koreader/koreader-base

- .travis.yml
- Makefile
- ffi/blitbuffer.lua
- ffi/mupdf.lua
I'm pretty sure busted v2.* causes current testing system
segmentation fault occasionally.
And this patch also removes debug hook in some computationally intensive
functions in blitbuffer so that coverage test won't timeout in travis.
> revert busted to v1.10.0

- Makefile
This fixes crash when loading libssl in some Kobo firmware
in which libcrypto.so.1.0.0 is missing in LD_LIBRARY_PATH.
> Use relative path to load dependency of libssl

- ffi/framebuffer_mxcfb.lua
I noticed that waiting for updates is broken on my Kobo Aura. According to strace, `MXCFB_SEND_UPDATE` is always called with `marker = 0`. This patch is supposed to fix that.
Tested only on Kobo Aura, but should work on other devices too, please test.
> Pass the correct update marker to MXCFB_SEND_UPDATE ioctl.

- .travis.yml
- Makefile
- Makefile.defs
Since libtool does not respect LDFLAGS we just hack it to remove the -lstdc++ dependency and feed the linker with the file `$(CC) -print-file-name=libstdc++.a`.
> Statically link libstdc++ for all shared libraries

- Makefile
- Makefile.defs
Now only Android build of sdcv uses static libglib, all other platforms use shared library.
> fix GLIBC_2.7 symbols in PocketBook build of sdcv cannot run on 4.x firmware

- .gitmodules
github is faster (got 9kbps from gnome.org servers).
> Replace glib git source

- ffi/kobolight.lua
After pending PR https://github.com/koreader/koreader/pull/1854 in koreader, we do not need these functions and variables in kobolight anymore.
> Remove legacy functions and variables in kobolight.lua

- Makefile.defs
- third.Makefile
- thirdparty/libzmq/CMakeLists.txt
- thirdparty/luajit/CMakeLists.txt
- thirdparty/openssl/CMakeLists.txt
* Fix zmq to link to libstdc++ statically again
* Bump LuaJIT & OpenSSL (1.0.2 is still a no-go w/ Clang. There's a patch available in ChromeOS, but the current trunk is also OK, so, meh, let's wait for that to hit a release).
> Minor buildsystem fixes

- ffi/util.lua
This is part of to add an auto-suspend function for Kobo, which does not have power management function in kernel.
Discussed in #1356 #1565 & #1814.
> Add util.getsec shortcut to get current time in seconds

- Makefile
This should hopefully fix the random segfault we have with busted+LuaJIT FFI
> test: disable auto-insulate in busted

- thirdparty/mupdf/CMakeLists.txt
The official git repo is breaking our ci tests...
> build(fix): use gitlab mirror for mupdf build

- Makefile.defs
- Makefile.third
- thirdparty/sqlite/CMakeLists.txt
Right now, it's not added as a dependency for the main target. If we decided to adopt sqlite in the future, we can just add $(SQLITE_LIB) to all.
> thidparty: add sqlite target

- Makefile.defs
- Makefile.third
- thirdparty/leptonica/CMakeLists.txt
Because my original fix broke builds on glibc < 2.22 (i.e., basically all we actually care about :D).
> Really fix #421

- .travis.yml
- thirdparty/libk2pdfopt/CMakeLists.txt
This change is part of Android NDK 11c build fixup. This issue has been discussed in #2043 of koreader. The change to add a define for android build has been merged into libk2pdfopt, so bump koreader-base to fix this issue.
> bump libk2pdfopt - fix android build with NDK 11c

- thirdparty/tesseract/CMakeLists.txt
- thirdparty/tesseract/tesseract-android.patch
This change is part of android NDK 11c toolchain migration, which has been discussed in #2043 of koreader (https://goo.gl/8oSJGy)
1. Update tesseract to latest release build 255c31fe31c418fd93cd2dde5941e0f923ab51ca.
For the sample.pdf in our testdata, both version cannot work very well, i.e. the text selection won't be able to select the correct word.
2. Add a patch to disable librt in tesseract, which won't be provided in NDK 11c.
> Update tesseract to latest release 255c31 and fix android build issue (librt won't be provided in NDK 11c)

- ffi/blitbuffer.lua
This should fix the kobo screenshot segfault.
> blitbuffer(fix): use getWidth and getHeight in :writePNG

- thirdparty/gettext/CMakeLists.txt
- thirdparty/tesseract/CMakeLists.txt
This issue has been discussed at koreader issue 2043 https://github.com/koreader/koreader/issues/2043
This change adds libc in gettext ld flags.
> Fix build break of gettext library with android NDK 11c

- Makefile.third
- thirdparty/tar/CMakeLists.txt
- thirdparty/zsync/CMakeLists.txt
Running a non-PIE binary on Android L will cause an error:
```
Error: only position independent executables (PIE) are supported
```
But if we link the binary with `-static` option it will have no dynamic section thus being PIE. Tested on MX4 Android 5.1.
> fix position independent executables (PIE) error on Android L

- Makefile.defs
- Makefile.third
- thirdparty/leptonica/CMakeLists.txt
- thirdparty/leptonica/leptonica-1.72-fmemopen-arm-compat-symbol.patch
- thirdparty/leptonica/leptonica-1.74-fmemopen-arm-compat-symbol.patch
Turns out the compat symbol is pinned to a different version on arm than
on x86, which explains the discrepancies we were seeing (2.2.5 on x86
vs. 2.4 on ARM).
Since we now have the code to check the TC glibc version, keep using that
check, but only when doing non-emulator builds (i.e., targeting arm).
Make that clear in the variable name and the comments.
And, most importantly, fix the patches so we're actually using the
compat symbol for arm, not x86, since this is where we care about it ;).
This fixes arm builds with current Ubuntu TCs, for instance.
Fix #2188 (thanks for the feedback, @tigran123 ;)).
> Clearup the leptonica fmemopen compat symbol mess.

- thirdparty/turbo/turbo.patch
My fault in last patch, ffi.C.signal or ffi.C.sysv_signal won't work in ffi.C.
> ffi.C triggers undefined symbol error in turbo

- Makefile.defs
In Makefile.defs, a dash is missing in the ARMV6_GENERIC_ARCH variable, making the build process stop working.
> Add missing dash

- Makefile
- Makefile.defs
- Makefile.third
- thirdparty/lj-wpaclient/CMakeLists.txt
A bug in lj-wpaclient causing it to identify the wrong network as the currently connected one.
> fix: only build popen for kindle & bump lj-wpaclient for bug fix

- thirdparty/zlib/CMakeLists.txt
after 3 years, zlib finally received a minor version bump and removed the old download link. As a result, our build is broken. Switching to fedoraproject.org as a workaround.
> build(fix): update zlib download link for 1.2.8

- thirdparty/czmq/CMakeLists.txt
This works around the readdir_r being depracated error in glibc 2.24. References #471.
> czmq: Add -Wnoerror to CFLAGS

- thirdparty/lj-wpaclient/CMakeLists.txt
@lgeek reported that many Linux systems report results message with warning level instead of info.
> bump lj-wpaclient for bug fix

- cre.cpp
See https://github.com/koreader/crengine/pull/69 for details.
Bumped crengine.
Added fix for a correct display of old (before this crengine mod) saved highlights that included punctuation at edges.
Well, I didn't use highlights at all, so I'd be happy if one of you who do, and have such epubs near the emulator, could test on the emulator that everything feels right (old highlights display the same, new hightlights are fine, text selection is indeed better). Thanks !
> More accurate word detection and text selection

- .luacheckrc
- ffi/framebuffer.lua
- ffi/pic.lua
This makes it so you're not absolutely overwhelmed by errors when you run luacheck and fixes a couple of minor things where luacheck is clearly complaining for a reason.
> Added .luacheckrc

- .ci/before_install.sh
- .ci/build_script.sh
- .ci/common.sh
- utils/pdfattach
Build array of files with:
```bash
mapfile -t shellscript_locations < <({ git grep -lE '^#!(/usr)?/bin/(env )?(bash|sh)' && git ls-files ./*.sh; } | sort | uniq)
```
Check with:
```bash
for shellscript in "${shellscript_locations[@]}"; do
echo -e "${ANSI_GREEN}Running shellcheck on ${shellscript}"
shellcheck "${shellscript}" || SHELLSCRIPT_ERROR=1
echo -e "${ANSI_GREEN}Running shfmt on ${shellscript}"
if [ "$(cat "${shellscript}")" != "$(shfmt -i 4 "${shellscript}")" ]; then
echo -e "${ANSI_RED}Warning: ${shellscript} does not abide by coding style"
shfmt -i 4 "${shellscript}" | diff "${shellscript}" - || SHELLSCRIPT_ERROR=1
fi
done
```
See https://github.com/koreader/koreader/blob/6f037cec30673a41492b727648988cc598d40432/.ci/helper_shellchecks.sh
> (minor) some shell code quality and formatting fixes

- ffi/blitbuffer.lua
Not used much by koreader, except when loading a cached TileCacheItem and in one unit test.
(But I witnessed huge memory leaks when playing with cached cover images and some thumbnails view - not sure i'll end up making something of that, but this bug should be fixed).
This setAllocated(1) is what will make the calls to free() actually do some freeing, it's what used in this file in all other places after a ffi.C.malloc() is made.
> Fix memory leak with BB.fromstring()

- Makefile.third
- thirdparty/czmq/CMakeLists.txt
- thirdparty/freetype2/CMakeLists.txt
- thirdparty/gettext/CMakeLists.txt
- thirdparty/giflib/CMakeLists.txt
- thirdparty/libjpeg-turbo/CMakeLists.txt
- thirdparty/libpng/CMakeLists.txt
- thirdparty/libzmq/CMakeLists.txt
The `libtool` version >= 2.4.6 don't have this problem and won't be affected by the patch. See comments in #482.
> [fix] patch libtool version < 2.4.6 to generate lib without version suffix for Android

- thirdparty/djvulibre/CMakeLists.txt
- thirdparty/turbo/CMakeLists.txt
- thirdparty/turbo/turbo.patch
fixes compilation errors reported in https://github.com/koreader/koreader/issues/3069
does not fix runtime errors under fedora (due to lua5.3 vs lua 5.1), though
> fix compile errors under Fedora due to -Werror

- cre.cpp
crengine: fix parsing of long decimal values in css and new Polish and French hyph dictionaries
cre.setEmbeddedFonts() to make this crengine feature available to koreader (having a go at https://github.com/koreader/crengine/issues/76)
> Bump crengine and add cre.setEmbeddedFonts()

- thirdparty/sdcv/CMakeLists.txt
Needed by: Dict settings menu: list dictionaries, and allow disabling them https://github.com/koreader/koreader/pull/3144
> update sdcv to consider -u params to be already utf8

- cre.cpp
Will allow crengine to use new default fonts when dealing with css font-family.
Details in:
https://github.com/koreader/crengine/pull/83
https://github.com/koreader/koreader/pull/3149
> Added cre.setAsPreferredFontWithBias()

- ffi/SDL1_2.lua
- ffi/SDL2_0.lua
- ffi/input.lua
- ffi/input_SDL2_0.lua
This will send Alt + F4 on any SQL quit event, whether from Alt + F4 or
another interaction with the window manager. The frontend can subsequently
mount an appropriate response by obliterating itself.
> SDL: handle quit event

- ffi/framebuffer.lua
During the unit tests fb:getDPI() is hit multiple times and self.dpi has to be filled from scratch.
This results in multiple calls to `os.getenv("EMULATE_READER_DPI")`. No biggie you would think, but
for some reason this causes memory use to quickly balloon out of proportion and exceed the 2 GB limit.
> [fix] ffi/framebuffer: memory use explosion in unit tests

- .ci/android_install.sh
- .travis.yml
- Makefile
- Makefile.defs
- toolchain/Makefile
Updates some stuff.
`NDKABI?=14` is important for specifying something custom for testing.
Also see https://github.com/koreader/android-luajit-launcher/pull/59
> Android NDK 15

- ffi-cdecl/posix_decl.c
- ffi/posix_h.lua
- ffi/util.lua
Needed to implement cancelable dict lookup.
Checking if `static const int FIONREAD = 21531; ` does not fail here...
> Added util.getNonBlockingReadSize(luafile)

- ffi/mupdf.lua
- ffi/mupdf_h.lua
mupdf.renderImage() may not scale the image to the width & height provided, see https://github.com/koreader/koreader/pull/3253#issuecomment-331702912.
I haven't tested that much for side effects, but it seems to work for menu images (they look more blury, less pixelized, dunno if it's actually better and good).
If you can test the rendering results on various sizes/dpi, upscale/downscale, I'm not that much able to appreciate that.
The code in mupdf for the scaling is in mupdf/source/fitz/draw-scale-simple.c fz_scale_pixmap_cached, and I don't even know what algorithm it used :|
> Add proper scaling to mupdf.renderImage()

- ffi/blitbuffer.lua
- ffi/mupdf.lua
We get better quality scaling with MuPDF than our internal BlitBuffer:scale(), so we'll use it instead in ImageWidget.
> Added mupdf.scaleBlitBuffer() for better scaling

- Makefile.defs
- thirdparty/czmq/CMakeLists.txt
- thirdparty/filemq/CMakeLists.txt
- thirdparty/freetype2/CMakeLists.txt
- thirdparty/giflib/CMakeLists.txt
- thirdparty/libjpeg-turbo/CMakeLists.txt
- thirdparty/libpng/CMakeLists.txt
- thirdparty/libzmq/CMakeLists.txt
- thirdparty/zyre/CMakeLists.txt
According to https://gpac.wp.imt.fr/2011/09/01/jpeg-support-for-android-resolving-libjpeg-so-conflicts/
> Google’s dynamic libraries are always loaded first as of Android 2.3. This is annoying because this affects numerous programs and also other dynamic libraries (such as zlib, libpng, …)
> […]
> The best solution we found is to rename the dynamic library to a non-usual name. libjpeg.so is now named libjpegdroid.so for the GPAC package.
Of course a better mechanism for doing exactly that already exists, so this patch reverts http://git.savannah.gnu.org/cgit/libtool.git/commit/?id=8eeeb00daef8c4f720c9b79a0cdb89225d9909b6 which makes libtool >=2.4.6 generate versionless libs when the target is Android.
Alternatively we could change the librares_names_spec and soname_spec to include …
> [fix] Versioned android libs

- toolchain/Makefile
I got `Error: Ignoring unknown package filter 'build-tools-26.0.1` otherwise and in result a non-functioning build
> add --all flag to android update sdk command

- cre.cpp
- ffi/mupdf.lua
Support for colored rendering is already there for all engines/formats. It just needs a few fixes, and enabling it. This is the stuff needed in base.
> mupdf, cre: allow for optional colored rendering

- thirdparty/luasec/CMakeLists.txt
- thirdparty/openssl/CMakeLists.txt
* Bumping luasec takes care of proper TLS encryption.
* Bump OpenSSL to the latest 1.0.2l and disable insecure deprecated SSLv2 and SSLv3.
> [fix] Ignore deprecated SSLv2 and SSLv3 encryptions

- .gitignore
- Makefile
This is to aid switching between builds with and without KODEBUG. LuaJIT requires a manual `make clean` if you do.
> Makefile: add luajit-clean target and auto-call it

- .luacheckrc
- ffi/blitbuffer.lua
Also remove what appears to be an unused legacy function,
`BB_mt.__index:blitFromRotate(source, degree)`. We now
have the much better `BB:rotate()` and related functions.
> [chore] blitbuffer luacheck fixes

- Makefile
- Makefile.defs
git-rev was moved to the frontend in 4e99f99f8b88e88cfcb544239971b46c3ed9abc1
because it's used as a versioning tool for the entirety of KOReader. However,
there are uses for keeping an easy to reference base git-rev as well.
It looks like the easiest way to ensure CircleCI cache is updated is to use a key.
https://circleci.com/docs/2.0/configuration-reference/#save_cache
In our case we can use `{{ checksum "filename" }}` to decide whether base has
changed and whether we should save a new base cache.
Presently the cache from early September is always reused and hence base will
always be compiled in the frontend CircleCI build.
> Reintroduce base git-rev

- ffi/framebuffer_android.lua
@poire-z Turns out I significantly overcomplicated things due to my earlier debugging-related activities while I was trying to figure out what went wrong.
The landscape problem was rudimentary: when you rotate the screen, so do "width" and "height", which I had matched up with the "physical" dimensions.
When you don't pass any other parameters to `blitFrom` it automatically does the equivalent of
```lua
bb:blitFrom(ext_bb, 0, 0, 0, 0, ext_bb:getWidth(), ext_bb:getHeight())
```
The only part of my earlier fix that was actually properly relevant was adding in `self.full_bb`, which doesn't yet exist the very first time it's called.
> [fix] ffi/framebuffer_android: landscape mode was broken

- .ci/android_install.sh
- .travis.yml
- Makefile
- Makefile.defs
- thirdparty/gettext/CMakeLists.txt
This makes the build less stuck to its current ARM paradigm.
Use `ANDROID_ARCH=x86` to build for x86.
References koreader/koreader#1815
> [chore] Add ANDROID_ARCH environment variable

- Makefile
- thirdparty/djvulibre/CMakeLists.txt
- thirdparty/djvulibre/android.patch
References https://github.com/koreader/koreader/issues/1534
> [Android] Build libdjvu

- .travis.yml
- Makefile.defs
- Makefile.third
- thirdparty/sdcv/CMakeLists.txt
Deprecates our fork because we've got all improvements included upstream now.
<hr>
Tagged WIP because there are a couple of things remaining that need to be fixed, probably only for Android.
> [build] sdcv: change to upstream 0.5.2

- thirdparty/sdcv/CMakeLists.txt
- thirdparty/sdcv/sdcv.patch
(temporary) patch to have Enabling/Disabling dictionaries working with sdcv 0.5.2.
See https://github.com/koreader/koreader/pull/3378
> sdcv patch: allow utf8 encoded or not-found -u dictnames

- thirdparty/sdcv/sdcv.patch
Second attempt at solving this problem. See https://github.com/koreader/koreader/pull/3378#issuecomment-338478405
> sdcv patch: allow utf8 encoded in -u dictnames (try 2)

- thirdparty/sdcv/sdcv.patch
Force LC_ALL=en_US.UTF-8, which may be empty on Android
Added comments around previous modifications.
See https://github.com/koreader/koreader/pull/3378#issuecomment-338623549
> sdcv patch: allow utf8 encoded in -u dictnames (try 3)

- thirdparty/sdcv/sdcv.patch
Also force LANG=en_US.UTF-8, which may be empty on Android and seem to be used even we set LC_ALL.
See https://github.com/koreader/koreader/pull/3378#issuecomment-338954972 , https://github.com/koreader/koreader/pull/3378#issuecomment-339010478
> sdcv patch: allow utf8 encoded in -u dictnames (try 4)

- Makefile
See https://github.com/koreader/koreader/issues/3419#issuecomment-339370648
> [build] Don't strip cross-compile files when KODEBUG=1

- Makefile
- Makefile.defs
Cleaning and rebuilding to get a build with and
without debugging symbols is freaking annoying.
> [build] Add -debug suffix to KODEBUG build

- .gitignore
- Makefile
- Makefile.third
- blitbuffer.c
- blitbuffer.h
- ffi/blitbuffer.lua
- ffi/framebuffer_SDL2_0.lua
- ffi/framebuffer_android.lua
- ffi/koptcontext_h.lua
- ffi/mupdf.lua
The C implementation is only built for the Android platform and the Emulator. With this patch [mcode allocation failure](https://github.com/koreader/koreader/issues/1416) on Android don't degenerate the performance. And we can even disable `jit` on Android that also means we can port Koreader to iOS on which `jit` is disabled by the system.
This implementation does not change the `blitbuffer` API and is transparent to the `frontend`.
> C blitbuffer implementation

- Makefile.third
This should fix koreader/koreader#3523.
> [build] Fixed zlib has no soname on arm-linux-gnueabi

- input/input-pocketbook.h
- input/input.c
This PR implements event-injection to control the automatic system-suspension on PB-devices.  See long comment in `input/input-pocketbook.h` for a more detailed description.
Fixes https://github.com/koreader/koreader/issues/3419 in a  way, as suspending is deactivated on start and re-enabled after 60 seconds which should be enough for the initial loading of plugins and book.
In the future this will be controlled from a koreader-plugin which re-enables suspension on onReaderReady() and may disable it while menus are open to smoothen the overall user-experience.
> Implement event-injection for PocketBook to control auto-suspension 

- thirdparty/mupdf/encrypted_zip.patch
fz_archive_needs_password didn't check the type of the archive, made an unsafe downcasting to fz_zip_archive. The result was a password prompt for tars (cbts).
This will be needed for https://github.com/koreader/koreader/issues/3533.
> Support tar in fz_archive_needs_password

- cre.cpp
koreader would have crengine segfault when opening an unrecognized format document (for example: a .epub in which `/mimetype` file is absent), because loadDocument would return false, but Koreader would continue to call methods on it (render()). This will allow us to return an error in init so we can display _No reader engine for this file or invalid file_ instead of crashing.
> cre: make loadDocument() return success or failure

- ffi-cdecl/mupdf_decl.c
- ffi/mupdf.lua
- ffi/mupdf_h.lua
- thirdparty/mupdf/external_fonts.patch
- wrap-mupdf.h
MuPDF related changes:
* support loading HTML from a string
* layout HTML for a given resolution
* use Noto Sans font when requested
Needed for https://github.com/koreader/koreader/issues/1776
> MuPDF document loading from memory, Noto Sans support

- blitbuffer.c
- ffi/mupdf.lua
This is about the cblitbuffer code used on the emulator (and android, although for some reason, I didn't notice the following problems on my android phone with the latest nightly...) and the new bbtypes we may get from the new mupdf 1.12.
Mupdf 1.8 used to always return BB8A or RGB32 from renderImage code.
Mupdf 1.12 now can return BB8 (from a greyscale jpeg) and RGB24 (from a color jpeg).
When viewing images from epub with ImageViewer, they would be fine when not scaled. But when scaled, they need to be blitted to a RGB32, and the cblitbuffer code would blit these BB8 or RGB24 with a full transparency, making the image full white. This sets a correct alpha of 0xFF so that no transparency is added (as BB8 and RGB24 do not carry any alpha info).
@chrox : do these additions look ok to you? …
> cblitbuffer: fix alpha in some bb conversions, and add a few more

- thirdparty/mupdf/CMakeLists.txt
- thirdparty/mupdf/no_icc_fixes.patch
MuPDF 1.12 outputs a warning for [JPEG](https://github.com/ArtifexSoftware/mupdf/blob/a292539cc9e5e91843d48e691038d9c1b529422c/source/fitz/load-jpeg.c#L149) or [TIFF](https://github.com/ArtifexSoftware/mupdf/blob/a292539cc9e5e91843d48e691038d9c1b529422c/source/fitz/load-tiff.c#L1149) images that include some ICC info/profile and that we can't use with our -DNO_ICC build. But for [PNG](https://github.com/ArtifexSoftware/mupdf/blob/a292539cc9e5e91843d48e691038d9c1b529422c/source/fitz/load-png.c#L361), there is no warning but an exception is thrown. This patch just change this throw to a warning.
So, when meeting such a PNG that embeds some ICC info, it would just output:
```
error: ICC Profiles not supported in NO_ICC build
warning: could not load ICC profile in PNG image
```
and show the …
> MuPDF patch: don't fail rendering some PNG images that includes icc profile

- thirdparty/mupdf/external_fonts.patch
* fall back to FreeSans.ttf if needed
* font filenames were not freed everywhere
* font properties (bold, italics, ...) were not set
> MuPDF font fixes

- ffi/posix_h.lua
- ffi/util.lua
`util.runInSubProcess()`: give child its own process group and use `kill(-pid)` in `terminateSubProcess `to kill child and its children.
Should allow us to safely run `os.execute()` in sub-process.
(No current project in which I would need that, I just had a try with `os.execute("sleep 60")` and it has a few side effects that this solves.)
> util.runInSubProcess(): give child its own process group

- ffi/blitbuffer.lua
I've been toying with making a MovebableContainer so we can move some widgets on screen, and got segfaults (in libc6.so or libcrengine.so!) when moving some widgets past the top left corner. Did not happen if I removed libblitbuffer.so.
I guess the missing BB.checkBounds were making cblibuffer draw/poke outside the malloc'ed buffer, so in some other code data (guess that's what is called a _buffer overflow_ :)
Shouldn't have had any impact, as current code is hardly drawing outside screen (dunno if that could be responsbile for some crashes on Android with nightmode when some viewport/fullscreen are involved).
I also moved the existing checkBounds _et al._ inside the `if use_cblitbuffer` sections, as the `else` all call `self:blitFrom` (line 750), where checkBounds are done anyway - so we …
> BB:colorblitFrom: add missing bounds check when use_cblitbuffer

- .ci/test_script.sh
- thirdparty/zlib/CMakeLists.txt
Get zlib download link back to http://zlib.net/ , where `All released versions of zlib` links to http://zlib.net/fossils (previously changed in #469)
> build(fix): update zlib download link

- cre.cpp
Bump crengine for https://github.com/koreader/crengine/pull/95
Also have getLinkFromPosition() and getPageLinks() additionaly return xpointers from position/source of link (so we can have a more precise "previous location" in location_stack).
Should have no impact on current code that does not use it.
I just want it in a nightly so I can test on my kobo for some time a followup to https://github.com/koreader/koreader/pull/3202 (_I would also have liked to have that when back from link, to again see where we were before jumping to link, but that's more complicated_)
> Bump crengine

- cre.cpp
Allow for quicker loading when interested in metadata only https://github.com/koreader/crengine/pull/123
Allow for more than 65535 different attribute values https://github.com/koreader/crengine/pull/124
Increase gamma values range https://github.com/koreader/crengine/pull/122
> bump crengine: quicker metadata loading and others

- cre.cpp
So we can show in the Notification the real gamma value (0.8, 1, 2.5, 15) instead of the index (5, 15, 31, 56) of the possible values array.
> cre: added getGammaLevel()

- ffi/SDL2_0.lua
- ffi/SDL2_0_h.lua
- ffi/framebuffer_SDL2_0.lua
@poire-z There seems to be some kind of memory leak present (unless it's something in front), which is not the biggest issue for what's more of an experimental proof of concept, but I might be missing something obvious.
In front I'm not quite finished with the proof of concept, but basic resizing works as you'd expect (besides the memory leak).
```diff
diff --git a/frontend/device/input.lua b/frontend/device/input.lua
index f595d25c..76de4578 100755
--- a/frontend/device/input.lua
+++ b/frontend/device/input.lua
@@ -345,7 +345,33 @@ function Input:handleKeyBoardEv(ev)
end
function Input:handleMiscEv(ev)
-    -- should be handled by a misc event protocol plugin
+    -- bit of a hack for passing SDL window resize events
+    local SDL_WINDOWEVENT_RESIZED = 5
+    local x = 0
+    local y = …
```
> [feat] SDL2: resize framebuffer implementation

- Makefile.defs
Forgot to push this back in October, see https://github.com/koreader/crengine/pull/90#issuecomment-338333188
<hr>
Some more info here: https://developers.redhat.com/blog/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/
Btw, there are more sanitize options, some of which are mutually exclusive.
Clang has 'em too. (Based on the same lib?) http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#ubsan-checks
> [build] Add -fsanitize=undefined to debug flags

- ffi/SDL2_0.lua
The next buffer might always contain garbage, and on X11 without
compositing the buffers will be damaged just by moving the window
partly offscreen, minimizing it, or putting another window
(partially) on top of it.
Handling `SDL_WINDOWEVENT_EXPOSED` is the only way to deal with
this without sending regular updates.
<hr>
A few illustrations of the effect that this solves when combined with a `UIManager:setDirty("all")` in front. A mere `SDL.SDL_RenderPresent(S.renderer)` in base comes close to fixing the problem but unfortunately doesn't completely.
> SDL2: handle SDL_WINDOWEVENT_EXPOSED

- ffi/framebuffer_android.lua
Fixes https://github.com/koreader/koreader/issues/3529
> [fix] ffi/framebuffer_android: separate invert blitbuffer

- ffi/SDL2_0.lua
- ffi/SDL2_0_h.lua
- ffi/framebuffer_SDL2_0.lua
This commit first renders the full updated blitbuffer to a temporary texture.
Subsequently it renders the updated rectangle from the temporary texture onto
the final texture, which has up to that point retained all of the old pixel
info. That final texture, of which only the one rectangular area was updated,
is then rendered to the window.
Without this, there are cases where a full screen (or at least bigger) refresh
is required that will not be obvious without first testing on a real device.
See https://github.com/koreader/koreader/pull/3804
Also fixes `EMULATE_READER_FLASH`, which was accidentally broken in 981bd40e1ca1c1152b702590fd85ae2d7cbf0ea6
> [feat] SDL2: update parts of window like a real device

- ffi/SDL2_0.lua
- ffi/SDL2_0_h.lua
This is a "dumb" implementation that spits out fake keyboard events.
* Left stick & d-pad: arrow keys
* Bumpers and right stick: page up/down
* Menu button: menu
* A: enter
* B: back
This is sufficient to use most of the program.
Made possible by @onde2rock's recent efforts in https://github.com/koreader/koreader/pull/3796
https://github.com/koreader/koreader/pull/3785 https://github.com/koreader/koreader/pull/3774
https://github.com/koreader/koreader/pull/3765 and https://github.com/koreader/koreader/pull/3745
> [feat] SDL2: preliminary gamepad support

- thirdparty/mupdf/CMakeLists.txt
A small size optimization. We don't print and we don't support forms, so there's no point to these for now.
> [build] MuPDF: disable CMYK plotter & javascript

- ffi/SDL2_0.lua
- ffi/input_SDL2_0.lua
It wouldn't make much sense to continue adding endless workarounds along the lines
of the getDroppedFile() function. For SDL multitouch events we could emit a number
of fake Linux kernel multitouch events but it seems more sensible to construct
gesture events out of SDL event information directly in front.
Emits a made up EV_SDL code to tap into the existing event system.
Also added SDL_MULTIGESTURE and SDL_WHEEL passthrough.
> [chore] SDL2: less hackish SDL event approach

- djvu.c
All of the `GURL` stuff in djvulibre is absurdly complicated and this does nothing to help.
References https://github.com/koreader/koreader/issues/542
```
04/06/18-10:20:48 WARN  cannot open document /mnt/onboard/.books/koreader_test/Михайлов ТФКП.djvu frontend/document/djvudocument.lua:42: ddjvu: ** Unrecognized DjVu Message:
** Message name:  ByteStream.open_fail
Parameter: %D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%20%D0%A2%D0%A4%D0%9A%D0%9F.djvu
Parameter: No such file or directory
ddjvu: 'ByteStream.cpp:704'
```
@poire-z Not quite sure if a situation is possible where there's no internal error message. in that case it'd return `0` which is no good… 
Basically I want the `handle()` function with a `return luaL_error(L, "cannot open DjVu file <%s>", filename);` at the end …
> djvu.c: return internal djvulibre error

- Makefile.defs
Nothing fancy here right now but it would technically need to include SDL2 (and maybe Gtk3) as well. An AppImage is supposed to run independently. However, for AppImage purposes those can simply be copied from the host system.
> [build] Makefile.defs: add AppImage target

- Makefile.defs
`-march=native` is good for the emulator but not for an AppImage that needs to support various CPU models.
References https://github.com/koreader/koreader/issues/3853.
> [fix, build] AppImage use `-mtune=generic -march=x86-64`

- ffi/blitbuffer.lua
Fix segfaults with highlights spanning multiple pages (not possible when selecting, but possible with previous highlights after changing font size or other layout parameters).
The added `BB.checkBounds()` are exactly the same that are done in `self:paintRect()` in the `else` (so, it was properly done when `not use_cblitbuffer`)
Similar to what was done in #589.
> BB:dimRect/lightenRect: add missing bounds check when use_cblitbuffer

- ffi/giflib_h.lua
- ffi/pic.lua
pic.lua was returning each frame as-is. Very often, frames are just a mask to apply on previous frame, so we need to combine them and paste each one over the previous.
Adds support for transparency for that, and limited support for the rare other "dispose" modes of the GIF spec.
This makes the little (or full size) animated territories expansion maps (gray backround with a year displayed) found on these Wikipedia pages, when saved as a GIF, correctly displayed by PicDocument:
https://fr.wikipedia.org/wiki/Empire_romain https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Roman_Republic_Empire_map.gif/220px-Roman_Republic_Empire_map.gif
https://fr.wikipedia.org/wiki/Saint-Empire_romain_germanique https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/HRR.gif/220px-HRR.gif …
> picdocument: fix rendering of animated GIFs

- .travis.yml
These are the ones that include the new TC, see https://github.com/koreader/virdevenv/pull/14 and https://github.com/koreader/koxtoolchain/pull/3
> [chore, CI] Update to latest Docker images

- ffi/giflib_h.lua
- ffi/pic.lua
This will allow using giflib to render GIF images, which is better than MuPDF for rendering the first frame of an animated GIF, and will allow getting all its frames.
Also fix alpha value when combining animated GIF frames (although I don't really get how alpha works - I thought it would matter only on RGB32A, not on RGB32) but using 0xFF instead of 0x00 gives always the expected image (with 0x00, I sometime got a blank image, or just some shadows - might be related to the GIF transparency...)
> Adds Pic.openGIFDocumentFromData()

- ffi/framebuffer_SDL2_0.lua
Embarrassingly, I recently introduced two (!) regressions in rotation handling.
1. The new blitbuffer created when resizing didn't take rotation into account. Cf. https://github.com/koreader/koreader-base/pull/614
2. The feature to emulate E Ink refresh didn't properly distinguish between BB rectangles and "physical" SDL rectangles. Cf. https://github.com/koreader/koreader-base/pull/626
Reported by @poire-z in https://github.com/koreader/koreader/pull/3812#issuecomment-386806443
> [fix] SDL2: resolve rotation issues

- Makefile
- Makefile.defs
- Makefile.third
Fixes noise, see https://github.com/koreader/koreader-base/pull/640#issuecomment-386825021
> [fix, build] Makefile target should be dropbearmulti, not dropbear

- cre.cpp
Includes:
- Factorize ldomXPointer::getRect() and ::getRectEx() https://github.com/koreader/crengine/pull/187
- Toggable alternative rendering method for list items https://github.com/koreader/crengine/pull/188
- Compute nodeStyleDisplayHash and adds isBuiltDomStale() https://github.com/koreader/crengine/pull/189
> Bump crengine: alternative rendering method for list items

- .ci/test_script.sh
- cre.cpp
So we can manage the cache file from lua side (delete, add/remove a ".keep" extension, etc...)
Bump crengine for _Adds tinyNodeCollection::getCacheFilePath()_ https://github.com/koreader/crengine/pull/190
> cre: adds getCacheFilePath()

- cre.cpp
The previous usage of `getIntProperty("crengine.dom.version")` and `setIntProperty("crengine.dom.version", version)` had some unwelcome side effects.
Let's wait for https://github.com/koreader/crengine/pull/192 to be merged to bump crengine with this PR too. (I cancelled the Travis checks to save a few trees)
> Adds cre.getLatestDomVersion() and cre.requestDomVersion()

- cre.cpp
Includes:
- Avoid page break between a node and its borders https://github.com/koreader/crengine/pull/207
- Allow building an alternative TOC from document headings https://github.com/koreader/crengine/pull/205
Adds proxy methods in cre.cpp: buildAlternativeToc() and isTocAlternativeToc()
> bump crengine: alternative TOC, no page break on borders

- ffi-cdecl/koptcontext_cdecl.c
- ffi-cdecl/pthread_cdecl.c
- ffi/koptcontext_h.lua
- ffi/mupdf.lua
- ffi/pthread_def_h.lua
- ffi/pthread_h.lua
- ffi/pthread_x64_h.lua
- ffi/pthread_x86_h.lua
(Use leptonica types directly. Functionally identical).
It already needs postprocessing for the leptonica require anyway...
> Prettier koptcontext FFI :D

- Makefile
- Makefile.defs
- Makefile.third
- ffi-cdecl/SDL2_0_decl.c
- ffi/SDL2_0_h.lua
- ffi/framebuffer_mxcfb.lua
- thirdparty/openssl/CMakeLists.txt
- thirdparty/openssl/openssl-origin-rpath.patch
... mmmmaaybe?
This time it's based on actual data, so, here's hoping!
Had to get rid of the insane/mysterious collision_test handling, because, of course, it changed behavior.
Since it's fairly obscure and dubiously useful anyway, not a huge loss.
I still documented what I could of its behavior on the KOA2, FOR SCIENCE! :D
This also help confirm that we really shouldn't be using A2 on REAGL Kindles, because it looks awful, so use DU + MONOCHROME, it works much better (even on my PW2).
> Unbreak KOA2 handling

- thirdparty/zsync/CMakeLists.txt
- thirdparty/zsync/zsync-android-build-p1.patch
- thirdparty/zsync/zsync-android-build-p2.patch
- thirdparty/zsync/zsync-openstack-abort.patch
Plus a new patch to:
* make it actually build
* make it abort gracefully when encountering the HTTP frontend of an
OpenStack container, instead of busy-looping for ever.
Addresses https://github.com/koreader/koreader/pull/4043/commits/0b448a0f0f7cc7f878f3717827a9838a32cd55ff from another angle.
> Bump zsync to git master

- thirdparty/fbink/CMakeLists.txt
Namely, LuaFileSystem, because we've been forgetting about it for three years since it's not handled in the thirdparty folder ;).
And FBInk, to pickup the out-of-Nickel fixes discussed in [KO#4043](https://github.com/koreader/koreader/pull/4043) ;).
> Bump some more third-party libs

- ffi/framebuffer_mxcfb.lua
- thirdparty/fbink/CMakeLists.txt
Fix #694
\o/
(Based on data from a Clara HD, but appears consistent with what we've seen from the other Mk7 kernels).
(I'll fold a bump to FBInk 1.0.0 in there once testing's done and it's actually tagged ;p).
> Flip the switch on the Mark 7 codepath

- blitbuffer.c
Fixes behavior on Kindle, which is palettized 8bpp, so the off-white was
very obnoxious ;).
Funnily enough, the slightly-off white @ #fefefe was rendered not as #FFF, but as #EEE (the next palette entry besides white), despite being much farther away. EPD quantization is weird.
> Port color conversions fixes from #590 to the cblitbuffer implementation

- cre.cpp
Includes:
- HTML: fix parsing of non-lowercase stylesheet link tags https://github.com/koreader/crengine/pull/225
- Allow creating no default document on load
- Rework styles loading, avoid nodes styles re-init in somes cases https://github.com/koreader/crengine/pull/226
- Fix support of style "white-space: pre"
> bump crengine: various loading and styles fixes

- ffi/framebuffer_linux.lua
We need it on Kobo to handle 16bpp-specific tweaks
Needed for [KO#4137](https://github.com/koreader/koreader/issues/4137)
> Export framebuffer bitdepth

- Makefile
- Makefile.third
- thirdparty/fbink/CMakeLists.txt
And bundle it on Kindle too, because I'm going to need it there to move everything to FBInk
That'll allow us to get rid of some shell shenanigans to handle eips properly everywhere, as well as unify a couple of scripts between Kindle & Kobo.
> Bump FBInk to 1.5.0

- .ci/build_script.sh
- .travis.yml
- Makefile.defs
- thirdparty/fbink/CMakeLists.txt
* Namely, the highly nitpicky renaming from `sony_prstux` to `sony-prstux` (c.f., [KO#4198](https://github.com/koreader/koreader/pull/4198)) ;).
* Bump FBInk to 1.6.2, which includes a fix for progress bars' width that could be off by 1px, potentially causing unsightly artifacts depending on the speed and eInk controller...
> Minor cleanups after #724, part two!

- cre.cpp
Footnote detection code is quite huge, and tweakable from Lua with the use of flags.
See frontend PR (coming soon) for details.
Also adds optional parameter to `getPageLinks()` to request only internal links.
Also have `getPageLinks()` add to each link the segments (rect for each line) it spans on the page, for a more accurate computation of distance from gesture position.
> cre: adds isLinkToFootnote() and highlightXPointer()

- cre.cpp
By starting or ending text selection on a punctuation char, a quote or a paren..., these will now be included in the text selection and the higlighted text. Details and screenshots in https://github.com/koreader/koreader/issues/4134#issuecomment-428617973
bump crengine, which includes:
- Avoid wrap on a space before or after some specific chars https://github.com/koreader/crengine/pull/237
> cre: allow non-word chars in text selection

- cre.cpp
Needed by frontend code to solve a few issues when top full status bar is used,
as in https://github.com/koreader/koreader/pull/4261#issuecomment-429265831
> cre: adds getHeaderHeight() to get full status bar height

- blitbuffer.c
- cre.cpp
Fix text selection behaviour introduced in #742 when holding only and not panning.
Otherwise, when holding to just do a dictionary lookup:
- when holding on a space or a punctuation, this char would be and stay highlighted while the dict lookup would not happen because text selection would have been cleaned and become empty.
- when holding on a blank space (eg: after the last word on a non-full last line), no text would be selected here, but getWordFromPosition(), used as a fallback, would return the nearest word on above or below line, which would then be used as dict lookup input, with a few side effects: no highlighting done while looking up; if then Highlighted from the dict window button and bookmarked, the bookmark would have no text and no highlight box would be shown when …
> cre text selection: grab word when just holding and not panning 

- Makefile.defs
- thirdparty/cmake_modules/koreader_thirdparty_git.cmake
Uses a fairly conservative value of 50 for now. Also implements a fallback to pull in the entire repo if that's not enough.
This will mainly help to speed up the nightly builds and the CI builds, but it will also reduce the space and time investment for potential hackers.
> [build] Pull in thirdparty repos with --depth 50

- djvu.c
Pretty much what the title says. This implements the `getMetadata()` function for DjVu documents, following in the style of the same for the PDF implementation.
This just dumbly copies all the metadata key-value pairs into a lua table. The intent is to give the frontend everything we possibly can and let it figure out what to do with the info, an example of which can be found in the companion pull request koreader/koreader#4314.
This is my first foray into koreader's code, not to mention anything lua-related. I tried to copy the surrounding style as much as I could, and I tested this out on my actual kindle. However, I'd not be surprised if I'm missing something obvious. Anyway, I hope this turns out to be helpful.
> [Feature] Implement getMetadata() function for DjVu documents

- Makefile
- Makefile.defs
Use tabs everywhere as talked in #745. Also I found old code which is not used anywhere. Remove it.
> [chore]: Makefile.defs - use tabs everywhere and remove old unused code

- thirdparty/libjpeg-turbo/CMakeLists.txt
As in the libjpeg-turbo building instructions:
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/43ce78e0321da44fe359f40a847fe79d2de06d4c/BUILDING.md
Cf. https://github.com/koreader/koreader/issues/4254
> [fix] libjpeg-turbo crash on Android <=4.x

- ffi-cdecl/include/mxcfb-cervantes.h
- ffi-cdecl/mxcfb_cervantes_decl.c
- ffi/framebuffer_mxcfb.lua
- ffi/mxcfb_cervantes_h.lua
Removed a bunch of unused structs & kernel code. Not really needed but makes the file easier to read/understand.
Use same MXCFB_SEND_UPDATE because MXCFB_SEND_UPDATE_OLD was borked and made all legacy devices stupid enough to not update the screen :sob:
Add a bunch of epdc flags from Cervantes 2013 - Cervantes 4 kernels.
Rename is_new to is_reagl to be a little more descriptive.
This fixes #754 (in particular: https://github.com/koreader/koreader-base/issues/754#issuecomment-438485877)
> [Cervantes]: waveforms & flags

- Makefile.defs
Forgot to push this, so https://github.com/koreader/koreader/pull/4352
was incomplete.
Cf. https://github.com/koreader/koreader-base/pull/768
> [build, Android] libjpeg-turbo: make sure to copy the right lib

- .ci/android_install.sh
- .ci/build_script.sh
- .travis.yml
This deprecates the outdated r11c to "it may not break" status while ensuring that our nightly builds will succeed.
> [build] Drop Android NDK r11c; also test build on Docker `koandroid`

- ffi/framebuffer_android.lua
Forgot to set rotation on the second blitbuffer. Fixes https://github.com/koreader/koreader/issues/3945.
> [fix] Android nightmode landscape

- Makefile.third
Fix this error on mac
```
ffi.load: libs/libmupdf.dylib
ffi.load (warning): dlopen(libs/libmupdf.dylib, 5): @rpath/libjpeg.8.dylib
Referenced from: /Users/pazos/Desktop/koreader/base/build/x86_64-apple-darwin18.2.0/libs/libmupdf.dylib
Reason: image not found
./luajit: ./setupkoenv.lua:30: Not able to load dynamic library: libs/libmupdf.dylib
```
https://github.com/koreader/koreader/issues/4375#issuecomment-444688176
> [mac] mupdf.dylib: load libjpeg from libs/ instead of @rpath

- ffi/framebuffer.lua
Make it human readable (hopefully), heavily commented, simpler, and symmetrical, so we actually get easy access to Inverted Portrait.
Attempt to fix [KO#3002](https://github.com/koreader/koreader/issues/3002) in the process by making sure inversion trickery is only applied on explicit UI interaction (other end of that in [KO#4291](https://github.com/koreader/koreader/issues/4291).
AFAICT, that works as expected \o/.
> Dust up setScreenMode's logic

- cre.cpp
Includes https://github.com/koreader/crengine/pull/249:
- Fix restore of last xpointer in scroll mode
- Adds support for private CSS property "-cr-hint:"
- CSS: Implement -cr-hint: toc-level and toc-ignore
- CSS: Implement -cr-hint: footnote-inpage
- Tweak "in-page" footnotes rendering
cre.cpp: adds support for `-cr-hint:` `noteref`, `noteref-ignore`, `footnote` and `footnote-ignore` in footnote detection code.
This support is quite straightforward, and needs the styled element to have the targeted `id` AND to contain the full footnote. I'll see about doing more (like extending the footnote to more than one final block, like it's done in the rest of the detection code) when I meet a book that needs that.
Also see https://github.com/koreader/koreader/pull/4440.
> bump crengine: support for private CSS property "-cr-hint:"

- Makefile.defs
- ffi/koptcontext.lua
- ffi/leptonica_h.lua
- thirdparty/leptonica/CMakeLists.txt
- thirdparty/leptonica/leptonica-1.74.1-fmemopen-arm-compat-symbol.patch
- thirdparty/libk2pdfopt/CMakeLists.txt
Involves bumping Leptonica to v1.74.1, the one k2pdfopt 2.42 expects, as well as fixing our buildsystem to include k2pdfopt's new patches to Leptonica.
Re: https://github.com/koreader/koreader/issues/4448
Re: https://github.com/koreader/koreader/issues/4467
> Fix undefined _dewarpBuildPageModel_ex symbol in k2pdfopt

- ffi/framebuffer_linux.lua
Should properly handle 600x800 devices, like in
https://github.com/koreader/koreader/issues/4476
> More PB fb setup trickery

- blitbuffer.c
Scanning y in the outer loop and x in the inner loop allows scannning memory linearly and avoid CPU cache trashing.
(This gives a 25% performance boost on the emulator in portrait mode, and might as well on Android.)
See https://github.com/koreader/koreader-base/pull/746#issuecomment-458105542
> blitbuffer.c: small optimisation by switching x/y loops

- cre.cpp
Includes:
- Update french hyphenation pattern https://github.com/koreader/crengine/pull/255
- epub.css: update style for 'blockquote' https://github.com/koreader/crengine/pull/256
- DrawBuf: count nb of images and surface drawn
cre.cpp drawCurrentPage(): returns nb of images and % of buffer surface used when drawing images.
This will allow frontend code to decide if refresh with (possibly costly) dithering should be used or not on devices with HW dithering capabilities. See https://github.com/koreader/koreader/pull/4541 , https://github.com/koreader/koreader/pull/4541#issuecomment-459947281.
> bump crengine: count nb of images drawn & others

- blitbuffer.c
- blitbuffer.h
- ffi/framebuffer.lua
- ffi/framebuffer_mxcfb.lua
... on supported devices.
That is:
Kindle: KOA2+ (KOA2, PW4)
Kobo: Mk.7+ (Clara, Forma)
Possibly Cervantes 3 & 4, but the required "new" codepath isn't implemented in KO (pinging @pazos) ;).
Used by [KO#4541](https://github.com/koreader/koreader/pull/4541)
> Honor dithering requests from UIManager

- ffi-cdecl/posix_decl.c
- ffi/posix_h.lua
- thirdparty/fbink/CMakeLists.txt
- thirdparty/lpeg/CMakeLists.txt
The POSIX variant is unavailable on Android (c.f., #4543).
Fix https://github.com/koreader/koreader/issues/4543
> Switch to GNU basename in ffi.util

- ffi/SDL2_0.lua
> Log something useful if SDL2 fails to init

- ffi/framebuffer_linux.lua
Purely for documentation purposes, because that little function in the kernel epdc driver has been my new best friend today ;).
> Jot down the alignment values used on Kobo/Kindle kernels

- ffi-cdecl/posix_decl.c
- ffi/framebuffer.lua
- ffi/framebuffer_linux.lua
- ffi/posix_h.lua
Useful in combination with a refreshFull to prevent ghosting.
> Provide a clear screen method that bypasses blitting on Linux fb

- cre.cpp
Includes https://github.com/koreader/crengine/pull/261:
- Page drawing: don't clip on left and right margins
- Rendering: draw borders before their inner content
- Harfbuzz: fix rendering when hyphenating on a ligature
cre.cpp:
- adds getNextVisibleChar() and getPrevVisibleChar()
- fix getNext/PrevVisibleWordStart/End to return nil when reaching end/start of book and moving again is not possible
> bump crengine: fix font clipping and hyphenation with HB

- ffi/framebuffer_mxcfb.lua
Lastest @NiLuJe tweaks made more evident that cervantes framebuffer was borked. This fix this by requesting AUTO waveforms instead of REAGAL and using DU instead of A2 (in monochrome).
This fixes nightmode too, which was pretty broken, but who cares.
IMO, this improves the quality of life of (recent) cervantes users, but maybe @avsej can give us a second opinion.
> fix cervantes fb again, unbreak night mode too

- cre.cpp
Includes: https://github.com/koreader/crengine/pull/263
- Footnotes, text selection: don't clip on left and right margins
- Fix underline overflowing last word
- Fix ldomXPointer::getRectEx(), cleanup getSegmentRects() workaround
- Update remaining font metrics from Int8 to Int16
- [CI] Add .codacy.yml https://github.com/koreader/crengine/pull/262
cre.cpp:
- adds compareXPointers()
> bump crengine: font, text and highlights fixes

- ffi/framebuffer_linux.lua
Basically doing the same as Kobo/Kindle kernels.
This should hopefully be much saner, and much more compatible.
In case there's any weird corner-cases (einkfb?) or extra-broken
devices, the safety check from #4416 should take care of it.
> Simplify the whole PB fb setup shenanigan

- Makefile.defs
- thirdparty/mupdf/CMakeLists.txt
- thirdparty/mupdf/honor_cflags.patch
- thirdparty/mupdf/no_arm_asm.patch
* Avoid compat CFLAGS on kobo & kindle-legacy when using our TCs
* Disable ARM ASM in MµPDF, and honor debug builds
> A few minor buildsystem tweaks

- thirdparty/gettext/CMakeLists.txt
- thirdparty/libiconv/CMakeLists.txt
- thirdparty/tar/CMakeLists.txt
Fixes #823.
This is a simple one. https://ftp.gnu.org/ is currently offline but we shouldn't actually be using it anyway.
https://www.gnu.org/server/mirror.en.html
> First, for users/downloaders: the address http://ftpmirror.gnu.org/ multiplexes between the mirrors, trying to choose one that is nearby and up to date. E.g., http://ftpmirror.gnu.org/emacs/ goes to a mirror's directory of GNU Emacs. We recommend using this generic ftpmirror.gnu.org address wherever possible in links, documentation, etc., to reduce load on the main GNU server.
tl;dr http://ftpmirror.gnu.org should be more stable.
> [build] Download GNU deps from mirror

- cre.cpp
Includes https://github.com/koreader/crengine/pull/264:
- Fix text selection in some tables
- Add known HTML attributes to avoid cache issues
- Make existing context.AddLine() and pb_flag clearer
cre.cpp:
- gotoPos(): allow scrolling after end of document (to avoid not seeing the last line of a document that would be hidden by the footer bar). Will help fixing https://github.com/koreader/koreader/issues/4650
> bump crengine: fix text selection and cache issues

- thirdparty/libjpeg-turbo/CMakeLists.txt
https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.2
> Bump libjpeg-turbo to 2.0.2

- input/input-pocketbook.h
- input/input.c
The forked process based implementation of the PocketBook event thread has been replaced with a background thread based one. This should fix the hanging of Koreader process  on waking from suspension state every second time (koreader/koreader#4646). Koreader suspending can be achieved by:
- Pushing the _Home_ button => resume by selecting _koreader_ task in the Task Manager
- Pushing the _Power_ button => Push it again to resume
- Waiting until the _Auto-suspend_ timeout has passed => Push the _Power_ button to resume
The issue root cause is currently unknown, although it seems to be introduced by one of more recent firmware updates. Tested on _PB InkPad3 FW v.5.19.660_ and _PB Touch HD FW v.5.19.673_. Requires testing on more devices. It would be really nice to check if it doesn't break …
> PocketBook: Fix hanging on waking up from sleep

- ffi/framebuffer.lua
Makes sure custom DPI settings actually work for now.
This might not be quite the Right Thing™ but better slightly improprietary than broken.
See https://github.com/koreader/koreader/issues/4726 for discussion.
> [fix] ffi/framebuffer: set self.dpi in setDPI

- cre.cpp
Bump crengine for: docToWindowPoint(): adds isRectBottom parameter
cre.cpp: logical fix for getting boxes coordinates on screen, but fix mostly an issue in 2-pages mode where the top line of the second page was not highlighted, and its link couldn't be followed.
See https://github.com/koreader/crengine/pull/268 for details
> cre: fix highlight/link boxes in 2-pages mode

- Makefile.defs
- thirdparty/cmake_modules/DownloadProject.CMakeLists.cmake.in
- thirdparty/cmake_modules/DownloadProject.cmake
- thirdparty/sdcv/CMakeLists.txt
This module is like FetchContent in CMake 3.11, but for the moment it may be more inviting to hackers not to require that yet.
The principle is explained here: https://crascit.com/2015/07/25/cmake-gtest/
It allows us to work with CMake in a more natural environment for CMake-submodules, which are otherwise nigh-uncontrollable in between escaping variables in CMake syntax and CMake being extremely bad at taking command-line arguments. (A fact I utterly despise as a regular user just downloading a project to compile & try.)
Upping the minimum CMake version over 3.3 should also allow us to get rid of a few braindead Android-related workarounds for sdcv, where we had to completely force-feed the `.a` suffix.
> [build] CMake: Introduce DownloadProject module

- ffi/blitbuffer.lua
We've found more corner-cases not limited to 16bpp since the last
time...
Some of them barely even corner-y ;).
Re: https://github.com/koreader/koreader/pull/4782
>  Make the JIT loopunroll tweak mandatory when not using the C blitter

- thirdparty/freetype2/CMakeLists.txt
Also, enforce a working mmap, as it gets disabled for safety when
x-compiling.
> Bump FreeType to v2.10.0

- Makefile.defs
Otherwise it won't get cleaned by `make clean` or `make dist-clean`.
Also make it a little more ordered & legible.
> [fix] Makefile.defs: add sqlite to CMAKE_THIRDPARTY_LIBS

- Makefile.defs
Like https://github.com/koreader/koreader-base/pull/865 but only occurs when cross-compiling for certain platforms.
Cf. https://github.com/koreader/koreader-base/pull/866 for a possible solution where this could never be a problem.
> [fix] Makefile.defs: add lj-wpaclient to CMAKE_THIRDPARTY_LIBS

- thirdparty/cmake_modules/koreader_thirdparty_common.cmake
CMake <ins>2.8.5</ins> shipped with a built-in module.
Also quote `KO_DOWNLOAD_DIR`.
> [chore] CMake: deprecate custom processor count logic

- ffi/SDL2_0.lua
- ffi/util.lua
Fixes <https://github.com/koreader/koreader/issues/4826#issuecomment-475043234>.
A bit like the idea penned down [here](https://github.com/koreader/koreader/issues/3108#issuecomment-377548634).
> [fix] Add util.ffiLoadCandidates to try multiple SDL2 library names

- ffi/util.lua
Fixes minor typo with embarrassing consequences from https://github.com/koreader/koreader-base/pull/873
The file I committed accidentally wasn't 100 % the same as the one I tested. That would've blown up in a pretty embarrassing way.
> [fix] Return fail status for SDL

- Makefile
It's generally working as expected you're unlikely to have a file named `clean`. But if you were to create a file named `all` or `clean` you could have a pretty difficult time figuring out why nothing's happening anymore.
Cf. https://github.com/koreader/koreader/pull/4819 and https://github.com/koreader/koreader-base/issues/871.
> [chore] Makefile: declare all phonies

- Makefile
Deprecated by https://github.com/koreader/koreader-base/pull/567.
Originally added in https://github.com/koreader/koreader-base/pull/531 and https://github.com/koreader/koreader-base/pull/533.
> [chore] Remove luajit-clean target

- thirdparty/zlib/CMakeLists.txt
Obviously it's not LD_FLAGS. Fixes <https://github.com/koreader/koreader/issues/4833>.
> [fix, Android] thirdparty/zlib LDFLAGS typo

- cre.cpp
Helpful on 300dpi devices.
re: https://github.com/koreader/koreader/pull/4785#issuecomment-473704379
For ref., scaleBySize on a Forma:
```
echo $(( 12. * (1440/600. + 1440/600.) / 2. ))
28.799999999999997
echo $(( 30. * (1440/600. + 1440/600.) / 2. ))
72.
```
> Expand the font sized panel to allow full granularity from 12 to 72.

- blitbuffer.c
- ffi-cdecl/posix_decl.c
- ffi/blitbuffer.lua
- ffi/framebuffer_android.lua
- ffi/framebuffer_linux.lua
- ffi/posix_h.lua
- thirdparty/fbink/CMakeLists.txt
* Fix Android, because the framebuffer can also have a physical stride larger than the pixel width ;).
* Fix RGB32-to-RGB32 fast blitting w/ the Lua blitter, which I broke late in #878 because of a stupid typo.
* Allow disabling the C blitter, to make testing easier.
* Bump FBInk to v1.13.0 (unbreak legacy Kindle handling)
* Possibly unbreak some PB corner-cases (koreader/koreader#4851)
> Fix a couple bugs from #878

- cre.cpp
Includes https://github.com/koreader/crengine/pull/276:
- DrawBuf: allow drawing images inverted (to be used in night mode)
- ldomXPointer::getRect(): adds adjusted=false parameter
- CSS: fix parsing of "! important" with spaces
- CSS: fix non-deterministic combinators
- Delay some style computations until needed https://github.com/koreader/crengine/pull/278
> bump crengine: allow drawing images inverted, various fixes

- Makefile
- Makefile.defs
- blitbuffer.c
- blitbuffer.h
- ffi/blitbuffer.lua
- ffi/framebuffer.lua
- ffi/framebuffer_mxcfb.lua
- ffi/util.lua
Crappy puns aside:
* Faster SW inversion when done via invertRect (Lua/C, although the C version will be drastically faster on x64, because GCC vectorizes it properly).
* Speaking of, enforce aggressive optimizations when building the C bb, to ensure this will actually happen for real, and not just on my box ;p.
* Switch to HW PxP inversion on eInk devices where this is known to be stable (i.e., Kindles, Kobos aside from the Aura).
* When in NightMode, enforce a possibly less stupid waveform mode (fix the truly ancient https://github.com/koreader/koreader/issues/1375). On Kindle, where supported, this attempts to use the nightmode-optimized waveform modes. Needs testers on PW4/KOA2, because there's probably two of them.
> The Dark (K)Night

- ffi/framebuffer.lua
- ffi/koptcontext.lua
this PR needs more testing since it will result in multiple pixels offset for screens with more density.
> scale density independent pixel by 160 instead of 167

- Makefile.defs
Unversioned is a proven recipe for disaster. #thanksandroid
But perhaps more to the point, this isn't just a personal fancy. It crashes on load.
> [fix, Android] Versioned OpenSSL libs

- ffi/SDL2_0.lua
Only actively used on device ports (Ubuntu Touch, Sailfish), so it was silently broken.
Cf. https://github.com/koreader/koreader/issues/4960 and https://github.com/koreader/koreader-base/issues/899
```
---------------------------------------------
launching...
_  _____  ____                _
| |/ / _ \|  _ \ ___  __ _  __| | ___ _ __
| ' / | | | |_) / _ \/ _` |/ _` |/ _ \ '__|
| . \ |_| |  _ <  __/ (_| | (_| |  __/ |
|_|\_\___/|_| \_\___|\__,_|\__,_|\___|_|
It's a scroll... It's a codex... It's KOReader!
[*] Current time: 04/22/19-16:54:43
[*] Version: v2019.03-129-g5c95597f_2019-04-22
ffi.load: SDL2
ffi.load: SDL2
ffi.load: blitbuffer
ffi.load (assisted searchpath): ./libs/libblitbuffer.so
./luajit: ./ffi/SDL2_0.lua:80: undeclared or implicit tag 'SDL_DisplayMode'
stack traceback:
[C]: …
```
> [fix] ffi/SDL2: crash with `SDL_FULLSCREEN`

- spec/unit/zeromq_spec.lua
This was necessary on Travis four years ago, cf. https://github.com/koreader/koreader-base/commit/7025830053c47496db413802375236300eaf4e6e
> [CI, spec] Remove #notest from Zyre

- djvu.c
Partially addresses koreader/koreader#2943.
This just transparently translates the annotation tree into a Lua table. The frontend needs to be prepared to handle this more flexible structure. Fortunately, almost all DjVu files in practice adhere to the rigid `page -> line -> word` hierarchy, so this patch should transparently work without any noticeable difference in practice.
The final product here is my original implementation, which departs from the prevailing style of `djvu.c`, so I made an attempt at orthogonalizing style choices into the second commit.
Currently, `djvu.c` has a lot of magic numbers and repeated code, so my goal was to give these understandable names and make them reusable. Arguably, this should be it's own pull request, and be  carried out file-wide, but I figured …
> Pass arbitrary DjVu text annotations to frontend

- ffi/SDL2_0.lua
In the future either the whole SDL event or an abstraction can be passed on to front so that right click can be treated as instant hold.
> ffi/SDL2: restrict taps to SDL_BUTTON_LEFT

- blitbuffer.c
Clang defines `__GNUC__` (masquerading as GCC 4.2.1), too, so make sure the GCC version check excludes clang...
Shouldn't make any difference in practice, but, technically more correct ;).
> Make the GCC/Clang version check slightly more robust

- djvu.c
The existing implementation only worked in 8-bit mode. By using the `ddjvu_format_set_gamma()` function that comes with djvulibre it suddenly and attractively becomes Not Our Problem™.
I noticed this after doing a quick experiment with a custom power function `#ifdef __ANDROID_API__` like in https://stackoverflow.com/a/19488271/2470572
(For example, if Android define a custom power function, else `#define power(x, y) pow(x, y)`.)
I believe the proper way to go about it would probably be to ignore document-specific implementations and to do it in the blitbuffer, but this is quicker to implement.
As a side effect, this fixes https://github.com/koreader/koreader/issues/3493.
> [fix] DjVu gamma correction

- ffi/framebuffer_mxcfb.lua
By utilizing *both* of the nightmode waveform modes, as they ought to, instead of blindly picking one ;).
Thanks to ilovejedd on MR for the strace logs ;).
> Better nightmode handling on the KOA2 & PW4

- thirdparty/mupdf/CMakeLists.txt
- thirdparty/mupdf/upstream-698877.patch
Fixes <https://github.com/koreader/koreader/issues/5182>.
> [fix] MuPDF: backport fix for upstream 698877

- .circleci/config.yml
With any luck the odd MD5 problem will go away…
See <https://github.com/koreader/virdevenv/pull/42>.
> [CI] Switch to Clang 8

- ffi/MD5.lua
- spec/unit/md5_spec.lua
It's `expected, object`, not the other way around. Not the most important thing because it'll error out as intended either way, but the error messages are confusing otherwise.
> [chore, CI] Fix MD5 spec expected/result order

- thirdparty/harfbuzz/CMakeLists.txt
> This release does not include much functional changes, but includes major internal
code-base changes. We now require C++11. Support for gcc 4.8 and earlier has been
dropped.
https://github.com/harfbuzz/harfbuzz/releases/tag/2.5.0
> bump harfbuzz to 2.6.0

- cre.cpp
Includes https://github.com/koreader/crengine/pull/305 :
- View HTML: option to show text unicode codepoints
- Fix attribute parsing: decode &-encoded chars
- Text: allow wrap after more unicode spaces and hyphen
- Fix: no left hanging when hanging punctuation disabled
- lvtextfm.cpp: more comments, some formatting cleanup
- Optimize background image drawing
- CSS: fix background-image file path resolution
cre.cpp:
Adds setBackgroundImage() proxy function to crengine facility to set background textures (this is unrelated to the above background-image CSS fixes).
> bump crengine: background image and other fixes

- ffi/input_android.lua
https://www.mobileread.com/forums/showpost.php?p=3881047&postcount=11
ANR while pressing the back button. I don't know why but it seems that I'm not a heavy back key user. It should be reproducible since https://github.com/koreader/koreader/commit/81ea5f6a7ebc7f0dff1bf31b46b4f76e1054f91f. Sorry for the mess.
```logcat
W/KOReader(21500):  got error waiting for events: ffi/input_android.lua:108: missing declaration for symbol 'AKEYCODE_MEDIA_MUTE'
E/ActivityManager( 1490): ANR in org.koreader.launcher (org.koreader.launcher/.MainActivity)
E/ActivityManager( 1490): Reason: keyDispatchingTimedOut
```
> fix ANR by fixing a typo in the name

- input/input.c
> [chore] Fix implicit declaration of strcmp warning

- ffi-cdecl/mupdf_decl.c
- ffi/mupdf.lua
- ffi/mupdf_h.lua
This will be queried in front to dynamically set font size.
Cf. <https://github.com/koreader/koreader/issues/4368>.
> FFI: Add MuPDF fz_is_document_reflowable

- thirdparty/lua-Spore/CMakeLists.txt
Nothing of interest compared to the previous commit hash.
Just some stuff related to the move from GitHub to GitLab.
But! A tag is clearer. :-)
> thirdparty/lua-Spore: Bump to 0.3.3

- ffi/rtc.lua
This will allow for scheduling wakeups.
Prerequisite for <https://github.com/koreader/koreader/pull/5335>.
> [feat] Add FFI RTC interface

- thirdparty/mupdf/external_fonts.patch
Cf. <https://github.com/koreader/koreader/issues/5347#issuecomment-529480686>.
> [fix] MuPDF Android font dir patch update

- ffi-cdecl/SDL2_0_decl.c
- ffi/SDL2_0.lua
- ffi/SDL2_0_h.lua
- ffi/input_SDL2_0.lua
Cf. <https://github.com/koreader/koreader/issues/5374>.
> SDL: add rumble support

- ffi/kobolight.lua
- ffi/rtc.lua
Shouldn't have any visible effect, except for no longer leaking fds on
exec ;).
(c.f., man 3 open for the rationale behind this set of flags for ioctl handles).
> Unify open flags for ioctl-only fds

- thirdparty/kpvcrlib/CMakeLists.txt
Includes:
- (Upstream) Unified cache for chars and glyph's indexes https://github.com/koreader/crengine/pull/314
- (Upstream) Glyph caching: optional use of hash table instead of a linked list
- (Upstream) Adds docx and fb3 support
- Update hardcoded elements list and stylesheets
- DocX: build a HTML DOM instead of a FB2 DOM
- Text: allow wrap after '/' and '-' https://github.com/koreader/crengine/pull/316
- Text: with Harfbuzz, split measurement on text node change
- Clear fonts on load and re-rendering
> bump crengine: adds DOCX and FB3 support

- thirdparty/luajit/koreader-luajit-makefile-tweaks.patch
- thirdparty/luajit/koreader-luajit-verbose-build.patch
strip arguments are target-sensitive, so enforcing GNU flags everywhere
was a bad call.
> Fix LuaJIT patchset on Darwin

- Makefile.defs
luarocks 3.x supports one luarocks install with multiple lua versions.
archlinux already uses 3.x, debian and friends still use 2.x
this will change the directory structure in the release (not sure if that is important)
as documented in:
https://github.com/luarocks/luarocks/blob/master/CHANGELOG.md
> Breaking change: The support for deprecated unversioned paths (e.g. /usr/local/lib/luarocks/rocks/ and /etc/luarocks/config.lua) was removed, LuaRocks will now only create and use paths versioned to the specific Lua version in use (e.g. /usr/local/lib/luarocks/rocks-5.3/ and /etc/luarocks/config-5.3.lua).
> luarocks_dir compatibility with luarocks 3.x

- cre.cpp
Needed for proper auto hinting before switching the default kerning mode to Harfbuzz.
Includes https://github.com/koreader/crengine/pull/317.
Details in https://github.com/koreader/koreader/pull/5553
> bump crengine: use FreeType light hinting algorithm

- thirdparty/mupdf/external_fonts.patch
Forgotten in koreader/koreader#5463.
Doesn't revert the Roboto part of https://github.com/koreader/koreader-base/pull/971.
> [fix] Revert Android Noto patch

- ffi/SDL2_0.lua
Otherwise we'll get an `undefined symbol` error, but this function is too convenient to bother with the old-fashioned way of rumbling.
Fixes <https://github.com/koreader/koreader/issues/5570>.
> [fix] Don't crash on SDL < 2.9

- ffi-cdecl/SDL2_0_decl.c
- ffi/SDL2_0.lua
- ffi/SDL2_0_h.lua
I accidentally tested <https://github.com/koreader/koreader-base/pull/1008>
with SDL 2.0.9, so of course it seemed to be working…
> [fix] Prevent undefined symbol error on SDL < 2.0.9

- Makefile
- Makefile.defs
- Makefile.third
- ffi-cdecl/freetype2_decl.c
- ffi/freetype.lua
- ffi/freetype_h.lua
- ffi/pic.lua
- thirdparty/libunibreak/CMakeLists.txt
- xtext.cpp
- xtext.h
New Lua C module to be used by frontend TextWidget and TextBoxWidget, as an alternative text layout method, using Harfbuzz, FriBiDi and libunibreak.
This is needed to correctly shape Arabic scripts (cursive glyphs), propertly draw RTL text (Hebrew,
Arabic) and bidi text (arabic/hebrew filenames in english UI).
Early description of how I imagined it in https://github.com/koreader/koreader/issues/5359#issuecomment-533211988.
Screenshots and discussion in https://github.com/koreader/koreader/issues/5359.
See individual commit message for (not much) details.
@NiLuJe:
I used ffi-cdecl for the added Freetype ffi stuff, so it should be fine :)
About libunibreak, I don't know if it needs any of the `ifdef DARWIN` you added to others recently (I don't really get why you do it for some and not for …
> Adds libkoreader-xtext.so: enhanced text shaping helper

- Makefile
- ffi/SDL2_0.lua
- xtext.cpp
Linking with -static-libstdc++ might be needed on Kindle and Pocketbook to load (the simple fact of linking against the STL implies ABI compat checks). https://github.com/koreader/koreader/pull/5598#issuecomment-554764338
Also fix some clang-tidy warning about malloc'ing 0 bytes by handling the empty input case apart. https://github.com/koreader/koreader/pull/5598#issuecomment-554753824 - even if that's not really an issue:
```
$ man malloc
The malloc() function allocates size bytes and returns a pointer to the
allocated memory.  The memory is not initialized.  If size is  0,  then
malloc()  returns either NULL, or a unique pointer value that can later
be successfully passed to free().
```
Let's wait a bit for broken on Kindle reports to validate it's really needed - and in case we find …
> xtext: link against stdc++, fix some clang-tidy warning

- Makefile.third
I'm going bonkers when a patch file is updated and nothing happens because only CMakeLists.txt is a dependency. This reruns CMake when any file in `thirdparty/<dependency>` changes. In practice that mostly means `*.patch` in addition to CMakeLists.txt. There's a `cr3.css` in kpvclib and that's probably about it, but I'm trying to be forward-thinking here.
> [chore] thirdparty patch file dependencies

- thirdparty/mupdf/external_fonts.patch
This reverts commit b7dd4c16b06c22fc1d1b85544f9c767f8d4b2995.
Closes <https://github.com/koreader/koreader/issues/5617>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1013)
> Revert "[fix] MuPDF Android font dir patch update (#971)"

- thirdparty/fbink/CMakeLists.txt
- thirdparty/lodepng/CMakeLists.txt
* FBInk 1.20.3 (fix Cervantes CI)
* LodePNG
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1016)
> Minor third-party bumps

- xtext.cpp
When computing the accumulated width, we have a trick of keeping adding "tofu" widths, that we later remove when we add the correct width measured with a fallback font.
In a multi glyphs cluster, that notdef width was computed only from the first notdef glyph met, but it should include all the glyphs' widths, even if the first one is not notdef.
Fix the issue noticed in https://github.com/koreader/koreader/issues/5615#issuecomment-561734969.
Before, the glyph was off key because the computed width was too large (77):
<kbd>![too_large_wrong_width](https://user-images.githubusercontent.com/24273478/70189545-e00c7c00-16f3-11ea-8a96-85c4cd4fa7ff.png)</kbd>
After (correct width of 16):
<kbd>![fixed_width](https://user-images.githubusercontent.com/24273478/70189550-e1d63f80-16f3-11ea-9da0-7663fe …
> xtext: fix occasionally wrong measured width

- ffi-cdecl/posix_decl.c
- ffi/posix_h.lua
- ffi/util.lua
To have some tools to try to do better with our config files getting corrupted in case of device hang/crash.
More details in https://github.com/koreader/koreader/pull/3625#issuecomment-561838044.
Of interest:
http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/
https://stackoverflow.com/questions/37288453/calling-fsync2-after-close2
Also bump crengine:
-  Open (as text) small or empty files https://github.com/koreader/crengine/pull/322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1021)
> Add util.fsyncOpenedFile() and util.fsyncDirectory()

- thirdparty/fribidi/CMakeLists.txt
- xtext.cpp
- bump crengine: (Upstream) DocX: fix paragraphs with single hyperlink https://github.com/koreader/crengine/pull/323
- bump fribidi to 1.0.8 (for nested isolates fix, https://github.com/koreader/koreader/issues/5359#issuecomment-565001148)
- xtext.makeLine(): return `no_allowed_break_met=true` when that happens, so we know the line breaks inside a word. https://github.com/koreader/koreader/pull/5598#issuecomment-565836669
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1022)
> bump crengine & fribidi, tweak xtext.makeLine()

- cre.cpp
Includes https://github.com/koreader/crengine/pull/325 :
- lvtinydom.cpp: fix Use-after-free
- lvtextfm: fix/cleanup lastnonspace code bits
- lvtextfm: fix vertical-align: top & bottom
- renderBlockElementEnhanced: minor fixes related to floats
- renderBlockElementEnhanced: compute baseline of block
- Add support for display: inline-block/inline-table
- Better selection highlighting by using getSegmentRects()
- getHtml(): add flag to get text soft-hyphenated
cre.cpp: toggable text selection highlighting method, default to the new one using segments.
If we need to revert to former method, we can add in credocument.lua `true, false` to the 2 occurences of:
```diff
-local text_range = self._document:getTextFromPositions(pos.x, pos.y, pos.x, pos.y)
+local text_range = …
```
> bump crengine: support display: inline-block, better text selection

- cre.cpp
- thirdparty/kpvcrlib/CMakeLists.txt
- thirdparty/mupdf/external_fonts.patch
Includes https://github.com/koreader/crengine/pull/326 :
- ldomXRange/ldomMarkedRange: update enhanced drawing flag
- Hardcoded elements list: add <script>
- CSS: ensure selectors are applied in the order met
- elementFromPoint(): fix some floats not being visited
- Fix getPageDocumentRange() on bidi text
- Text: fix: allow wrap on space around images
- CSS/Text: adds "-cr-hint: strut-confined"
- Rename mispelled 'ident' and field 'margin' to 'indent"
- text-indent: some fixes, handle negative & hanging indent
- (Upstream) Minor cleanup and ifdef wraps
- lvtextfm: avoid possible segfault when hyphenating
- lvtextfm: avoid spurious spaces when hyphenating
- lvtextfm: dont adjust space after initial quotation mark/dash
- lvtextfm: ensure page-break:avoid on inline-block and images
- …
> bump crengine: various text and CSS fixes

- ffi-cdecl/include/einkfb.h
- ffi-cdecl/include/mxcfb-cervantes.h
- ffi-cdecl/include/mxcfb-kindle.h
- ffi-cdecl/include/mxcfb-kobo.h
- ffi/framebuffer_mxcfb.lua
Without doing something stupid this time around, like requesting monochromatic output when we really, really shouldn't ;).
c.f., #819 & #820
As well as koreader/koreader#4602
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1034)
> Re-enable HW dithering on Kindle

- ffi/framebuffer_mxcfb.lua
@NiLuJe 
KT4 doesnt support this HW dithering.
#1034 causes the display to be faded (i almost thought i damaged my screen by mistake)
if you think there is anything else that can be tried i am happy to help/test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1039)
> unbreak KT4 dithering (broken by #1034)

- ffi/framebuffer_mxcfb.lua
work
Followup to #1039
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1043)
> Make sure HW dithering won't be requested on Kindles where it doesn't

- Makefile.defs
Otherwise, we're picking it up in the final packages
We've been shipping extra bits of jpeg-turbo & zsync2 because of that,
which explains why the tarball's size has suddenly ballooned...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1044)
> Move CMake's staging directory outside OUTPUT_DIR

- thirdparty/harfbuzz/CMakeLists.txt
- thirdparty/harfbuzz/hb-disable-atomics.patch
Workaround for https://github.com/koreader/koreader/issues/5780
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1046)
> On Kindle legacy, disable atomics in HB

- xtext.cpp
Handle tabstops in makeLine() only (to get the segment that fits in the targeted width, with each tab width adjusted so the tab reaches the next tabstop - all that in string logical order).
(But not in shapeLine(), which will just report flags: it's the frontend code job to then handle tabstops just like it handles text justification and alignment.)
Buddy frontend PR: https://github.com/koreader/koreader/pull/5870
Will help closing https://github.com/koreader/koreader/issues/5837,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1049)
> xtext: flag tabs, optionally handle tabstops

- .circleci/config.yml
Without it the base CI is now failing to finish properly.
See https://github.com/koreader/virdevenv/pull/49 and https://github.com/koreader/koreader-base/pull/1049#issuecomment-587059804
Also includes a bump to the base image. See <https://github.com/koreader/virdevenv/pull/48>, closes <https://github.com/koreader/koreader-base/issues/956>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1050)
> [CI] New PocketBook Docker image with our own TC

- ffi/framebuffer_mxcfb.lua
It *really* doesn't work, even when I don't fuck it up myself ^^.
c.f., https://github.com/koreader/koreader/issues/5884
(re #1034)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1051)
> Definitively disable HW dithering on Kindle

- .github/workflows/build.yml
GitHub Actions provides readily available Mac OS (and Windows) builds, so we should prevent the habitual Mac OS breakage from here on out.
Differences from README:
* ccache for obvious reasons (faster builds)
* md5sha1sum caused some conflict with coreutils
<hr>
Hopefully @NiLuJe will be able to help resolve the gettext/glib issue because I have no idea what's going on there.
GH Actions docs: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1052)
> [CI] Mac OS build

- Makefile.third
- thirdparty/luasec/CMakeLists.txt
https://github.com/brunoos/luasec/compare/luasec-0.8.2...v0.9
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1005)
> thirdparty/luasec 0.9

- Makefile.defs
The Docke rimages don't ship w/ bc.
As discussed on gitter ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1053)
> Use awk instead of bc for version comparisons

- cre.cpp
Includes https://github.com/koreader/crengine/pull/329 :
- toStringV2(): fix when target node is a boxing node
- CSS font-family parsing: set usual default of sans-serif
- FB2 footnotes: fix spurious newline ("display: run-in")
- FB2 footnotes: disable hardcoded handling as in-page
cre.cpp: accepts classic FB2 footnotes in footnote popup detection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1055)
> bump crengine: normalized xpointers fix, FB2 footnotes tweaks

- thirdparty/fbink/CMakeLists.txt
- thirdparty/lodepng/CMakeLists.txt
* LodePNG 20200306
* FBInk 1.22.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1061)
> Update third-party deps

- ffi/MD5.lua
(Same upstream as luxl, which is why I fell into this rabbit hole).
My vague hope that this might fix the mysterious Clang bot issues have been crushed.
On the other hand, it doesn't seem to break anything, so, eh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1065)
> Rebase MD5 module against upstream

- thirdparty/cmake_modules/CMakeCross.cmake
See https://github.com/koreader/koreader/issues/4512#issuecomment-605433402
This is not intended to actually fix the build, just to make it so that an interested party won't have to start at 0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1071)
> Minor Win32 cross-compile fix

- thirdparty/harfbuzz/CMakeLists.txt
removed in 2.5.0
see https://github.com/harfbuzz/harfbuzz/commit/65392b734e38668b870b1ffcbfb4b42ec289ef58
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1075)
> harfbuzz: remove --with-ucdn

- ffi/MD5.lua
Regression since #1065
Probably because of implicit type conversions to/from Lua
and the fact that Lua numbers are double internally?
Or something.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1077)
> Unbreak MD5 on ARM

- xtext.cpp
Includes https://github.com/koreader/crengine/pull/341 :
- Text: fix occasional BiDi bad word splitting
- Font: fix HB fallback measurement/drawing mismatches
- Font: do not add letter spacing on diacritics
- Text: tunable use of letter spacing for justification
- Text: dont adjust space after initial quotation mark/dash (rework)
xtext.cpp: pick crengine fix with HB fallback measurement/drawing mismatches
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1094)
> bump crengine: tunable use of letter spacing for justification

- Makefile
do not build dropbear on unsupported platforms.
Also sorting.
Related to https://github.com/koreader/koreader/pull/6099
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1095)
> strip objects on native debian builds

- thirdparty/freetype2/CMakeLists.txt
Apparently, Android sometimes likes to try to link against an inexistant
brotli otherwise...
Fix https://github.com/koreader/koreader/issues/6178 (thanks to @zwim)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1102)
> Explicitly disable WOFF2 support in FT

- ffi-cdecl/rtc_cdecl.c
- ffi/rtc.lua
- ffi/rtc_h.lua
Do it like busybox & Nickel
The other approach would be a WKALM_RD + WKALM_SET.
I'm not *quite* sure what the previous behavior was actually doing
(No idea what an epoch set to -1 actually does in practice?)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1106)
> Tweak RTC alarm disable

- thirdparty/harfbuzz/CMakeLists.txt
> As a part of our migration to meson, this release will be the last one
to provide cmake port files but autotools still is our main build system.
There is a possibility that the next version or the after be released
using meson.
<https://github.com/harfbuzz/harfbuzz/releases/tag/2.6.7>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1109)
> thirdparty/harfbuzz 2.6.7

- Makefile
- Makefile.defs
- Makefile.third
- thirdparty/lua-Spore/CMakeLists.txt
- thirdparty/lua-htmlparser/CMakeLists.txt
My setup does not allow me to check how does it integrate with the complete build (Raspberry Pi). So, would be thankful if someone could verify if it works and then is used by [the patched newsdownloader](https://github.com/koreader/koreader/pull/6228).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1110)
> Added htmlparser Luarock for newsdownloader

- cre.cpp
Includes https://github.com/koreader/crengine/pull/345 :
- GIF decoding: avoid crash on some images
- Top progress bar: avoid re-computing when not needed
- Top progress bar: allow external filling of marks
- CSS/Text: properly inherit and handle text-align-last
- getRenderedWidths(): fix handling of text-indent
- Reorder some flags to make the sets clearer
- CSS: support more white-space named values
- Text: fix standalone BR not making an empty line (rework)
- CSS: support for pseudo elements ::before & ::after
- CSS: content: open-quote support via TextLangMan
- CSS/Text selection: adds a few "-cr-hint:" tweaks
cre.cpp: adds setHeaderProgressMarks()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> bump crengine: support for pseudo elements ::before/after

- Makefile
- Makefile.defs
- Makefile.third
- thirdparty/lua-rapidjson/CMakeLists.txt
- thirdparty/lua-rapidjson/lua-rapidjson-android-link-to-lua.patch
- thirdparty/lua-rapidjson/lua-rapidjson-never-native.patch
Decodes **2-10x** faster than current json lib (with minimal memory footprint), supports pretty print and has nice functions to load/dump tables from/to JSON files.
Mainly to use when speed could be an issue, like in https://github.com/koreader/koreader/pull/6177
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1113)
> add lua-rapidjson

- thirdparty/djvulibre/CMakeLists.txt
- thirdparty/djvulibre/android.patch
Nothing of much importance besides perhaps a few ARM64 fixes, and [8e79901a927d7b20b629f5240e64f617d67f3dff](https://gitlab.com/koreader/djvulibre/-/commit/8e79901a927d7b20b629f5240e64f617d67f3dff) deprecates part of our Android patch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1119)
> thirdparty/djvulibre Bump to latest master

- thirdparty/evernote-sdk-lua/CMakeLists.txt
Bump evernote-sdk-version to https://github.com/koreader/evernote-sdk-lua/commit/b6d8bed1fecb95b062f719dcad3cd720048c623a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1121)
> Bump evernote-lua-sdk(fix 印象笔记)

- thirdparty/harfbuzz/CMakeLists.txt
> Meson build fixes, cmake port removal is postponed but please prepare for
it and give us feedback.
> Autotools is still our main build system however please consider
experimenting with meson also for packaging the library.
<https://github.com/harfbuzz/harfbuzz/releases/tag/2.6.8>
So, given that we don't use CMake, /shrug. ^_^
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1122)
> thirdparty/harfbuzz 2.6.8

- ffi/framebuffer.lua
It was broken (only the FB was rotated not the touch) and prevents using a W>H device
this keeps `isAlwaysPortrait()` for devices that have a bad starting orientation (can be set in the emulator with EMULATE_READER_FORCE_PORTRAIT)
to test try `kodev run -h=600 -w=800`. Fixes: koreader/koreader#5910 may need koreader/koreader#6309 to be complete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1128)
> remove W>H startup rotation

- ffi/framebuffer_android.lua
As suggested by @Frenzie in https://github.com/koreader/android-luajit-launcher/pull/210#issuecomment-570514091
This unblocks a few things, namely:
- Native rotation on android
- Split view on android
- Platforms that require a resizable window: Chrome OS and Anbox
Also removed the (old) comments. It is not better to use NDK calls to get height and width, since our own sdk methods take care of oddities between APIs and fullscreen status.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1130)
> android: resize buffer

- ffi/framebuffer_android.lua
On tv and chromeOS, where surface rotation is not available, we still use blitbuffer rotation.
Requires https://github.com/koreader/android-luajit-launcher/pull/235
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1134)
> use native rotation if available

- Makefile.defs
Aka emulator without debug symbols
https://github.com/koreader/koreader/issues/6331
Also bumps crengine (fix mac build)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1138)
> Mac target

- ffi/util.lua
(There was an early potentially bogus return).
Also, that do block for scoping was funky as hell.
We're already in a dedicated module, using local functions for the
private ones and a namespace ffor the public ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1140)
> Resync orderedPairs w/ upstream

- button-listen.c
When the home button is used to wake the device from suspend the evdev
events have surprising time stamps. There is a pair of press & release
events, but the press has a timestamp from when the device went into
suspend and the release has a timestamp from after. This means that the
wake keypress will launch koreader as button-listen thinks the key was
held down for the whole time the device was suspended!
Instead, just record CLOCK_BOOTTIME timestamps for the events and use
those instead of the event timestamps. CLOCK_BOOTTIME is monotonic but
includes time spend in suspend.
Also keep track of whether button-listen saw a key press before each key
release. Probably not strictly required but seemed sensible to add.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> remarkable: fix button-listen when resuming from suspend

- .github/workflows/build.yml
(12.0 as a test, will switch to 11.3.1 if that doesn't work out, as that is the version from before the segfaulting started)
See https://github.com/marketplace/actions/setup-xcode-version and https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#xcode for more information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1147)
> [CI] Setup custom Xcode version for macOS build

- Makefile
- Makefile.defs
- osx_loader.c
- thirdparty/sdl2/CMakeLists.txt
- thirdparty/sdl2/cocoa.patch
also called: fun with match-o things!
To be used instead of the shell script. Renders part of the `cocoa.patch` obsolete and makes the program debuggable with instruments and other tools.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1151)
> add a minimal launcher for osx

- thirdparty/libunibreak/CMakeLists.txt
- thirdparty/libunibreak/add_lb_get_char_class.patch
Includes:
- (Upstream) LVBase64NodeStream: fix possible segfault https://github.com/koreader/crengine/pull/366
- (Upstream) Fix getting encoding from HTML META tags
- FB2: also look for cover in `<src-title-info>`
- FB2: fix cover image colors
- FB2: don't draw cover in scroll mode
- TextLang: better linebreaks at em-dash (EN/ES/FR) https://github.com/koreader/crengine/pull/365
- TextLang: increase _lb_props static array size https://github.com/koreader/crengine/pull/368
libunibreak: add patch to export internal function `get_char_lb_class_lang()` as `lb_get_char_class()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1160)
> bump crengine: better linebreaks at em-dash, fb2 fixes

- thirdparty/harfbuzz/CMakeLists.txt
<https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.1>
ot-funcs now handles variable empty glyphs better when hvar/vvar isn't present.
Reverted a GDEF processing regression.
A couple of fixes to handle OOM better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1161)
> thirdparty/harfbuzz 2.7.1

- Makefile
- Makefile.defs
- Makefile.third
- ffi/framebuffer_linux.lua
- input/libue.h
- thirdparty/kobo-usbms/CMakeLists.txt
And sprinkle a bit of `CLOEXEC` magic in `framebuffer_linux` while we're at it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1165)
> Build KoboUSBMS on Kobo

- cre.cpp
- ffi/util.lua
Includes https://github.com/koreader/crengine/pull/370 : 
- Revert "FB2: don't draw cover in scroll mode"
- (Upstream) FB2: fix coverpage drawing in scroll mode
- FB2 footnotes: only merge run-in when next is erm_final
- fb2.css: use OTF tabular-nums for footnote numbers
- Text: ignore ascii and unicode control chars
- Fix HR positionning when floats involved
- writeNodeEx(): minor tweaks
- OnTagClose(): add self_closing_tag parameter
- HTML format detection: accept HTML5 doctype
- HTML parser: rework Lib.ru specific handling
- HTML parser: new more conforming implementation
- HTML parser: ensure foster parenting inside tables
Also add getTimestamp() and getDuration() to ffi/util.lua.
To be used for timing loading and rendering times:
```diff
--- a/frontend/apps/reader/readerui.lua
+++ …
```
> bump crengine: New HTML parser, libRu and FB2 tweaks

- thirdparty/lua-ljsqlite3/init.lua
`sqlite3_close()` may occasionally return SQLITE_BUSY, which is not expected by frontend code and can cause some crash.
`sqlite3_close_v2()` always returns SQLITE_OK and has SQLite deal itself with properly closing it later.
Ref: https://github.com/koreader/koreader/issues/5563#issuecomment-682980942
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1174)
> lua-ljsqlite3: use sqlite3_close_v2()

- input/input-kobo.h
- thirdparty/kobo-usbms/CMakeLists.txt
* Fix erratic status bar refresh on Mk. 7
* Attempt to abort early when connected to a wall charger instead of a USB host
In the spirit of that last change, split our own fake events in two, like on Cervantes, in order to prevent showing the USBMS popup when plugging into a wall charger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1183)
> Update to KoboUSBMS v0.9.8

- thirdparty/giflib/CMakeLists.txt
Because everything is terrible, I guess?
Fix https://github.com/koreader/koreader/issues/6668
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1186)
> Forcibly disable docs when building giflib

- cre.cpp
- thirdparty/kpvcrlib/CMakeLists.txt
Includes:
- Update German hyphenation patterns https://github.com/koreader/crengine/pull/375
- (Upstream) Adds ODT (ODF) format support https://github.com/koreader/crengine/pull/377
- TextLang, hyphenation: add Basque, Croatian, Esperanto, Estonian, Georgian, Latvian, Lithuanian, Macedonian, Occitan, Welsh; update Bulgarian, Irish, Portuguese, Slovak, Dutch, Norwegian, Spanish; update hyphen min for Czech, English, Greek; fix Romanian and Ukrainian pattern file names https://github.com/koreader/crengine/pull/378
- HyphMan: adds HyphMethod::getLeft/RightHyphenMin()
- epub.css: update HR default style https://github.com/koreader/crengine/pull/379
- fb2.css: keep <date> in main text left-aligned
- getRenderedWidths(): inline-block and table fixes
- CSS: avoid style hash mismatch when …
> bump crengine: ODT support, added/updated hyphenation

- input/input.c
as per https://github.com/Eeems/oxide/issues/69, we have a couple changes to koreader for remarkable build that will make koreader play nicer with launchers. this diff turns off the exclusive input grab because we don't need that for remarkable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1193)
> reMarkable: don't exclusive grab input for remarkable build

- ffi/blitbuffer.lua
* Detecting stuff we can't handle, and fall back to Lua
* It's also possible to toggle CBB on the go without koreader restarts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1195)
> blitbuffer refactor: Make CBB modular

- ffi/framebuffer.lua
- ffi/framebuffer_SDL2_0.lua
- ffi/framebuffer_android.lua
Get rid of the triple/quad inversion mess.
Tested only on SDL, but the mechanism is now same on Android:
Inversion is done during writes to the shadow BB that is configured
to invert by noHWInvert from the base fb class, same way it works for
linuxfb eink that lacks inversion mode.
During the final update we then copy the shadow buffer 1:1 to the
backing texture.
Should fix
https://github.com/koreader/koreader/issues/6708
https://github.com/koreader/koreader/issues/6703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1200)
> SDL + Android: Clean up inverse blit modes

- blitbuffer.c
- blitbuffer.h
- ffi/SDL2_0.lua
- ffi/blitbuffer.lua
- ffi/framebuffer_SDL2_0.lua
- ffi/framebuffer_linux.lua
- ffi/mupdf.lua
- ffi/pic.lua
- spec/unit/common_spec.lua
More of an RFC/WIP for now, to agree on stuff etc.
TODO: This turned out to be fairly invasive in a lot of places, so need to do some daily use testing to see if things still hold together.
* phys_w/pitch renamed to pixel_stride/stride, phys_h removed
* Get rid of getPhys*() uses. stride is hardwired to rotation,
so returning swapped coordinates from there doesn't work
* make proper distinctions in uses between stride/pixel_stride where such
wasn't the case
* add some more getenv() options to SDL to emulate arbitrary bb formats
and b&w device
* make BB.new() infer optional stride/pixel_stride parameters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1201)
> blitbuffer: Some more refactoring + SDL FB debug tools     

- cre.cpp
Includes:
- (Upstream) various unimpacting changes to keep in sync https://github.com/koreader/crengine/pull/384
- (Upstream) Fix issues with legacy text rendering
- (Upstream) FB3/DocX/ODT: get lang and description metadata
- (Upstream) remove some global settings, make them per-doc
- TextLang, hyphenation: add Armenian, Friulian, Piedmontese, Romansh, Zulu and Brazilian Portuguese. https://github.com/koreader/crengine/pull/383
cre.cpp: remove update of removed global `gDOMVersionRequested`, which should now be done with:
`setIntProperty("crengine.render.requested_dom_version", version)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1204)
> bump crengine: sync with upstream, new hyphenation languages

- .luacheckrc
- cre.cpp
- ffi/freetype.lua
Includes https://github.com/koreader/crengine/pull/385 :
- TextLang: German: loosen quotation marks handling
- Fonts: add LVFontManager::getFontFileNameAndFaceIndex()
- fb2.css: avoid break before footnote links
- FlowState: fix possible wrong baseline with nested inline-table
- Tables: fix possible layout issues with rowspan
- Table cells: minor refactoring of baseline handling
- getRenderedWidths(): better estimate table width
- lvstyles: allow for more than 64 styles
cre.cpp: add getFontFaceFilenameAndFaceIndex().
ffi/freetype.lua: add optional 'faceindex" parameter to FT.newFace() so we can request a font other than the first one from font collections (.ttc).
Needed to show font names in the menu in their own font, see https://github.com/koreader/koreader/issues/6739#issuecomment-70313 …
> bump crengine: more than 64 styles, table layout fixes

- ffi/blitbuffer.lua
The rest of them were already doing that ;).
I don't *rightly* recall *why* we're killing debug hooks in there in the first place (performance?), but, oh, well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1210)
> Drop unused variable

- ffi/blitbuffer.lua
It's currently horribly broken on CircleCI under Busted, for... reasons.
And, surprise surprise, it was originally implemented as... a CI hack.
(in 897906d91a3cbba0eb2aa27583a6510c99ac720d).
Plus, I don't think we actually ever set debug hooks in the first place
anyway?
I fully expect the testsuite to implode on some random new stuff instead,
but, oh, well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1213)
> Get rid of debug hooks shenanigans

- ffi-cdecl/freetype2_decl.c
- ffi/freetype_h.lua
- thirdparty/freetype2/CMakeLists.txt
c.f., https://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/docs/CHANGES
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1214)
> Bump FreeType to 2.10.3

- ffi/input_android.lua
this is intended when killed by the system or by the program using `finish()` from kotlin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1224)
> android input: do not error when the activity is destroyed

- cre.cpp
Includes:
- Update German hyphenation patterns https://github.com/koreader/crengine/pull/387
- (Upstream) Rename lChar16/lString16 to lChar32/lString32 https://github.com/koreader/crengine/pull/390
- (Upstream) Ignore provided document w/h if negative
- (Upstream) Parse and skip '@charset' in CSS
- (Upstream) Fix possible segfault in ~ldomDocument()
- lvDefFatalErrorHandler(): add comment on how to get a real crash
- writeNodeEx: dont show ="" on empty attributes
- List item markers: draw even when they overflow
- Strut confining: avoid it too when only no break spaces
- Text: ensure LTEXT_FIT_GLYPHS around images/inline boxes
- Font: fix synthetized italic metrics
- Font: fix synthetized bold italic drawing
- In-page footnotes: always push vertical margin before
cre.cpp: rename lString16 …
> bump crengine: upstream sync, some rendering fixes

- ffi/framebuffer_android.lua
https://github.com/koreader/android-luajit-launcher/pull/250 introduces new QualcommOnyxEPDController. This adds proper refresh modes to support it. It's still needs some fine-tuning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1221)
> Add support for QualcommOnyxEPDController

- thirdparty/libk2pdfopt/CMakeLists.txt
- thirdparty/minizip/CMakeLists.txt
Add compile flags to allow implicit function declarations in libk2pdfopt and minizip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1198)
> Fix build in macOS XCode 12

- .github/workflows/build.yml
```
Error: Unable to process command '::set-env name=MD_APPLE_SDK_ROOT::/Applications/Xcode_11.3.1.app' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Cf. https://github.com/maxim-lobanov/setup-xcode/issues/12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1232)
> [fix] GitHub Actions set-env error

- thirdparty/libjpeg-turbo/CMakeLists.txt
Probably nothing relevant to us.
<https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.6>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1231)
> thirdparty/libjpeg-turbo 2.0.6

- input/atomicio.h
- input/libue.h
* Properly ignore udev events, by not even listening for them
* Slightly more resilient reading logic, based on current udev & busybox
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1234)
> Resync libue w/ KoboUSBMS

- thirdparty/fbink/CMakeLists.txt
- thirdparty/kobo-usbms/CMakeLists.txt
* FBInk v1.23.0 (basically what we were running before, but on a tagged release ;p)
* KoboUSBMS v1.0.0 (I expect that the version number alone will trigger new and interesting failures!).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1236)
> Minor third-party updates

- ffi/blitbuffer.lua
This PR solves the issue https://github.com/koreader/koreader-base/pull/1233#issuecomment-732227157 with extremely poor performance on `writeBMP` on Tolino. 
See also koreader/koreader#6736 on slow screenshot performance and the solution at the time #1205.
In my understanding the history of #1205 was the following:
I created an issue koreader/koreader#6736 on slow screenshot performance.
On Oct. 4 @ezdiy proposed a solution for the slow screenshot #1205, which worked at that time.
On Oct. 5 @NiLuJe improved blitbuffer.lua for "less crappy performance" #1206. This was a massive change in blitbuffer.lua which counteracted the improvement of the loopunroll. But nobody noticed that, because nobody used the folded loops on a slow device.
The whole genesis of this revert can be found in #1233. …
> Revert "blitbuffer: Always enable JIT workaround (#1205)"

- ffi/blitbuffer.lua
Momentary brainfart lead to me using a char* instead of an unsigned
char*
Which doesn't change much in the grand scheme of things, but, oh, well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1238)
> BB: Ensure consistent types are being used in writePNG

- ffi/framebuffer.lua
Even if said override happens to match the native DPI, because the scaleBySize heuristic is weird and results would differ.
c.f., https://github.com/koreader/koreader/pull/6977#issuecomment-743276911
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1258)
> framebuffer: Make sure scaleBySize honors a DPI override

- Makefile.third
- thirdparty/zstd/CMakeLists.txt
- thirdparty/zstd/zstd-rpath.patch
We don't really need it, but it was broken by the switch to env from `MOREFLAGS` ;).
Also fix CRe's dependencies on macOS to avoid it depending on brew's zstd.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1260)
> Fix ZSTD rpath

- ffi/framebuffer_linux.lua
Fix https://github.com/koreader/koreader/issues/7017
Supercedes https://github.com/koreader/koreader/issues/7022
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1264)
> PB: Preserve the SW invert flag after a HW rotation

- ffi/blitbuffer.lua
This is mildly related to part of the recent Android discussions on Gitter ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1263)
> Fiddle with CBB toggling to try to avoid weird Android corner-cases

- cre.cpp
- thirdparty/kpvcrlib/CMakeLists.txt
We expect RGBA, CRe uses BGRX (well, alpha is actually sane, but inverted. Which, AFAIK, is usually a weird legacy PNG/Gif quirk or something, but, oh, well).
As discussed in https://github.com/koreader/koreader/pull/7021
Depends on https://github.com/koreader/crengine/pull/402
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1265)
> Handle CRe's weird-ass pixel-format once and for all

- blitbuffer.c
- blitbuffer.h
- ffi/blitbuffer.lua
- ffi/framebuffer_android.lua
As a side-effect of #1200, software nightmode was no-longer handled in the C blitter, it instead went through to the Lua blitter.
This exacerbated the latent issues with LuaJIT and mcode_alloc on that platform (remember, the C blitter was initially implemented *specifically* to avoid stressing LuaJIT with the blitter code on Android because of that fact).
So, without going back to the admittedly messy way this was handled before, tweak a few things to make Android a special snowflake again, so that nightmode on Android no longer goes through the Lua blitter.
In fact, port `paintRoundedRect` to the C blitter to make doubly sure of that (and get rid of an ugly hack that was necessary to handle inversion quirks in setPixel otherwise ;p).
---
This change is [<img …
> Android: Never ever touch the Lua blitter

- thirdparty/harfbuzz/CMakeLists.txt
Not relevant to us.
<https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.4>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1271)
> thirdparty/harfbuzz 2.7.4

- .github/workflows/build.yml
Something along these lines should solve the issue that ccache is becoming so outdated that it's barely even helpful anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1276)
> [CI, macOS] Use files most relevant to build to invalidate cache

- ffi-cdecl/SDL2_0_decl.c
- ffi/SDL2_0.lua
- ffi/SDL2_0_h.lua
Turn on text input for SDL, which means it decodes key events
into text events according to the keyboard layout and delivers
it as Unicode.
This can then be wrapped in an SDL event and passed upwards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1277)
> SDL: Handle text input

- ffi/blitbuffer.lua
Completely random whitespace change while looking into https://www.mobileread.com/forums/showpost.php?p=4077126&postcount=334 (which, btw, makes no sense, unless there's some heinous viewport/rotation shenanigan going on. My one theory was an underflow, but 2020.12 wasn't using unsigned data types yet, and checkBounds should guard against negative values anyway; and 2020.12 was effectively using the Lua blitter for nightmode, so that magically working now makes no sense, again).
(Well, not so random, `getPhysicalRect` just below it is formatted the same way).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1280)
> Minor cosmetic tweak

- ffi/framebuffer.lua
- ffi/framebuffer_mxcfb.lua
Also, export `MXCFB_WAIT_FOR_UPDATE_COMPLETE` to allow calling it manually on the previous marker from front.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1283)
> Kobo: Switch to DU for "fast"

- thirdparty/tar/CMakeLists.txt
- thirdparty/tar/tar-1.33-remove-o_path-usage.patch
Re https://github.com/koreader/koreader/issues/7140
("Regression" thanks to a gnulib update in tar 1.33).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1288)
> Unbreak tar on older kernels

- ffi/framebuffer_android.lua
Regardless of whether we actually could potentially coerce those buffers to RGB32, the sanity check makes sense ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1293)
> Android: Fix nighmode on devices w/ RGB565 windows w/ the C blitter

- cre.cpp
Includes:
- EPUB ncx TOC: allow items with an empty title https://github.com/koreader/crengine/pull/409
- resizeImage(): restore original scaling options code
- CSS: parse and store min/max-width/height
- Add getStyledImageSize() ensuring min/max-width/height
- renderBlockElementEnhanced(): ensure min/max-width/height
- 2-pages mode: add option twoVisiblePagesAsOnePageNumber https://github.com/koreader/crengine/pull/410
- TOC, PageMap: save the visible pages number they were build for
- 2-pages mode: tweak header drawing
- Header: add option to display time as 12-hours clock
- 2-pages mode: decrease min middle margin from 1.2 to 0.8em
- Add LVDocView::getDocumentRenderingHash()
- (Upstream) Text: don't remove trailing space on last word if pre https://github.com/koreader/crengine/pull/410 …
> bump crengine: support min/max-width/height, 2-pages tweaks

- thirdparty/curl/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1301)
> Update to cURL 7.75.0

- thirdparty/gettext/CMakeLists.txt
Worked locally, so, who knows...
> Fix gettext install on old(?) CMake

- blitbuffer.c
- ffi/blitbuffer.lua
In the vast majority if cases, in blitbuffer, when we're passed a `Color?` object, it's a direct *reference* (e.g., `Color8 &`) to the buffer *itself*. As such, if we update it, we're *writing* to the buffer.
This is obviously a terrible idea (except in the cases where we actually *want* to write to the buffer ^^), and shit starts getting really scary when you remember that we most often do that via the `getColor?` methods, which do *pixel-format* conversions. Ouch.
I'm mildly amazed this has never blown up anywhere in fun and interesting ways before, but, this was at least exposed by @poire-z's testcase in https://github.com/koreader/koreader/issues/5916#issuecomment-779486154
ImageViewer starts by showing the image full-screen, then a tap scales it in order to show the buttons. …
> BlitBuffer: Make sure we *never* update a color reference

- ffi/framebuffer_mxcfb.lua
We've effectively switched to DU for "fast" everywhere, and we've
limited our usage of "fast" to plain highlights.
Relying on FORCE_MONOCHROME for these use-cases is unnecessary, and has
known side-effects on various platforms, ranging from minor refresh
glitches to more severe and pernicious issues.
(That leaves PB, which I can't test, and where DU and especially A2
are already special snowflakes to begin with, even on NXP SoCs).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1312)
> MXCFB: Match the Kobo behavior for "fast" on every device where I know it'll behave sanely.

- ffi/framebuffer_mxcfb.lua
They tend to be older/lower-res, and it looks notably worse without it there.
(Followup to #1312)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1313)
> MXCFB: Re-enable FORCE_MONOCHROME on EPDCv1 devices

- Makefile
- input/input-remarkable.h
When the reMarkable2 is suspended and the user presses the Power button, the device wakes up but does NOT send the power button "pressed" or "released" events to `/dev/input`.
This PR is an alternate solution to https://github.com/koreader/koreader/pull/7345
If someone has a cleaner way to watch DBus events on the reMarkable2, let me know.
This code simply launches the command
```
dbus-monitor --system member='PrepareForSleep'
```
and then watches for a line that starts with
```
[three spaces]boolean false
```
That feels a bit klunky and brittle, but it's working on my machine, so [*shrug*]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1318)
> Add reMarkable2 generateFakeEvents

- thirdparty/sqlite/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1328)
> Update SQLite to 3.35.0

- ffi/framebuffer.lua
- ffi/framebuffer_mxcfb.lua
Whether a device capcheck enables it by default or not.
(Followup to #1329).
Also, actually *log* failures for this ioctl in debug mode, which should help diagnosing affected devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1334)
> Kobo: Allow toggling the WAIT_FOR_UPDATE_COMPLETE hack

- ffi/framebuffer_mxcfb.lua
This makes adding support for new devices less unwieldy and error-prone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1339)
> MXCFB: Move cap checks to front

- thirdparty/fbink/CMakeLists.txt
- thirdparty/kobo-usbms/CMakeLists.txt
- thirdparty/openssl/CMakeLists.txt
There was a rather nasty bug in the OT codepath that could possibly cause KoboUSBMS to do Bad Things in some circumstances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1338)
> FBInk updates

- Makefile.defs
- cre.cpp
- thirdparty/kpvcrlib/CMakeLists.txt
Includes (among others):
- LVImg: Tweak JPEG decoding some more https://github.com/koreader/crengine/pull/427
- toStringV2(): fix (again) when target node is a boxing node https://github.com/koreader/crengine/pull/428
- LVFontCache::find(): give more weight to first fonts in list
- Page splitting: more accurate rendering progress
- getRenderedWidths(): fix nowrap around image/inlineBoxes
- Tables rendering: tweak column widths algorithm
- CSS: parse/handle "currentcolor", default for border-color
- CSS: add units 'ch' (just like 'ex')
- SVG images: proper alpha blending
- MathML: add parsing and rendering support files https://github.com/koreader/crengine/pull/429
- MathML: plug MathML code into crengine core
- MathML: <epub:switch/case/default>: accept MathML
- (Upstream) Make …
> bump crengine: add support for MathML

- ffi/SDL2_0.lua
- ffi/input_android.lua
Hopefully can't happen on Android, but very common on SDL because we don't do anything with mouse pointer events.
Only noticed tonight because my gamepad happens to be spamming gyro events tonight (which we don't do anything with, too) ;p.
Basically, waitForEvent is designed to poll *once* and return *one* event. But the SDL & Android version need to generate evdev input events from Abdroid/SDL input events, which mean they nerd to handle 1 => many scenarios. This is handled via a FIFO queue, which means the polling is stuck in a forever loop.
That means we were never going back to Lua to recompute timeouts, which was bad: that meant scheduled task would only actually run on the next input event instead of the scheduled time.
PB is a special snowflake, and, while it's also a forever loop, …
> SDL/Android: Actually honor polling timeouts

- ffi/input_android.lua
This is a very draft for demonstrating the functionality of `alooper.fifo`. This connects the `luajit-launcher` with the frontend.
Of course the `require("logger").err("xxxxxxx` will disappear. 
The important lines are from 183 down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1326)
> Process ALooper-FIFO

- ffi/SDL2_0.lua
- ffi/input_android.lua
- ffi/input_pocketbook.lua
- input/input.c
The legacy design of consuming events one by one made the SDL & Android backends somewhat awkward, because they needed to generate many evdev events from possibly a single native event.
Moreover, even on plain Linux, you're mostly guaranteed that events will be readable in a batch, with boundaries at each `SYN_REPORT`.
Actually draining the queue ASAP pushes the possibility of a queue overflow (and as such, a `SYN_DROPPED`, which we don't actually handle) even further away from the realm of possibility, which is good, because, again, we're not handling this case anyway ;).
Except for PB being a special snowflake with its custom loop and timeout handling that I'm not touching, this makes the Android/SDL implementations code flow much closer to the C implementation's.
Speaking of, since I …
> Input: Handle events in batches

- ffi-cdecl/posix_decl.c
- ffi/posix_h.lua
- input/input.c
- input/timerfd-callbacks.h
Okay, turns out, reading the full batch of events at once (or at least in as few `read` as possible) isn't too gnarly, and allows us to do nifty things with Lua table allocations, by telling Lua exactly how many elements we're going to insert.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1346)
> Input: Batched reads & batched table allocations

- ffi/input_pocketbook.lua
- ffi/jpeg.lua
- ffi/kobolight.lua
- ffi/util.lua
- thirdparty/kpvcrlib/CMakeLists.txt
* CRe: Disable CLOEXEC on Kindle Legacy
* Use CLOEXEC in every one of our (ffi.C) open() calls.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1349)
> CLOEXEC related tweaks

- cre.cpp
- djvu.c
- ffi-cdecl/posix_decl.c
- ffi/posix_h.lua
- input/input.c
- input/timerfd-callbacks.h
- xtext.cpp
Mainly pre-alloc when we can know/estimate the amount of elements, unify usage of *raw* setters for metatable-less tables, and stricter typing (e.g., don't cast integers to double by limiting usage of `pushnumber` to actual floats).
Also added some comments for the twistiest bits of logic (djvu, lookin' at ya').
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1350)
> Completely random table alloc tweaks in Lua/C modules

- ffi/input_android.lua
They're now marked NONBLOCK, so we can safely do read loops until we hit EAGAIN ;).
Requires https://github.com/koreader/android-luajit-launcher/pull/299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1356)
> Android: Drain the CMD & USER pipes in a single waitForEvent iteration

- ffi/input_android.lua
pollAll is a wrapper around pollOnce useful when multiple fds are registered with callbacks, to ensure they *all* fire. Since we don't register callbacks at all, do away with this wrapper.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1358)
> Android: Swith to pollOnce

- ffi/posix_h.lua
The constants are hilariously not portable. So, fix 'em on macOS & most common BSD flavors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1360)
> POSIX: Fix portability issues with clock_gettime

- thirdparty/libjpeg-turbo/CMakeLists.txt
Relevant to our interests: fancier NEON support. Would be even fancier if built w/ Clang, because GCC's NEON intrinsics support is generally subpar compared to Clang, and that's a problem here, so the build-system disables 'em.
(Namely, the inverse DCT which we could have used in our overwhelmingly-decompression-centered workloads)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1361)
> Update to libjpeg-turbo 2.1.0

- input/input.c
- input/timerfd-callbacks.h
The loop condition is based on num_fds, so the current implementation closes only half of all the open fds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1364)
> closeInputDevices should not decrease num_fds within the loop

- ffi/framebuffer.lua
- ffi/framebuffer_linux.lua
returns a Geom in front...
(For https://github.com/koreader/koreader/pull/7664)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1369)
> FrameBuffer: Rename getSize to allow overloading a getSize that actually

- cre.cpp
Apply this together with https://github.com/koreader/crengine/pull/439.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1374)
> bump crengine: support for user hyphenation dictionary

- ffi/mupdf.lua
MuPDF may slightly update/round annotation boxes coordinates, and we need frontend to have them consistent for it to be able to delete/update annotations.
See https://github.com/koreader/koreader/issues/7928#issuecomment-882056494
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1388)
> mupdf.lua: update frontend pboxes with MuPDF adjusted ones

- ffi-cdecl/linux_input_decl.c
- ffi/linux_input_h.lua
Supposedly useful to grok the Elipsa's pen battery status, but I haven't actually seen one in the wild yet ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1393)
> Add KEY_BATTERY constant

- ffi/blitbuffer.lua
- ffi/jpeg.lua
Allows to save a BMP in 8 bit grayscale.
See https://github.com/koreader/koreader/issues/8046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1396)
> BMP in 8bit grayscale

- Makefile.defs
It's probably more relevant/easier that way in 2021?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1402)
> win32: change CHOST to x86_64-w64-mingw32

- cre.cpp
Includes among others:
- https://github.com/koreader/crengine/pull/450
- Various CHM handling fixes, and others
- https://github.com/koreader/crengine/pull/451
- https://github.com/koreader/crengine/pull/452)
- https://github.com/koreader/crengine/pull/453
- HTML documents: rebuild TOC from headings after load
- Font: use metrics for underline offset and thickness
- epub.css, html5.css: tweak ruby styling
- CSS: fix EPUB's head>style content encoding
- CSS: add support for 'box-sizing: content-box/border-box'
- CSS: support for styling the `<html>` element
cre.cpp: comment out some unused functions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1406)
> bump crengine: support for 'box-sizing', and various other fixes

- ffi/mupdf.lua
The `getSize` methods of a page -- much like the various BBox methods -- all return an internal representation of rectangles, with floating point precision, for a fixed render DPI of 72.
Trying to round that to integer this early in the pipeline risks cascading large rounding errors after scaling back to the actual screen size & scale factor.
Noticed with a random CBZ where this returned weirdly tiny rectangles (still don't know why), but, most importantly, ones that featured meaningful decimals.
This lead to computing a scale factor that was slightly off, which meant we actually scaled it to a slightly unexpected size (here, bigger), while the images were actually perfectly screen sized.
So, extra scaling pass: bad!
Extra-scaling pass that breaks page mode + fit-to because it no longer …
> MµPDF: Don't accumulate rounding errors when computing page dimensions

- ffi/mupdf.lua
Includes https://github.com/koreader/crengine/pull/454 : 
- XML parsing: strip leading \n in PRE and TEXTAREA
- Text: allow wrap on any space in "white-space: pre"
- initTableRendMethods(): avoid expensive processing
- Tables: fix handling of whitespace between nodes
- ldomDocument: store screen size
- CSS: more robust skipping of invalid content
- CSS: parse/skip at-rules, support `@media`, `@supports`
- CSS: handle media condition with `@import` and <link/>
- CSS: fix parsing of "font-family:inherit!important"
- LDOMNameIdMap::deserialize(): fix when >1024 items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1408)
> bump crengine: CSS: parse/skip at-rules

- thirdparty/sdcv/CMakeLists.txt
Needed to finally fix koreader/koreader#5168.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1431)
> sdcv: update to include multiple results fix

- thirdparty/libjpeg-turbo/CMakeLists.txt
* Update to libjpeg-turbo [2.1.2](https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.1.2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1433)
> Update to libjpeg-turbo 2.1.2

- thirdparty/kpvcrlib/CMakeLists.txt
This allows to open files from rclone mounts in crengine
Closes koreader/koreader#7236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1430)
> crengine: build with long file support

- thirdparty/harfbuzz/CMakeLists.txt
* 3.1.0 is broken on ARM
* 3.1.1 requires GCC >= 5
Our Android TCs haven't moved to Clang, so we're stuck on GCC 4.9 there,
and 3.1.1 also apparently ICEs on Ubuntu's GCC 8.4.0, which one of the
CI bots uses...
Let's see how things shakes out in the next minor release, and if it
becomes too annoying, we'll possibly consider making the version
being built different depending on the target...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1434)
> Rollback to HarfBuzz 3.0.0

- cre.cpp
Includes https://github.com/koreader/crengine/pull/461 : 
- setStatusFontSize/Face(): avoid spurious re-rendering
- Hanging punctuation: include it in native highlighting
- Hanging punctuation: tweak hanging ratios again
cre.cpp: don't Render() in setViewDimen(), we'll do that in a more controlled fashion in frontend (https://github.com/koreader/koreader/pull/8501#issuecomment-986965082).
These tweaks and fixes will allow to contain any crengine re-renderings in `ReaderRolling:onUpdatePos()` where https://github.com/koreader/koreader/pull/8501 can plug Device:setIgnoreInput() to avoid ANR on Android.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1438)
> bump crengine: avoid re-renderings, hanging punctuation tweaks

- ffi/blitbuffer.lua
- ffi/mupdf.lua
As discussed at the tail end of https://github.com/koreader/koreader/pull/3905 ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1440)
> A few quick blitbuffer fixes

- .ci/test_script.sh
- .github/workflows/build.yml
- .github/workflows/ci.yml
- Makefile
There is a job for linters, a matrix for the emulator builds, and a matrix for cross compile
Fix macos build based on koreader/koreader#8525
Android Builds have not be implemented yet. (I still have to figure out what the toolchain requirements are vs what GHA provides)
~~This still has some work to be done to deduplicate the dependency install scripts with front and virdevenv~~
Requires: koreader/virdevenv#71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1442)
> [CI] Github Action for lint, build and tests

- ffi/mupdf.lua
Unlock new strikeout highlight style.
Reduce underline/strikeout line thickness, to look similar to KOReader highlight style.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1450)
> mupdf: strikeout highlight style, line thickness

- ffi/framebuffer_pocketbook.lua
Needs also the following PR: https://github.com/koreader/koreader/pull/8727
I've been emailing about color support for the pocketbooks directly with Pocketbook. The awesome folks of pocketbook replied with the implementation of rendering with the native inkview library. I've tested this with my Pocketbook 741 and the results are very promising.
This is their answer:
> Support for PB741 (InkPad Color)
> https://github.com/koreader/koreader/issues/7406 
> 
> There are two types of color screens used by PocketBook: Kaleido and Kaleido plus. These two types have slightly different color filter patterns. Thus we need to use different algorithms to display colors. All this functionality is already implemented in inkview library which is already used by KoReader. The easiest way to have colors …
> PocketBook: Handle rendering of interface and books directly with inkview

- ffi-cdecl/include/einkfb.h
- ffi-cdecl/include/frontlight-kindle.h
- ffi-cdecl/include/ion-kobo.h
- ffi-cdecl/include/mtk-kindle.h
- ffi-cdecl/include/mxcfb-kindle.h
- ffi-cdecl/include/mxcfb-kobo.h
- ffi-cdecl/include/mxcfb-pocketbook.h
- ffi-cdecl/mxcfb_kindle_decl.c
- ffi/framebuffer.lua
- ffi/framebuffer_linux.lua
- ffi/framebuffer_mxcfb.lua
- ffi/mxcfb_kindle_h.lua
- thirdparty/fbink/CMakeLists.txt
- thirdparty/lua-ljsqlite3/init.lua
As found on the PW5 ;).
Thankfully, the driver's API is designed to match the mxcfb API, so this was hilariously trivial compared to the sunxi insanity ;).
----
* On mxcfb-like devices with hardware inversion support, toggle nightmode by switching the grayscale fb vinfo flag when we're running at 8bpp. All the mxcfb-like drivers check this to toggle PxP/MDP inversion, but the MTK driver also does it in other places to make better decisions in nightmode.
* Implement the refresh machinery for the MTK driver found on Kindles. Its API is thankfully based on the mxcfb API, so there's nothing drastic happening ;).
* Resync eink headers w/ FBInk.
* Update FBInk.
* Random lj-sqlite3 luacheck cleanup ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
> Implement MTK support on Kindle

- .ci/emulator_install.sh
Includes:
- Fix sizing of float/inline-block image containers https://github.com/koreader/crengine/pull/467
- Fix body background drawing and other clipping issues
- Drawing: don't use `setHidePartialGlyphs()`
- CSS: ignore the `<body>` parent of `<DocFragment>`
- CSS colors: parse `rgb()/rgba()` and 4/8 digits hex values
- LVString: update/fix char props and `lStr_findWordBounds()` https://github.com/koreader/crengine/pull/468
- `UserHyphDict::getHyphenation()`: trim word with `lStr_findWordBounds()` https://github.com/koreader/crengine/pull/469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1462)
> bump crengine: rendering, CSS and hyphenation tweaks

- ffi/framebuffer_linux.lua
devices
I had momentarily blocked out the painful memory that most NTX boards do
wonderfully weird things in their ioctl handler...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1468)
> Allow forgoing the whole "nightmode via grayscale fb flag" thing on some

- thirdparty/kobo-usbms/CMakeLists.txt
* Allows connecting to ports negotiated as CDP (which *should* be most PD-aware and not misbehaving and/or nerfed USB 3.1 (or is that 3.2 now?)/4.0 (i.e., Thunderbolt 3/4) ports).
USB is fun.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1473)
> Update to KoboUSBMS 1.3.1

- ffi-cdecl/SDL2_0_decl.c
- ffi/SDL2_0.lua
- ffi/SDL2_0_h.lua
Toggles between fullscreen and window mode.
When returning back to window mode previous size and position are restored.
Quite useful for Linux/ChromeOS 2in1 / convertible devices.
Might be useful on desktop too (maybe we can map it to F11 on linux?, it is not needed for mac)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1492)
> SDL: toggle fullscreen mode

- thirdparty/sdcv/CMakeLists.txt
https://github.com/Dushistov/sdcv/compare/v0.5.3...v0.5.4
Except of course we were on a slightly more recent commit, cf. <https://github.com/koreader/koreader-base/pull/1431>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1495)
> thirdparty/sdcv v0.5.4

- ffi/framebuffer_mxcfb.lua
koreader/koreader#9245 NiLuJe/FBInk#69
The simplest way to trigger this is `fbink -K direction=LEFT,steps=12 -s width=11`
The MTK Driver will crash if given a area smaller than the number of steps. If direction is L/R and w is smaller or if it is U/D and h is smaller Being as one generally will only want animations on a larger area, and I am too lazy to test for direction, disable animations when w or h is less than steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1494)
> [PW5 MTK] Fix swipe animations with a tiny refresh area

- cre.cpp
Includes https://github.com/koreader/crengine/pull/486 : 
- Text: fix possible overflow with "`white-space: pre`"
- Fonts: `getFontFileNameAndFaceIndex()`: return family type
- Fonts: account for `_bias` in Font hash
- epub.css, fb2.css: remove hardcoded monospace font names
- Fonts: allow scaling monospace fonts
- Fonts: allow adjusting fallback font sizes to x-height
- HTML parser: trust xml encoding before html charset
cre.cpp: make `setAsPreferredFontWithBias()` a global function (as it is not a per-document setting)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1503)
> bump crengine: monospace and fallback fonts tweaks

- thirdparty/sdcv/CMakeLists.txt
- thirdparty/sdcv/sdcv-locale-hack.patch
- thirdparty/sdcv/sdcv-pr90.patch
- thirdparty/sdcv/sdcv-pr91.patch
I'm not sure if it was actually broken for me before, but at least this one works on both Kobo & Android ;).
@pazos's hunch was nearly perfectly spot-on (my working theory is that it's the `sizeof` comparisons that were broken, quite likely because off64_t vs. ulong, and not the fstat call itself).
Split our existing patch in two, and submitted the sanest part of it upstream, because apparently I'd forgotten about it, and it happened to have been reported upstream.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1516)
> Bump sdcv to 0.5.4 + a couple of PRs to fix it

- ffi/util.lua
Usually involves sorting numbers with strings, but could theoretically be more esoteric ;).
Still assumes that matching types supports comparisons, which may not always be true for custom types without an overloaded operator...
Should be fine for our current needs, though.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1517)
> ffiUtil: Make orderedPairs behave with mixed key types

- cre.cpp
Includes https://github.com/koreader/crengine/pull/490 : 
- CSS parsing: accept (and ignore) namesspaces
- `isImage()`: more checks for `<object>` as it can have inner content
- `getFontFileNameAndFaceIndex()`: returns if font has math support
- `getFontFileNameAndFaceIndex()`: returns if font has emojis
- CSS/Fonts: add support for `font-family` to font name mapping
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1526)
> bump crengine: support for font-family to font name mapping

- Makefile.defs
This fixes koreader not being built on platforms where bash isnt at /bin/bash
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1529)
> Makefile.defs: Use path agnostic bash location for $SHELL

- ffi-cdecl/harfbuzz_cdecl.c
- thirdparty/harfbuzz/CMakeLists.txt
- thirdparty/sdl2/CMakeLists.txt
- thirdparty/sdl2/cocoa.patch
* HB 5.3.0 (https://github.com/harfbuzz/harfbuzz/releases/tag/5.3.0)
* SDL 2.24.1 (re: https://github.com/koreader/koreader/issues/8797#issuecomment-1272601513)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1534)
> Third-party bumps

- .luacheckrc
- ffi/util.lua
- thirdparty/luajit/CMakeLists.txt
- thirdparty/luajit/koreader-luajit-enable-table_pack.patch
It's unfortunately behind the Lua 5.2 extensions ifdef in a standard build (possibly because it's so common that it's usually implemented in Lua and monkey-patched over the table metatable?).
But it's trivial and doesn't actually poses an API issue, and it's helpful for a number of our use-cases.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1535)
> Build LuaJIT w/ table.pack support

- ffi/SDL2_0.lua
One being a failure to actually round properly, which lead to potentially passing a float to a C function that takes an int; and the other being that SDL's input timeout only has ms precision, which is much coarser than us, which meant that anything > 0 and < 1 ms was asking for an immediate return for as long as that fractional ms ticked. Instead, we now round up to 1ms in these cases.
Goes hand in hand w/ https://github.com/koreader/koreader/commit/d034e1a71955b45ce02587fdcd0a58b9f491de50
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1541)
> SDL: Fix a bunch of input timeout edge-cases

- cre.cpp
- xtext.cpp
Allow getting any text soft-hyphenated according to crengine hyphenation dicts. May be used by frontend's textboxwidget to hyphenate text before wrapping and rendering it with xtext. See https://github.com/koreader/koreader/pull/9630#issuecomment-1278158193.
Bump crengine for https://github.com/koreader/crengine/pull/492 :
- TextLang: add `TextLangCfg->softHyphenateText(lang, text)`
If soft-hyphens were present in the input text, it was considered (by libunibreak) as a candidate for breaking a line, but no real hyphen would be shown when the line is rendered.
So, be sure we properly draw a real hyphen when shaping a line ending with a soft-hyphen.
(Refactor the ellipsis substitution code so we can reuse it with hyphen substitution.)
See …
> cre & xtext: more soft hypheness

- ffi/input_pocketbook.lua
- input/input-pocketbook.h
This makes PB logs one billion percent less mysterious, and actually allows cleaning up some nastiness in front.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1545)
> PB Input: Handle EV_KEY & EV_MSC translations here, instead of in front

- input/input-cervantes.h
- input/input-kobo.h
- input/input-pocketbook.h
- input/input-remarkable.h
- input/input-sony-prstux.h
- input/input.c
- input/libue.h
Mainly, pass human-readable errors to Lua, not just a raw errno.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1549)
> Input: Minor logging tweaks

- ffi-cdecl/posix_decl.c
- ffi/posix_h.lua
This time I actually checked that there wasn't a native Lua wrapper ;p.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1552)
> ffi/posix: Add getuid

- thirdparty/mupdf/CMakeLists.txt
- thirdparty/mupdf/mupdf_cbz_chapter_support.patch
I wrote a patch to add support for sections, based on folders in the archive, in the comic book formats (cbz,cbt) in mupdf.
I have not tried to get this upstream because upstream does not seem interested in outside patches, judging by what is written on the mupdf website. But I still would like to see this functionality in koreader.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1553)
> mupdf: add patch to support sections in comicbooks

- thirdparty/mupdf/mupdf_cbz_chapter_support.patch
In a flat comicbook archive, where there are no chapters, `cbz_load_outline` would return an empty `struct fz_outline*`. This causes the ffi wrapper to crash, because it tries to call `strlen` on a string that is `NULL`.
This is fixed by returning NULL instead of the empty `struct fz_outline *`.
I'm sorry I should have tested this, but obviously did not :(
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1554)
> mupdf: fix crash with flat comicbook archives

- thirdparty/lunasvg/CMakeLists.txt
- thirdparty/lunasvg/extended.patch
- thirdparty/lunasvg/xtended/ximageelement.cpp
- thirdparty/lunasvg/xtended/xlunasvg.h
- thirdparty/lunasvg/xtended/xtextelement.cpp
- thirdparty/lunasvg/xtended/xtspanelement.cpp
- thirdparty/lunasvg/xtended/xtspanelement.h
Bump LunaSVG to its current master:
- Upstream fixes: https://github.com/sammycage/lunasvg/compare/637121f8...585d61eef
- Adaptations mostly because of renamings and small refactoring at upstream.
- ExternalContext target sizes: account for the change introduced by [0562a5dcc](https://github.com/sammycage/lunasvg/commit/0562a5dcc8c25e59c060ee73d6d4d538f172d642) ""Support SVG files with invalid size"
- 3rdparty/plutovg/plutovg-blend.c: fix edge pixels bleeding in outside area with `<image>` and `preserveAspectRatio="meet"` (the default).
Should allow closing https://github.com/koreader/koreader/issues/9766.
More screenshots at upstream https://github.com/sammycage/lunasvg/issues/97#issuecomment-1309956305
To be bumped in koreader after v2022.11.
- - -
This change is [<img …
> bump LunaSVG: various upstream fixes, fix edge pixels bleeding

- cre.cpp
Includes https://github.com/koreader/crengine/pull/496:
- getTextLangCfg(lang_tag): add 'force' parameter (and use it in cre.cpp's softHyphenateText()).
Fixes small issue noticed at https://github.com/koreader/koreader/pull/9630#issuecomment-1314320371
- Styles: check when inheritable CSS set on boxing elements
cre.cpp: docToWindowRect(): ignore rect over page top
See https://github.com/koreader/koreader/pull/9850#issuecomment-1336137373
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1557)
> bump crengine: fix styles under boxing elements

- ffi/mupdf.lua
The function fz_lookup_metadata returns the length the metadata item actually has, not how much was written into the supplied buffer which is what the caller expects. This matters if the item is longer than the supplied fixed size buffer because ffi.string will read out of bounds and include the garbage it reads in the resulting lua string.
This is fixed by checking the return value and calling fz_lookup_metadata again with an appropriately sized buffer if the metadata item is longer than the initial buffer.
Another option would be to call the function first with a zero sized buffer, but than every call would pay the cost of two calls instead of only those calls that actually need a larger buffer.
koreader/koreader#9855
- - -
This change is [<img …
> mupdf: Fix corrupt pdf metadata info if longer than 255 bytes

- Makefile
- thirdparty/dropbear/CMakeLists.txt
- thirdparty/dropbear/dropbear-2018.76-scp-command-hack-pocketbook.patch
Pocketbooks have a internal dropbear SSH server that is not used (I'm not sure why but most likely they use it for development). I was able to boot this SSH server so I was wondering if I it would be possible to use KoReaders dropbear server implementation with the no password improvements.
After making my own build of them it seems that this is actually working fine with some restrictions. You can only login with the `reader` user and don't have root access. But it will make debugging Pocketbooks a lot easier!
The command to login into pocketbooks is:
```
ssh -T reader@10.0.0.251 -p 2222
```
For some reason there is no tty access even when `lsof /dev/pts/*` gives results do the `-T` flag is needed else the following error will be thrown:
```
debug2: channel_input_status_confirm: type 100 …
```
> Enable SSH server for pocketbook devices

- ffi/input.lua
As discussed in https://github.com/koreader/koreader/issues/9427 removing the old global switch for pocketbook input selection.
Depends on: https://github.com/koreader/koreader/pull/9871
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1560)
> Remove old pocketbook input selection

- ffi/input_pocketbook.lua
This enabled the GSensor for modern PocketBook devices using the still unreleased firmware 6.7 and later.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1566)
> Enable gsensor EVT_ORIENTATION events on modern Pocketbook devices with InkView version 6.7

- thirdparty/kobo-usbms/CMakeLists.txt
Fixes battery discovery on the Clara 2E (and make the whole sysfs node discovery less of a clusterfuck in the process ;)).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1571)
> Update to KoboUSBMS 1.3.7

- ffi/lru.lua
Both in terms of slots & bytes (~~used by https://github.com/koreader/koreader/pull/10023~~)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1573)
> LRU: Add a couple of APIs to get/set the cache size

- xtext.cpp
Fix issue introduced by 08efc6da (#1543): when not truncating with ellipsis, an added and uninitialized trailing char was given to Harfbuzz, which could cause the last real char in Arabic text to not get its correct final form.
See https://github.com/koreader/koreader/issues/10030#issuecomment-1383172778.
Should allow closing https://github.com/koreader/koreader/issues/10030.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1574)
> xtext: fix inconsistent rendering of arabic text

- ffi/koptcontext.lua
- ffi/util.lua
We're unlikely to change OS at runtime ;o).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1583)
> ffiUtil: Don't branch on ffi.os at runtime

- thirdparty/cmake_modules/koreader_thirdparty_git.cmake
- thirdparty/mupdf/CMakeLists.txt
- thirdparty/openssl/CMakeLists.txt
- shallower clones
- sparse checkouts for the initial repos
- support not fetching/setting up any submodules
- disable all OpenSSL submodules (not used)
- only fetch/checkout the MuPDF submodules that are needed
Stats after building 3 versions (emulator debug & release versions, kindlepw2 release version):
|                                                  | master |     PR |
| -------------------------                        | ------:|-------:|
| `thirdparty/*/build/git_checkout`                |   2.6G |   296M |
| `thirdparty/*/build/x86_64-pc-linux-gnu`         |   3.2G |   1.5G |
| `thirdparty/*/build/x86_64-pc-linux-gnu-debug`   |   3.6G |   2.0G |
| `thirdparty/*/build/arm-kindlepw2-linux-gnueabi` |   3.5G |   1.8G |
| `thirdparty/*/build`                             |  13.0G | …
> reduce disk usage of thirdparty build directories

- thirdparty/mupdf/CMakeLists.txt
- thirdparty/mupdf/fix_link_cmd.patch
Patch the makefile link command so the build process does not try to link with system libraries (e.g. `-lpeg`), even when building the generator helpers (like `cnamedump.exe`). Since mupdf's build system is only in charge of building a static library, we can just drop the `$(LIBS)` part of the link command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1586)
> MuPDF: fix build

- thirdparty/kobo-usbms/CMakeLists.txt
We now use a very slightly larger font size for the bottom status line (Re: https://github.com/koreader/koreader/issues/10097).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1587)
> Bump KoboUSBMS to 1.3.8

- cre.cpp
Includes https://github.com/koreader/crengine/pull/513:
- Update German hyphenation patterns
- CSS stylesheets cache: also clear it after initial load
- getSurroundingAddedHeight(): use interline_scale_factor
- LVDocView::getNodeByPoint(): tweak again for text selection
- LVDocView::getPageBookmark(): behave as getBookmark()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1590)
> bump crengine: minor fixes, add getPageXPointer()

- .circleci/config.yml
See https://github.com/koreader/virdevenv/pull/80
~~For https://github.com/koreader/koreader-base/issues/1486~~
Android is for next week.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1487)
> [CI] Update all but Android to new CMake 3.16 image

- ffi/util.lua
Follow-up to #1593
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1594)
> Fix brew not found on non-Mac platforms

- .circleci/config.yml
Reverts koreader/koreader-base#1597
The CI only checks for Android ARM anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1598)
> Revert "[CI] Switch Android Docker image from 18.04 to 22.04"

- Makefile.defs
- thirdparty/czmq/CMakeLists.txt
https://github.com/koreader/koreader/issues/8797#issuecomment-1499554576
Mac OS X 13.3 (and 13.3.1) seems to have dropped ifr_netmask exposition in the kernel. These changes attempt to automatically omit ifr_netmask patch for czmq for Darwin 22.4+ kernels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1596)
> Fix build on Mac OS X 13.3+ (missing ifr_netmask)

- ffi/SDL2_0.lua
Partially inspired by the Android implementation.
After I added it, I suddenly realized we could've had fake multitouch on desktop for years. There's a right button on the mouse, after all. A possible alternative would be to simply fake right mouse button as being two fingers at once, as opposed to having to truly press left and right at the same time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1599)
> SDL: add multitouch support

- ffi/SDL2_0.lua
Re. <https://github.com/koreader/koreader-base/pull/1599#discussion_r1167966679>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1600)
> SDL: avoid silly ABS_MT_TRACKING_ID for mouse button presses

- ffi/util.lua
Turns out we can't rely on the len operator in all cases, as it may get confused depending on where the `nil`s are, so always use the `n` field instead, as that *is* reliable.
Re: #1535
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1603)
> Deal with table.pack corner-cases properly

- ffi/SDL2_0.lua
Presumably fairly harmless except in wasted processing because for motion the two are identical or close to it regardless.
Noticed in https://github.com/koreader/koreader/issues/10417#issue-1704432636
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1607)
> [fix] Uncomment accidentally commented out SDL_TOUCH_MOUSEID check

- ffi/koptcontext.lua
Don't set context field from a string that could be garbage collected…
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1613)
> ffi/koptcontext: fix language handling

- ffi/mupdf.lua
This is a rough approximation to be used by the caching mechanism. I assume one byte per character and a small constant size for coordinates. I don't know how much overhead the table and individual structures require.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1612)
> Return size of PDF page document

- Makefile
Probably never needed but it was part of LuaJIT instructions in mid 2020. c.f: https://github.com/koreader/koreader-base/pull/1151#discussion_r461683073
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1533)
> osx_loader: remove compiler flags no longer relevant since LuaJIT 2.1

- ffi-cdecl/mxcfb_kindle_decl.c
- ffi/mxcfb_kindle_h.lua
My PW5 is experiencing black -> white ghosting esp. on resume from suspend. It does not happen every time, and i suspect it is temperature dependent (it hapens most when switching climate indoors <-> outdoors) and my kindle's thermometer does not work so well :)
I adapted @poire-z footer patch from [here](https://github.com/koreader/koreader/issues/10231#issuecomment-1477138340) and indeed the temp is ~10°F above ambient, it is annoying to `ffi.cdef` the ioctl constants everywhere i need them, so let us just make the public here. also add the `mxcfb_panel_info` while i am at it.
I plan on integrating this into my SS plugin to auto adjust the temp a few degrees to compensate, and being as we pass `TEMP_USE_AMBIENT` everywhere it will go back to that with no long term effect. This approach …
> mxcfb_kindle: add temp ioctl constants

- ffi-cdecl/freetype2_decl.c
- ffi/freetype.lua
- ffi/freetype_h.lua
- ffi/harfbuzz.lua
- xtext.cpp
There's still one small leak remaining due to using `FT_Done_Library` instead of `FT_Done_FreeType` to handle the Freetype's library lifecycle: its memory object is not freed on exit.
This is also the precursor to some [memory optimizations](https://github.com/koreader/koreader/commit/59f982c65bb9e11dde50fe8b729e7433aa037d8c).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1618)
> fix most freetype/harfbuzz related memory leaks

- ffi-cdecl/SDL2_0_decl.c
- ffi/SDL2_0.lua
- ffi/SDL2_0_h.lua
- ffi/framebuffer_SDL2_0.lua
Fix https://github.com/koreader/koreader/issues/10502, regression since #1610
Well, only the size is a regression (plus, it was sortof an ffi/framebuffer API break, even if SDL is quirky in that fb.h / fb.w might not match fb.bb's dimensions because HiDPI shenanigans).
The position one is a bit of a mystery, we get an initial move event no matter what, for some reason, and without the explicit set, it's at the top left despite passing the right stuff to CreateWindow o_O.
Also dropped a duplicate openGameController call, as we handle it via an SDL_CONTROLLERDEVICEADDED event already.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1627)
> SDL: Unbreak window state save & restore

- Makefile.defs
Ensure our possibly updated `PATH` variable is taken into account for all `$(shell …)` invocations.
~Additionally, add a couple of sanity checks after some of those invocations).~ Nope, still sloppy…
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1630)
> make: fix possible PATH issues

- cre.cpp
Depends on https://github.com/koreader/crengine/pull/520.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1617)
> cre: fix and enable teardown

- Makefile
It's no longer in use, and gets deleted at runtime if empty, but its presence here means it makes it into the list of mandatory files in the `package.index` file used by OTAs, which means the *first* OTA after a fresh install will fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1643)
> Build: Don't create the legacy history dir

- cre.cpp
Includes https://github.com/koreader/crengine/pull/524:
- SVG: support embedded base64 images when no doc
- epub.css: hide <nav hidden="">
- Tables: fix possible specified width overflow
- Tables: fix caption and table width interactions
- CSS/Tables: add support for "caption-side: top/bottom"
- gatherNodeMatchingRulesets(): avoid messing document cache
- gatherStylesheetsMatchingRulesets(): add with_m_stylesheet param
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1644)
> bump crengine: CSS caption-side, SVG, CSS and table fixes

- thirdparty/mupdf/CMakeLists.txt
- thirdparty/mupdf/read_large_zip.patch
Allow reading files over 2GB (assuming you've got the RAM ;p).
(Fix https://github.com/koreader/koreader/issues/10829)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1649)
> MuPDF: Backport upstream Zip64 fixes

- thirdparty/libwebp/CMakeLists.txt
Fix CVE-2023-4863.
Our usual third-partiers must be partying, for not noticing all web browsers updated for that :)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1656)
> Update to libwebp 1.3.2

- .github/workflows/build.yml
Since the macOS build already come with one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1639)
> ci: don't install SDL2 from brew

- .github/workflows/build.yml
Avoid concurrent workflow runs on the same ref.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1659)
> ci: do not waste resources on Github Actions

- ffi/SDL2_0.lua
The tests explicitly check for `true` or `false` (`nil` is invalid).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1658)
> ffi/sdl: fix `batterystat` tests when running on battery

- ffi/zstd.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1666)
> ffi/zstd: fix possible leak on error

- ffi/rtc.lua
We've had a couple reports over the years of broken alarm reads on old NTX boards (in... every sense of the word; this only seems to affect old i.MX RTCs, true, but more specifically really old devices, with possibly dying batteries).
e.g., https://github.com/koreader/koreader/issues/7994 & https://github.com/koreader/koreader/issues/10996
While there *is* an ioctl that is supposed to help with this sort of stuff by reporting on the state of RTC's battery voltage, in my own testing on much less broken RTCs, it was extremely unreliable (especially when it matters most, i.e., right after a wakeup), so, that's kind of a no-go.
Thankfully, when this occurs, the returned alarm is *extremely* obviously bogus: `1`, as in, Epoch.
TL;DR: Just ignore such return values and assume the alarm did …
> RTC: Ignore obviously bogus alarm reads on dodgy RTCs

- thirdparty/kpvcrlib/CMakeLists.txt
Depends on https://github.com/koreader/crengine/pull/542.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1675)
> crengine: don't compile unused code

- .github/workflows/build.yml
- fix cache handling: the wrong path was configured, so the cache was not saved. Also tweak use so the cache is still saved on cancellation / failure.
- build checkout phase: update action so a full clone with filtering can be used (so tags are fetched and koreader's version is correct).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1686)
> improve macOS CI build

- input/input.c
- input/timerfd-callbacks.h
By making sure in openInputDevice that the top member of the array also happens to be the highest fd number.
----
Initial draft below:
Mention that nfds computations assume the inputfds array is sorted in increasing fd numbers
This doesn't necessarily hold true in practice (e.g., if one were to first open an fd during a directory walk with a few dir/file fds open...)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1685)
> Input: Ensure clearTimer won't compute a lower nfds value than one of our opened fds

- Makefile.defs
- `RCP`: use `cp -R` (supported on all systems we care about)
- `ISED`: get rid of it (none of the makefiles use it)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1687)
> minor Makefile cleanups

- Makefile.defs
- thirdparty/kpvcrlib/CMakeLists.txt
Use `-include […]/crsetup.h` instead of `--include […]/crsetup.h`, as the later would result in 0% cacheable calls when building with ccache (cf. [ccache issue #1324](https://github.com/ccache/ccache/issues/1324))…
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1691)
> fix crengine compilation cache

- .github/workflows/build.yml
The removal of the `distutils` module in Python 3.12 break Glib's build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1692)
> ci: fix macOS build

- ffi-cdecl/crypto_decl.c
- ffi/crypto.lua
- ffi/crypto_h.lua
PBKDF2 with HMAC-SHA1 is used by WPA to derive the PSK. We currently use wpa_passphrase to calculate this PSK. Since we already bundle OpenSSL, and OpenSSL has a function for PBKDF2 with HMAC-SHA1, we can replace wpa_passphrase with a direct function call.
See koreader/koreader#11089 where the function is used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1693)
> Add ffi definitions for libcrypto

- thirdparty/cmake_modules/koreader_thirdparty_git.cmake
The value of `ARGV4` is undefined when the number of arguments passed to the function is less than 5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1702)
> cmake: fix `ko_write_gitclone_script` function

- Makefile
- Makefile.defs
- Makefile.third
Don't depend on directories (as their timestamps cannot be relied on).
Make the crengine main library and its 3rd party libraries depend on the libraries needed for compilation, even though their not technically used (no link for static libraries), so they get build first (and their headers are available). Also touch the rule targets to prevent make from re-executing it again and again if one of those libraries is more recent, but no headers changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1701)
> fix crengine, koreader-cre, and mupdf rules

- Makefile.third
It's available starting with API level 18, our minimum supported version.
```c
#if __ANDROID_API__ >= 18
double log2(double __x) __INTRODUCED_IN(18);
float log2f(float __x) __INTRODUCED_IN(18);
long double log2l(long double __x) __RENAME_LDBL(log2, 18, 18);
#endif /* __ANDROID_API__ >= 18 */
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1703)
> sqlite: don't set `HAVE_LOG2=0` on Android

- .circleci/config.yml
No sense in wasting re-building stuff without cache if the testsuite fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1708)
> circleci: save the cache before running tests

- thirdparty/gettext/CMakeLists.txt
- thirdparty/libiconv/CMakeLists.txt
- thirdparty/tar/CMakeLists.txt
Note: this does increase the minimum CMake version to 3.7.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1711)
> add fallback URLs for gettext, libiconv & tar downloads

- toolchain/Makefile
java -version
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (build 1.8.0_392-b08)
OpenJDK 64-Bit Server VM (build 25.392-b08, mixed mode)
./sdkmanager --list --verbose | grep patcher
empty result
Build fails here:
./sdkmanager "platform-tools" "build-tools;30.0.2" "platforms;android-30" "patcher;v4" Warning: Failed to find package patcher;v4
Besides the fact I use arch linux and messed up with my system from time to time is only me facing this problem?
Can someone test whether the patcher is available? ./sdkmanager --list --verbose | grep patcher
I had to remove "patcher;v4" from the Makefile so the build could proceed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Fix dowload android sdk

- ffi/framebuffer_android.lua
Goes with https://github.com/koreader/android-luajit-launcher/pull/451
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1716)
> android: refactor full eink updates

- ffi/framebuffer_ion.lua
- ffi/framebuffer_sunxi.lua
Finally had time to see if I could find a workaround for the missing post-standby refreshes on sunxi, but that didn't pan out, so we're just left with comment cleanups ;p.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1714)
> sunxi: Minor comment updates

- Makefile.defs
- thirdparty/luajit/CMakeLists.txt
- thirdparty/sqlite/CMakeLists.txt
Also, minor third-party bumps for LuaJIT & SQLite.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1717)
> Work-around C++ weirdness on Legacy Kindle

- ffi/blitbuffer.lua
- ffi/framebuffer.lua
- ffi/framebuffer_SDL2_0.lua
- ffi/framebuffer_android.lua
- ffi/framebuffer_einkfb.lua
- ffi/framebuffer_mxcfb.lua
- ffi/framebuffer_pocketbook.lua
- ffi/framebuffer_sunxi.lua
https://github.com/koreader/koreader/issues/11303 showed that the current alignment trickery for HW dithering on mxcfb was a bit shoddy, so refactor the whole thing to do everything at once, in a function actually designed for that use case, instead of re-purposing a blitting helper...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1718)
> FB: Refactor refresh rectangle bounding checks

- input/input-kindle.h
- input/input-kobo.h
- input/input-remarkable.h
- input/input-sony-prstux.h
Also, fix a minor issue on Kobo, where evdev events would stomp the event value (not that we do anything with it, but, still).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1723)
> Input: Forward the suspend/wakeup source on Kindle

- ffi/framebuffer_sunxi.lua
- input/input-kindle.h
- input/input.c
Compute the proper dimensions instead, as getBoundedRect no longer accepts nil ;).
Re: https://github.com/koreader/koreader/issues/11354
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1725)
> FB/sunxi: Don't nil w & h in the rotation hack

- ffi/framebuffer_sunxi.lua
Followup to the rotation hack fix from #1725
(Harmless in practice, as we don't have sunxi devices with a viewport ;p).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1726)
> FB/sunxi: Use the screen's dimensions, not the viewport

- input/input-kindle.h
c.f., https://github.com/koreader/koreader/pull/11350#issuecomment-1891140373
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1727)
> Input/Kindle: Forward the arguments from wakeupFromSuspend & readyToSuspend

- ffi/framebuffer_linux.lua
- input/input-kindle.h
will be needed to test kindle rotate shenanigans where we do not set forced_rotation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1728)
> setHWRotation: nil guard self.forced_rotation

- ffi/SDL2_0.lua
- ffi/framebuffer_SDL2_0.lua
When running in Wayland, calling SDL_DestroyRenderer after SDL_Quit can cause a segmentation fault.
Fixes <https://github.com/koreader/koreader/issues/11371>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1730)
> ffi/sdl: ensure correct order of SDL_DestroyRenderer followed by SDL_Quit

- Makefile
The TC is old enough that the order of flags matters, a lot.
Regression since #1638
Re: https://github.com/koreader/koreader/issues/11172
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1734)
> PB: make sure libinkview-compat actually ends up w/ inkview as a DT_NEEDED

- cre.cpp
May allow crengine's top status bar to display our customized frontend metadata.
See https://github.com/koreader/koreader/issues/11461#issuecomment-1937056085
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1736)
> cre.cpp: add overrideDocumentProp()

- Makefile.defs
Broke with a double digits minor number (luarocks 3.10).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1742)
> fix luarocks' version check

- thirdparty/libunibreak/CMakeLists.txt
Includes:
- https://github.com/koreader/crengine/pull/558 : 
- In-page footnotes: avoid with '-cr-hint: noteref-ignore' 
- In-page footnotes: ensure they don't cross "flows"
- Tables: fix rendering when negative text-indent
- FB2 cover drawing: ensure _invertImages flag
- EPUB: fallback to look for a cover in the first fragment
- TextLang: Russian: add typography rules https://github.com/koreader/crengine/pull/557
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1743)
> bump crengine: various fixes, improved Russian typography

- thirdparty/cmake_modules/patch-wrapper.sh
To support multiple patches in argument. Better than ignoring extra arguments after the first (e.g. in case of missing `COMMAND` in an external project patch command list).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1746)
> tweak `patch-wrapper.sh`

- .ci/test_script.sh
- Makefile
- Makefile.defs
To automatically install the necessary test suite dependencies and ensure `make test` work out of the box.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1747)
> make: improve test rules

- ffi/framebuffer_pocketbook.lua
This makes rendering slightly slower but removes all ghosting artifacts.
See my tests below. I have "Always flash on pages with images" setting ON.
| With `FullUpdate()` | With `FullUpdateHQ()` |
|--------|--------|
| <img src="https://github.com/koreader/koreader-base/assets/483357/6f9e7e3e-dd22-49bc-be3e-4d33b9f84953" width="400"> | <img src="https://github.com/koreader/koreader-base/assets/483357/0ba75d4c-6afa-40db-92d5-e5019eaa3147" width="400"> |
| <img src="https://github.com/koreader/koreader-base/assets/483357/71f7fc79-8f5e-47f0-94e1-ce38b0a87129" width="400"> | <img src="https://github.com/koreader/koreader-base/assets/483357/9e822a28-9e03-48e6-85e0-c2b09c1f839b" width="400"> | 
Ghosting is especially visible on the light parts of the images.
This should also help with the issues …
> Call `FullUpdateHQ` to eliminate ghosting on Pocketbook

- Makefile
- Makefile.defs
I forgot I had worked around the fact that the `busted` launcher installed on Arch Linux is actually a shell script, not a LUA file.
Said script also messes with the LUA environment (forcibly using lua5.4).
Switch to invoking the busted runner manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1756)
> make: fix test rule on Arch Linux

- toolchain/Makefile
To allow updating the OpenJDK Java version to 17.
Cf. https://github.com/koreader/android-luajit-launcher/pull/445. Next step will be to try to update the Android Docker image to 22.04 again, and if that does not work, it looks like `openjdk-17-jdk-headless` is available on Bionic, so fallback to that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1682)
> android: update SDK command line tools and tweak NDK install

- ffi/framebuffer_pocketbook.lua
Color Pocketbooks are especially prone to ghosting and normal refresh functions aren't helpful.
This change doesn't fix ghosting in all cases, but whenever one of `refreshFlash...` functions is called, there will be less (if no) ghosting.
For the cases where we still have ghosting, we should switch to calling one of `refreshFlash...` API methods.
Tested on Pocketbook Inkpad Color 3.
Fixes https://github.com/koreader/koreader/issues/11416
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1755)
> Use high quality refresh for flash updates on color Pocketbooks

- .ci/build_script.sh
- .ci/cache_restore_post.sh
- .ci/cache_save_pre.sh
- more information: ccache version, configuration
- reduce maximum size to 256M (twice an emulator debug build use)
- reset statistics after restore and show them before saving
- cleanup cache before saving
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1759)
> ci: tweak circleci cache handling

- .ci/build_script.sh
- .github/workflows/build.yml
- Makefile.defs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1764)
> factorize cgroups detection (for proper jobs/load settings)

- .github/workflows/build.yml
- thirdparty/harfbuzz/CMakeLists.txt
Additionally, fix possible build error if ragel is not installed and some of the ragel source files end up with a more recent timestamp than their pre-generated results.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1760)
> harfbuzz: fix ccache 4.9.1 errors

- cre.cpp
- ffi/util.lua
Will allow frontend to disable CRE finalizers when running code in a subprocess and explicitely exiting quickly without any proper cleanup.
See https://github.com/koreader/koreader-base/pull/1679#issuecomment-1809377704 and followups.
Buddy frontend addition:
```diff
--- a/frontend/document/credocument.lua
+++ b/frontend/document/credocument.lua
@@ -116,6 +116,15 @@ end
function CreDocument:engineInit()
if not engine_initialized then
cre = require("libs/libkoreader-cre")
+
+        -- When forking to execute any stuff in a sub-process,
+        -- as that stuff may not care about properly closing
+        -- the document, skip cre.cpp finalizer to avoid any
+        -- assertion failure.
+        require("ffi/util").addRunInSubProcessAfterForkFunc("cre_skip_teardown", function()
+ …
```
> CRE: avoid assert failure in sub-processes

- Makefile.third
- on CI, always clone with a shallow depth of 1
- use 3 jobs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1770)
> make: speedup `fetchthirdparty`

- .circleci/config.yml
Isolate by branch name (but allow falling back to a "master" cache for restore): we don't want different PRs using each others' cache.
Cf. discussion about caches in #1760.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1772)
> ci: fix CircleCI caching

- Makefile
- Makefile.defs
A few small cleanups.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1776)
> make: cleanups

- Makefile.third
Avoid destructive operations.
The CIs don't rely on it.
It does not help that it can be triggered by `./kodev build` when using a sparse checkout that does not include all submodules (like `platform/ubuntu-touch/ubuntu-touch-sdl`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1777)
> make: saner `fetchthirdparty`

- thirdparty/curl/CMakeLists.txt
- thirdparty/curl/fetch-ca-bundle.sh
Don't use the default build system rule to create the certificates bundle: connections to `hg.mozilla.org` from CIs seem to be flaky, resulting in regular failures.
Cf. https://curl.se/docs/caextract.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1778)
> curl: make certificates bundle generation more robust

- thirdparty/libk2pdfopt/CMakeLists.txt
Fix leptonica build with GCC 14.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1780)
> libk2pdfopt: bump

- Makefile
- Makefile.defs
- thirdparty/turbo/CMakeLists.txt
* remove soft-float arm32 variant
* use `LINUX_ARCH` for cross compilation (supported are `arm` and `arm64`)
* if `LINUX_ARCH` is not `arm` or `arm64` we assume native compilation. It should work fine on all of the supported targets but only was tested against a 64 bit host.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1504)
> generic linux package

- Makefile.defs
NEON support is available when compiling with `TARGET=linux LINUX_ARCH=arm64` (`-march=armv8-a`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1784)
> make: fix NEON support detection

- .ci/build_script.sh
- .ci/cache_restore_post.sh
- .ci/cache_save_pre.sh
- .ci/test_script.sh
- .circleci/config.yml
- .github/actions/brew_cache/action.yml
- .github/workflows/build.yml
- Makefile
Mostly fix CircleCI's caching, again.
Unlike Github Actions, a PR target repository does not matter (unless environment sharing is enabled), which mean that PR from a fork don't have access to the master's branch cache. So keying by branch will result in most PRs starting with a cache miss.
Switch to 2 caches (build directory and ccache), keyed on part of the source tree (ignoring LUA files, tests, cdecl, etc…).
Note: I tweaked the CircleCI resource classes because for some reason my builds were using the large ones by default (on my fork, instead of medium).
Example CI runs:
- miss on both caches: [CircleCI](https://app.circleci.com/pipelines/github/benoit-pierre/koreader-base/126/workflows/da066080-a863-4b24-9606-40bacc9ae834) / …
> CI improvements

- Makefile.third
- ffi/fbink_input_h.lua
- thirdparty/fbink/CMakeLists.txt
- thirdparty/kobo-usbms/CMakeLists.txt
* Update FBInk so that the feature actually exist ;p
* Update KoboUSBMS to a build that also uses it internally
* Build & ship a very minimal shared library variant on FBInk that *only* provides this facility (it's 10K), that we'll be able to poke at via FFI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1782)
> Ship libfbink_input to provide input device classification

- ffi/SDL2_0.lua
Tested on a Dual Sense, which natively reports the dpad as a hat, but that SDL appears to translate into buttons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1786)
> SDL: Handle DPads reported as buttons and not hats

- input/input.c
- thirdparty/fbink/CMakeLists.txt
- thirdparty/kobo-usbms/CMakeLists.txt
Specifically, implement input.fdopen so we can keep the fds opened by fbink_input_scan without having to do a stupid close->open dance on top.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1788)
> Some more input & input_scan shenanigans

- cre.cpp
Includes https://github.com/koreader/crengine/pull/565 : 
- html5.css: really ensure ruby centering
- `getRenderedWidths()`: fix possible crash with 0-width images
- Page splitting: ignore empty non-linear flows
- LvDocView header: allow overriding "page/total %"
cre.cpp: add `setPageInfoOverride()` to allow tweaking top status bar display of page number/count/%.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1792)
> bump crengine: minor fixes (ruby, a crash, non-linear flows)

- thirdparty/kpvcrlib/CMakeLists.txt
We want both `-fvisibility-inlines-hidden` **and** `-fvisibility=hidden`.
This reduce `koreader-cre`'s final code size by ~174-220 KB (and potentially improve performance).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1795)
> crengine: fix `libcrengine.a` symbols visibility

- Makefile.defs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1798)
> fix building for `kindle-legacy` target

- Makefile.defs
Take advantage of ccache when using it to rewrite relative paths in the compiler’s standard error output to absolute paths.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1802)
> make: improve compiler diagnostics output

- ffi-cdecl/mupdf_decl.c
- ffi/mupdf.lua
- ffi/mupdf_h.lua
- thirdparty/mupdf/CMakeLists.txt
- thirdparty/mupdf/encrypted_zip.patch
- thirdparty/mupdf/external_fonts.patch
- thirdparty/mupdf/read_large_zip.patch
- thirdparty/mupdf/webp-upstream-697749.patch
- wrap-mupdf.h
There's one minor fix (correct `fz_recognize_image_format`'s prototype), but mostly tweak some patches to make updating easier (e.g. reduce conflicts), and trim FFI cdecls to keep only the declarations we need.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1791)
> mupdf: pre update cleanups

- cmake/CMakeLists.txt
- thirdparty/sdcv/CMakeLists.txt
Detect libc support at configure time, instead of hardcoding it.
This fix building on Alpine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1806)
> gettext & iconv: detect libc support

- ffi-cdecl/mupdf_decl.c
- ffi/mupdf.lua
- ffi/mupdf_h.lua
- wrap-mupdf.h
`fz_default_color_params` is no longer a function, but a plain constant.
Regression since #1805
Re: https://github.com/koreader/koreader/issues/11952
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1808)
> MuPDF: Unbreak RGB->BGR swap

- .github/workflows/build.yml
We actually don't need luarocks anymore for building (just testing).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1809)
> ci/macos: trim build dependencies

- Makefile.defs
So it works on Fedora: wget2 is provided, instead of the standard version, which does not support any of the progress options yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1811)
> make: tweak wget parameters

- thirdparty/mupdf/external_fonts.patch
```
cannot find builtin font with name 'Symbol' (4)
```
Cf. https://github.com/koreader/koreader/issues/11959
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1812)
> mupdf: fix builtin font error

- thirdparty/mupdf/external_fonts.patch
This is the correct MuPDF 1.24.2 update to the "external fonts" patch, preventing both https://github.com/koreader/koreader/issues/11959 and https://github.com/koreader/koreader/issues/11983.
And our little guy `◂` is now correctly rendered too!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1815)
> mupdf: fix fallback fonts handling

- Makefile.defs
- README.md
Adds support for building koreader for kindles after the switch to hardfloats using https://github.com/notmarek/koxtoolchain. This is more of an example for people adventuring into jailbreak on newer firmwares rather than a ready for production toolchain since @NiLuJe mentioned wanting to do multiple modifications to it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1814)
> feat: Add support for kindles after fw 5.16.3

- thirdparty/mupdf/CMakeLists.txt
Ensure it's executable, so `bindeps` & `libcheck` targets don't ignore it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1818)
> mupdf: fix shared library permissions

- thirdparty/mupdf/external_fonts.patch
- wrap-mupdf.h
Rework external fonts patch to fix second variant of https://github.com/koreader/koreader/issues/11959.
Fix `mupdf_fz_resolve_link` backward incompatible change when link position cannot be resolved: don't return `(NaN, NaN)`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1821)
> mupdf: fixes

- .ci/helper_shellchecks.sh
Quote argument to `git ls-files`: ensure the glob is evaluated by git, not bash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1822)
> ci: fix shellchecks helper

- cre.cpp
Includes:
- Russian hyphenation: revert "allow hyphens after не" https://github.com/koreader/crengine/pull/568
- Serbian hyphenation: combine patterns for Cyrillic and Latin scripts https://github.com/koreader/crengine/pull/566
- writeNodeEx(): fix handling of multilines attribute values https://github.com/koreader/crengine/pull/569
- Add getBalancedHTML() helper
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1824)
> bump crengine: update Russian and Serbian hyphenation

- ffi/util.lua
basename("/foo/") yielding "" is very much not what we signed up for...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1825)
> ffi/util: Deal with stupid GNU basename quirks

- thirdparty/luasocket/CMakeLists.txt
- thirdparty/luasocket/luasocket-enforce-cloexec.patch
And enforce CLOEXEC on open'ed sockets, to avoid weird crap like https://github.com/koreader/koreader/issues/12043
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1827)
> LuaSocket: Bump to 20240524

- Makefile.defs
Don't override existing flags when verbose mode is enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1830)
> make: fix `NINJAFLAGS` handling

- Makefile.defs
Use `-eo pipefail` so errors in pipe commands are not ignored.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1831)
> make: fix shell

- ffi/framebuffer_SDL2_0.lua
Check for a non-empty value.
Will make it easier to update kodev's run support for `--simulate`:
```diff
--- i/kodev
+++ w/kodev
@@ -582,6 +582,7 @@ TARGET:
+    screen_bw=
screen_width=540
screen_height=720
export KODEBUG=1
@@ -685,6 +686,7 @@ TARGET:
device_model="${VALUE}"
case "${device_model}" in
kindle)
+                        screen_bw=1
screen_width=600
screen_height=800
screen_dpi=167
@@ -827,7 +829,7 @@ TARGET:
RETURN_VALUE=85
while [ "${RETURN_VALUE}" -eq 85 ]; do
-                    env EMULATE_READER_W="${screen_width}" EMULATE_READER_H="${screen_height}" EMULATE_READER_DPI="${screen_dpi}" \
+                    env EMULATE_BW_SCREEN="${screen_bw}" EMULATE_READER_W="${screen_width}" EMULATE_READER_H="${screen_height}" EMULATE_READER_DPI="${screen_dpi}" \
${KOREADER_COMMAND} …
```
> ffi/sdl: tweak support for `EMULATE_BW_SCREEN`

- thirdparty/tesseract/CMakeLists.txt
- thirdparty/tesseract/no_debug_fonts.patch
Avoid spurious error traces:
```
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1834)
> tesseract: disable debug fonts

- cache-key.base
Ensure changes to `ffi-cdecl/koptcontext_cdecl.c` trigger a full build.
Forgot to do it as part of #1837.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1838)
> kopt: add CI cache key exception

- thirdparty/cmake_modules/koreader_thirdparty_libs.cmake
- thirdparty/djvulibre/CMakeLists.txt
Compile a static djvulibre library.
Impact on release builds code (bss+data+text) and file sizes:
|      | android-arm64|  emulator | kindlepw2 |
|  --- |         ---: |      ---: |      ---: |
| code |    -426.8 KB | -300.2 KB | -230.9 KB |
| file |    -429.1 KB | -331.3 KB | -234.5 KB |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1839)
> trim down koreader-djvu library

- ffi/koptcontext.lua
Use with:
```diff
--- i/frontend/document/document.lua
+++ w/frontend/document/document.lua
@@ -387,14 +387,6 @@ function Document:updateColorRendering()
end
end
-function Document:preRenderPage()
-    return nil
-end
-
-function Document:postRenderPage()
-    return nil
-end
-
function Document:getTileCacheValidity()
return self.tile_cache_validity_ts
end
@@ -435,7 +427,6 @@ function Document:renderPage(pageno, rect, zoom, rotation, gamma, render_mode, h
if hinting then
CanvasContext:enableCPUCores(2)
end
-    self:preRenderPage()
local page_size = self:getPageDimensions(pageno, zoom, rotation)
-- this will be the size we actually render
@@ -493,7 +484,6 @@ function Document:renderPage(pageno, rect, zoom, rotation, gamma, render_mode, h
page:close()
DocCache:insert(hash, tile)
- …
```
> kopt: color support

- thirdparty/tesseract/cmake_tweaks.patch
Since we're building a static library, we need to make sure all libraries the shared library would normally link with are forwarded to the pkg-config file, including `cpu_features` & `ndk_compat` on Android.
Close koreader/koreader#12098.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1841)
> tesseract: fix pkg-config entry on Android

- ffi/mupdf.lua
Remove `page:toBmp` unused `color` argument.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1846)
> ffi/mupdf: minor cleanup

- cre.cpp
- djvu.c
- thirdparty/cmake_modules/koreader_targets.cmake
- thirdparty/kpvcrlib/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1849)
>  cmake: enable `-Wall` when compiling koreader targets

- .circleci/config.yml
Support for the make generator was dropped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1856)
> ci/circle: drop `emu_gcc_make` job

- utils/gen_linker_exports.sh
Cf. https://github.com/koreader/koreader/issues/12190.
Note: compiling for arm64 with XCode 15.4 still does not work because of our old glib.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1857)
> fix macOS build

- ffi/SDL2_0.lua
To prevent things like unexpected textinput or popups, see <https://github.com/koreader/koreader/pull/12162#issuecomment-2243812140> for more details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1862)
> SDL: call SDL_StopTextInput() on start

- .github/workflows/build.yml
Avoid breakage on runner image update, like the recent update to XCode 15.4 on arm64 which breaks our (ancient) glib build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1870)
> ci/macos: pin XCode version

- thirdparty/cmake_modules/koreader_thirdparty_libs.cmake
- need to link with `libpthread` on Linux
- need to link with `CoreFoundation` on macOS
Note: depends on #1867 (for `DARWIN` → `APPLE`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1868)
> djvulibre: add missing dependencies

- Makefile
- Makefile.defs
Main change: before this PR, the output `data` directory would be symlinked to a directory in crengine submodule (`thirdparty/kpvcrlib/crengine/cr3gui/data`): this would pollute the checkout, and could result in some target specific build artifacts getting picked when building a release for other targets (e.g. `KoboUSBMS.tar.gz`).
Now, `data` is a directory, and the relevant files from `thirdparty/kpvcrlib/crengine/cr3gui/data` are symlinked. Note: `data/dict` and `data/tessdata` are still symlinked to directories created in `thirdparty/kpvcrlib/crengine/cr3gui/data`, so for example installed dictionaries survive a `make re` (which I assumed is by design).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> miscellaneous build system changes

- .circleci/config.yml
- Makefile.defs
Don't rely on `CC/CXX`: it make it seems like a specific version could be used (`CC=clang-18 make`), but the actual value is ignored and overridden with `clang` (same for `CXX`). And while `make CC=clang-18` is honored, this result in ccache support being partially disabled.
Instead, use a custom dedicated variable: `USE_CLANG`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1861)
> make: rework support for using clang

- djvu.c
The value stored in `msg` is never used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1864)
> djvu: fix clang-tidy warning

- thirdparty/libk2pdfopt/CMakeLists.txt
Don't generate `k2pdfopt_exports.cmake` in libk2pdfopt cmake build directory, or it will not survive cleaning the external project.
Cf. https://github.com/koreader/koreader-base/issues/1873#issuecomment-2254775309.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1877)
> libk2pdfopt: fix configure after `make libk2pdfopt-clean`

- thirdparty/tesseract/cmake_tweaks.patch
Correct the version: `5.3.4`, and not `tesseract_VERSION-NOTFOUND`!
Cosmetic, no impact on the build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1876)
> tesseract: fix pkg-config entry

- ffi/framebuffer_mxcfb.lua
This was an attempt to alleviate highlight flickers, given that it's caused by the CFA pass.
Unfortunately, the non-CFA pass uses different MDP buffers, and apparently the driver looses its damn mind when mixed with actual CFA updates.
This is not an issue when *nothing* uses CFA (e.g., 8bpp or Eclipse).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1874)
> mxcfb: Commit an experiment for posterity's sake

- Makefile
When included by koreader's main makefile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1880)
> make: fix test data download directories

- thirdparty/libjpeg-turbo/CMakeLists.txt
Changelog (nothing major): https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/3.0.3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1891)
> libjpeg-turbo: update to 3.0.3

- thirdparty/harfbuzz/CMakeLists.txt
Changelog (nothing major): https://github.com/harfbuzz/harfbuzz/releases/tag/9.0.0
Library code sized increased by ~16-22 KB.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1892)
> harfbuzz: update to 9.0.0

- ffi/mupdf.lua
- thirdparty/mupdf/CMakeLists.txt
- thirdparty/mupdf/visibility.patch
- thirdparty/mupdf/webp-upstream-697749.patch
Changelog: https://www.mupdf.com/releases/history
Potentialy relevant?
> Fix font size bug when parsing html without a font size unit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1893)
> mupdf: update to 1.24.8

- thirdparty/cmake_modules/koreader_external_project.cmake
- thirdparty/cmake_modules/koreader_thirdparty_common.cmake
- thirdparty/turbo/CMakeLists.txt
- `APPLE` → `TRUE` when the host machine system is macOS
- `CMAKE_HOST_APPLE` → `TRUE` when the build machine system is macOS
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1895)
> cmake: fix build machine checks for macOS

- toolchain/Makefile
Android Gradle Plugin 8.4.0 needs at least 34.0.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1897)
> android: bump sdk build tools

- thirdparty/cmake_modules/koenv.sh
When using the `exec $SHELL` directive in the plan for `git rebase --interactive`, the spawned shell will inherit the `$GIT_DIR` environment variable. This breaks most `git` invocations when downloading / checking out a git external project (like enabling a sparse-checkout in base, wiping whole parts of the tree, …).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1902)
> cmake: fix possible git external project issue

- thirdparty/czmq/CMakeLists.txt
Avoid it getting always triggered because of missing `src/platform.h` (removed during configure step).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1908)
> czmq: fix build step

- cmake/CMakeLists.txt
- thirdparty/ffi-cdecl/CMakeLists.txt
- thirdparty/ffi-cdecl/ffi-cdecl.patch
- thirdparty/ffi-cdecl/ffi-cdecl.sh.in
- thirdparty/zlib/CMakeLists.txt
Only for native emulator builds with GCC: after compiling base, use `make gcc-lua-cdecl` to compile and install to staging a small helper script and everything needed to run it. Example use:
```C
▹ ./build/x86_64-pc-linux-gnu-debug/staging/bin/ffi-cdecl.sh -I . -d lept -n ffi-cdecl/leptonica_cdecl.c
/usr/bin/gcc -fplugin=[…]/base/build/x86_64-pc-linux-gnu-debug/staging/lib/gcc/plugin/gcclua.so -fplugin-arg-gcclua-script=[…]/base/build/x86_64-pc-linux-gnu-debug/staging/share/lua/5.1/ffi-cdecl.lua -I[…]/base/build/x86_64-pc-linux-gnu-debug/staging/include/ffi-cdecl -I[…]/base/build/x86_64-pc-linux-gnu-debug/staging/include -I. -I[…]/base/build/x86_64-pc-linux-gnu-debug/staging/include -I[…]/base/build/x86_64-pc-linux-gnu-debug/staging/include/leptonica …
```
> helper to generate / update FFI cdecls

- ffi/zipwriter.lua
Avoid loading the system version instead of ours.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1912)
> ffi: avoid loading 2 different zlib libraries

- thirdparty/freetype2/CMakeLists.txt
https://github.com/freetype/freetype/compare/VER-2-13-2...VER-2-13-3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1901)
> thirdparty/freetype 2.13.3

- thirdparty/freetype2/CMakeLists.txt
- thirdparty/freetype2/fix_meson_bzip2_option.patch
Otherwise the macOS CI build of freetype2 end-up with bzip2 support:
```
freetype2 2.13.3
Operating System
OS             : darwin
Used Libraries
Zlib           : none
Bzip2          : yes
Png            : no
Harfbuzz       : no
Brotli         : no
```
```
build/libs/libfreetype.6.dylib:
SONAME    : @rpath/libfreetype.6.dylib
RPATH     : @executable_path/libs:@executable_path/../koreader/libs
NEEDED    : /usr/lib/libbz2.1.0.dylib
NEEDED    : /usr/lib/libSystem.B.dylib
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1916)
> freetype2: ensure bzip2 support is disabled

- ffi/blitbuffer.lua
Re https://github.com/koreader/koreader/pull/12438
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1918)
> BlitBuffer: Don't crash on nil input in colorFromName

- Makefile.defs
MuPDF would fail to open some ZIPs:
> MuPDF cannot open file.: cannot find end of central directory (7)
Make sure all code is compiled with `-U_FILE_OFFSET_BITS -D_FILE_OFFSET_BITS=32`.
NOTE: the initial `-U_FILE_OFFSET_BITS` is for meson external projects (cf. https://github.com/mesonbuild/meson/issues/3519).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1917)
> android: fix 32bits builds

- Makefile.defs
- thirdparty/cmake_modules/koreader_thirdparty_common.cmake
- thirdparty/djvulibre/CMakeLists.txt
- thirdparty/freetype2/CMakeLists.txt
- thirdparty/fribidi/CMakeLists.txt
- thirdparty/harfbuzz/CMakeLists.txt
- thirdparty/libunibreak/CMakeLists.txt
- thirdparty/openssl/CMakeLists.txt
- autotools doesn't by default
- ditto with meson
- gradle will ignore versioned libraries, and not include them in the APK
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1907)
> android: don't version shared objects

- ffi/mupdf.lua
Don't create Lua strings with an embedded null terminator.
Cf. https://github.com/koreader/koreader/pull/12468.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1921)
> ffi/mupdf: fix metadata strings

- ffi/blitbuffer.lua
We want to access the actual luminance value instead of the struct pointer ;o).
Fix https://github.com/koreader/koreader/issues/12473
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1922)
> Lua blitter: Fix the mul method for grayscale Color data types

- ffi/mupdf.lua
- thirdparty/mupdf/CMakeLists.txt
> MuPDF 1.24.9 (2024-08-29)
> 
> The 1.24.9 source only release is now available.
> 
>     Improve memory usage for shadings.
>     Improve rendering speed when applying transfer functions to softmasks.
>     Avoid crashing due to colorspaces.
>     Fix bug with SVG clip paths.
>     Fix several bugs concerning text extraction.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1923)
> mupdf: update to 1.24.9

- ffi/jpeg.lua
- thirdparty/libjpeg-turbo/CMakeLists.txt
The turbojpeg library symbols are versioned, so it should always be  backward compatible: the major & patch numbers are always 0, and when a new API version is made available, the minor number is incremented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1927)
> libjpeg-turbo: use versioned `turbojpeg` library

- thirdparty/lua-ljsqlite3/init.lua
- thirdparty/sqlite/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1928)
> sqlite: use versioned library

- thirdparty/luajit/CMakeLists.txt
To prevent Lua modules from linking with it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1930)
> luajit: patch out library from pkg-config entry when not used

- ffi/koptcontext.lua
- ffi/koptcontext_h.lua
- thirdparty/libk2pdfopt/CMakeLists.txt
Return `nil` (rather than an empty string) when `k2pdfopt_tocr_single_word` failed to initialize tesseract (bad or missing data) so the caller can differentiate with OCR misses (no results).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1932)
> kopt: improve OCR API

- thirdparty/libk2pdfopt/CMakeLists.txt
Cf. https://github.com/koreader/libk2pdfopt/pull/57
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1937)
> libk2pdfopt: fix uninitialized memory access

- Makefile.defs
- ffi/blitbuffer.lua
- ffi/crypto.lua
- ffi/freetype.lua
- ffi/harfbuzz.lua
- ffi/input_pocketbook.lua
- ffi/jpeg.lua
- ffi/koptcontext.lua
- ffi/loadlib.lua
- ffi/mupdf.lua
- ffi/pic.lua
- ffi/png.lua
- ffi/utf8proc.lua
- ffi/util.lua
- ffi/webp.lua
- ffi/zipwriter.lua
- ffi/zlib.lua
- ffi/zstd.lua
- spec/unit/font_spec.lua
- spec/unit/koptcontext_spec.lua
- thirdparty/lua-ljsqlite3/init.lua
- thirdparty/turbo/CMakeLists.txt
- thirdparty/turbo/turbo.patch
Provide a `ffi.loadlib` helper, replacing `ffi.load` and `util.ffiLoadCandidates` for loading our libraries.
Prerequisite for #1920 & https://github.com/koreader/koreader/pull/12545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1938)
> ffi/loadlib: add module

- ffi/jpeg.lua
We want to fallback on the unversioned system library if we're not shipping ours and the system version is different: if the version is too old, the symbols we need will be unresolved, otherwise, any newer version should be backward compatible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1940)
> ffi/jpeg: fix turbojpeg library load fallback

- cmake/CMakeLists.txt
- thirdparty/glib/CMakeLists.txt
- thirdparty/sdl2/CMakeLists.txt
- thirdparty/sdl2/appimage.patch
- thirdparty/sdl2/cmake_tweaks.patch
Getting an updated version fix an issue with some erroneous   key events being processed when using a X11 window manager:
- start KOReader on a virtual desktop, say the first one
- switch to another desktop, and back using the WM shortcut  (`Super+1`)
- on getting back focus, KOReader somehow end up processing a `1` key press event, jumping to the beginning of the current book
Note: will need an updated `koappimage` docker image.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1946)
> build sdl2 for appimage

- Makefile.defs
- README.md
- thirdparty/fbink/CMakeLists.txt
- thirdparty/harfbuzz/CMakeLists.txt
- thirdparty/kobo-usbms/CMakeLists.txt
- thirdparty/luajit/CMakeLists.txt
Now that the TCs are ready ;).
Also, minor third-party bumps.
(Rebase me)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1943)
> Add a kobov5 target

- Makefile.defs
Make sure we use our libpng headers, and not an older framework version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1954)
> libk2pdfopt: fix macOS build

- thirdparty/cmake_modules/koenv.sh
Fix cleanup of build artifacts when the build create directories.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1953)
> cmake: fix external projects in source tree rebuilds

- thirdparty/libjpeg-turbo/CMakeLists.txt
https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/3.0.4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1959)
> Update to libjpeg-turbo 3.0.4

- thirdparty/glib/CMakeLists.txt
- thirdparty/glib/libglib-only.patch
- thirdparty/glib/no_glibc_2.6_or_above_symbols.patch
- thirdparty/sdcv/CMakeLists.txt
- thirdparty/sdcv/compat_with_newer_glib.patch
Highlight: fix `futex_time64()` use on Android ≤ 10 (cf. https://github.com/koreader/koreader/issues/12601).
Full changelogs:
- https://gitlab.gnome.org/GNOME/glib/-/releases/2.81.0
- https://gitlab.gnome.org/GNOME/glib/-/releases/2.81.1
- https://gitlab.gnome.org/GNOME/glib/-/releases/2.81.2
- https://gitlab.gnome.org/GNOME/glib/-/releases/2.82.0
- https://gitlab.gnome.org/GNOME/glib/-/releases/2.82.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1960)
> glib: update to 2.82.1

- Makefile.defs
Prevent make from removing targets it considers as intermediate; e.g. when building from a pristine crengine's checkout:
```
[*] Install data files
make:
unlink: base/thirdparty/kpvcrlib/crengine/cr3gui/data/tessdata: Is a directory
make:
unlink: base/thirdparty/kpvcrlib/crengine/cr3gui/data/dict: Is a directory
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1962)
> make: prevent automatic removal of intermediates

- thirdparty/fbink/CMakeLists.txt
- thirdparty/kobo-usbms/CMakeLists.txt
Mainly to get the new USB PIDs in for the MTK lineup
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1968)
> Minor FBInk & USBMS bumps

- Makefile.defs
- thirdparty/cmake_modules/koreader_external_project.cmake
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1973)
> fix cmake 3.31 warnings

- .circleci/config.yml
Can't look at `/sys/fs/cgroup/cpu/cpu.shares` anymore…
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1976)
> ci/circle: manually cap build jobs

- ffi/mupdf.lua
- thirdparty/mupdf/CMakeLists.txt
Changelog:
> - Fix fz_image reference counting bug when redacting.
> - Fix bug with ordered list number in Story.
> - Fix bug where SMask TR needed to be cleared when SMask changes.
> - Add API to enumerate a cmap.
> - Various fixes for python bindings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1978)
> mupdf: update to 1.24.11

- ffi/mupdf.lua
Ignore empty word / line boxes, including the `fz_empty_rect` case (which changed from `(0, 0, 0, 0)` to `(FZ_MAX_INF_RECT, FZ_MAX_INF_RECT, FZ_MIN_INF_RECT, FZ_MIN_INF_RECT)` after the MuPDF update from 1.13.0 to 1.24.2).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1975)
> mupdf: fix `getPageText` implementation

- .circleci/config.yml
- koxtoolchain update to 2024.10 (https://github.com/koreader/koxtoolchain/releases/tag/2024.10)
- android image bump (with SDK build tools update to 34.0.0)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1977)
> ci/circle: bump docker images

- thirdparty/tesseract/CMakeLists.txt
- thirdparty/tesseract/cmake_tweaks.patch
https://github.com/tesseract-ocr/tesseract/releases/tag/5.5.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1980)
> tesseract: update to 5.5.0

- .github/workflows/build.yml
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /opt/homebrew
Could not symlink bin/pkg-config
Target /opt/homebrew/bin/pkg-config
is a symlink belonging to pkg-config@0.29.2. You can unlink it:
brew unlink pkg-config@0.29.2
To force the link and overwrite all conflicting files:
brew link --overwrite pkgconf
To list all files that would be deleted:
brew link --overwrite pkgconf --dry-run
Possible conflicting files are:
/opt/homebrew/bin/pkg-config -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/bin/pkg-config
/opt/homebrew/share/aclocal/pkg.m4 -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/share/aclocal/pkg.m4
/opt/homebrew/share/man/man1/pkg-config.1 -> /opt/homebrew/Cellar/pkg-config@0.29.2/0.29.2_3/share/man/man1/pkg-conf …
```
> ci/macos: fix possible issue during brew install

- .github/workflows/build.yml
- Makefile
- Makefile.defs
- cmake/CMakeLists.txt
- thirdparty/cmake_modules/koenv.sh
- thirdparty/cmake_modules/koreader_external_project.cmake
- thirdparty/luarocks/CMakeLists.txt
- thirdparty/spec/busted/CMakeLists.txt
- thirdparty/spec/dkjson/CMakeLists.txt
- thirdparty/spec/lua-term/CMakeLists.txt
- thirdparty/spec/lua_cliargs/CMakeLists.txt
- thirdparty/spec/luafilesystem/CMakeLists.txt
- thirdparty/spec/luassert/CMakeLists.txt
- thirdparty/spec/luasystem/CMakeLists.txt
- thirdparty/spec/mediator_lua/CMakeLists.txt
- thirdparty/spec/penlight/CMakeLists.txt
- thirdparty/spec/say/CMakeLists.txt
- utils/fake_tty.py
I wanted to run the tests on the macOS CI, but then I remembered lua5.1 is not supported by brew anymore, and figured I might as well make our testsuite self-sufficient (like with the meson branch): install luarocks to staging and the necessary Lua packages to a dedicated tree under the output `spec` directory.
This led to discovering 2 macOS specific issues: see #1953 & #1954.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1956)
> self sufficient testsuite + macos ci run tests

- ffi-cdecl/posix_decl.c
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1983)
> ffi/posix: fix typo in cdecls

- cmake/CMakeLists.txt
- thirdparty/spec/cluacov/CMakeLists.txt
- thirdparty/spec/luacov/CMakeLists.txt
This fix coverage on master (https://app.circleci.com/pipelines/github/koreader/koreader/11659/workflows/527da8a7-fe87-4125-8656-dd1a707a2a9e/jobs/17231). The addition of cluacov (which must be compiled for the luajit version used during coverage, or things go boom) also greatly speeds up things (see https://app.circleci.com/pipelines/github/benoit-pierre/koreader/528/workflows/59965b76-8cfa-4e07-a75e-454aefc6c088/jobs/547).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1984)
> tests: install luacov & cluacov to spec tree

- thirdparty/dropbear/CMakeLists.txt
- thirdparty/dropbear/localoptions.h.cmake
The ED25519 variant was missing, resulting in a failure to automatically generate the host key:
```
[15145] Nov 22 17:13:15 Couldn't create new file /etc/dropbear/dropbear_ed25519_host_key.tmp15145: No such file or directory
[15145] Nov 22 17:13:15 Exit before auth from <192.168.0.1:60314>: Couldn't read or generate hostkey /etc/dropbear/dropbear_ed25519_host_key
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1987)
> dropbear: add missing server key location override

- thirdparty/cmake_modules/koenv.sh
Work around cmake bug https://gitlab.kitware.com/cmake/cmake/-/issues/25428 (introduced in 3.23.0, fixed in 3.27.9): do not create `build.d` dependency files with phony targets (which would keep triggering unnecessary rebuilds of some external projects).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1986)
> cmake: fix external projects cmake bug

- .circleci/config.yml
New ccache versions respect the XDG spec: `~/.ccache` → `~/.cache/ccache`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1993)
> ci/circle: fix ccache cache

- Makefile.defs
```bash
▸ ./kodev test -vj1
make TARGET= KODEBUG=1 VERBOSE=1 testall T=-v\ -j\ 1
cd base/build/x86_64-pc-linux-gnu-debug/cmake && ninja -v -j\ -l8 all
ninja: fatal: invalid -j parameter
make: *** [base/Makefile:89: base-all] Error 1
```
Switch to `MFLAGS`: same value as `MAKEFLAGS` except that it does not contain the command line variable definitions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1995)
> make: fix corner case in -j / -l handling

- .ci/build_script.sh
- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1997)
> ci/circle: fix ccache cache, take 2

- thirdparty/freetype2/CMakeLists.txt
- thirdparty/freetype2/ftcalc_gcc12_arm_neon_fix.patch
Cf. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=117811.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1994)
> freetype2: work around GCC 12 ARM NEON bug

- cmake/CMakeLists.txt
- thirdparty/cmake_modules/koreader_thirdparty_libs.cmake
- thirdparty/kpvcrlib/CMakeLists.txt
- thirdparty/kpvcrlib/crsetup.h.cmake
- thirdparty/md4c/CMakeLists.txt
- thirdparty/md4c/cmake_tweaks.patch
Cf. https://github.com/koreader/koreader/issues/12683.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1969)
> crengine: add markdown support using md4c

- ffi/freetype.lua
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2000)
> freetype: cleanup stray semicolons

- cache-key.base
- ffi-cdecl/wrap-mupdf_cdecl.c
- ffi/mupdf.lua
- ffi/mupdf_h.lua
Some of the MuPDF tests segfault on quit pretty regularly (e.g.: `make --assume-old=all test T='mupdf -f jbig'`), this is because there's no guarantee that the context used to open a document or page won't be dropped before that document / page is.
Use the context private user pointer to keep a reference count and ensure it's only dropped last.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2001)
> mupdf: fix finalizers

- ffi-cdecl/wrap-mupdf_cdecl.c
- ffi/mupdf.lua
- ffi/mupdf_h.lua
- wrap-mupdf.h
Use fz_open_document_with_stream_and_dir instead of fz_open_document_with_stream to allow MuPDF to load resources (images and CSS) when it is loading a HTML document from a memory stream.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2002)
> mupdf: allow memory streams to load resources

- thirdparty/openssl/CMakeLists.txt
It's not used, and relies on glibc features not implemented on ARM anyway:
```
arm-pocketbook-linux-gnueabi/bin/../lib/gcc/arm-pocketbook-linux-gnueabi/14.2.0/../../../../arm-pocketbook-linux-gnueabi/bin/ld.bfd: crypto/async/arch/async_posix.o: in function `ASYNC_is_capable':
async_posix.c:(.text+0x8): warning: warning: getcontext is not implemented and will always fail
arm-pocketbook-linux-gnueabi/bin/../lib/gcc/arm-pocketbook-linux-gnueabi/14.2.0/../../../../arm-pocketbook-linux-gnueabi/bin/ld.bfd: crypto/async/async.o: in function `async_fibre_swapcontext.constprop.0.isra.0':
async.c:(.text+0x22): warning: warning: setcontext is not implemented and will always fail
arm-pocketbook-linux-gnueabi/bin/../lib/gcc/arm-pocketbook-linux-gnueabi/14.2.0/../../../../arm-pocketbook-linux-gnueabi/bi …
```
> openssl: do not build support for the async API

- cmake/CMakeLists.txt
- thirdparty/openssh/CMakeLists.txt
We actually don't need them for building the only 2 executables we care about (scp & sftp-server).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2011)
> openssh: drop openssl and zlib dependencies

- thirdparty/dropbear/CMakeLists.txt
- thirdparty/dropbear/localoptions.h.cmake
- thirdparty/openssh/CMakeLists.txt
We can't use the openssh one without shipping the `ssh` binary too, so instead, ship the one provided by dropbear (and the `dbclient` binary, which is dropbear equivalent for `ssh`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2012)
> dropbear & openssh: fix scp binary

- Makefile.defs
Turns out we can't have nice things because PW4 ;'(.
Might require a similar fix in the actual kindlehf TC.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2014)
> KindleHF: Downgrade mtune to A9

- xtext.cpp
Rename getSelectedWords to getSelectedWordIndices, and return the word boundary indices instead of the words. This is needed for highlighting. The words themselves can be obtained by passing the indices to the getText function.
Warning! Breaking change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2013)
> xtext: getSelectedWords returns with indices

- Makefile
- Makefile.defs
- spec/unit/common_spec.lua
- spec/unit/spore_spec.lua
- test-runner/busted_config.lua
- test-runner/busted_helper.lua
- test-runner/runtests
- initial LUA paths are now setup by the runner itself, so it can be executed directly without needing to manually set them before
- patch the LUA paths before actually executing the tests to remove the testsuite specific entries (e.g. `spec/rocks/…`), ensuring tests only have access to shipped packages
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2016)
> tests: improve test runner and testsuite isolation

- cmake/CMakeLists.txt
- thirdparty/dkjson/CMakeLists.txt
- thirdparty/lua-Spore/CMakeLists.txt
- thirdparty/spec/dkjson/CMakeLists.txt
https://framagit.org/fperrad/lua-Spore/-/tags/0.4.0
https://framagit.org/fperrad/lua-Spore/-/compare/0.3.4...0.4.0
Edit: of note, "switch to dkjson"
https://framagit.org/fperrad/lua-Spore/-/commit/8e7ad16a772ce7e13a4fbc33de33b045426dcb51
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2015)
> thirdparty/lua-Spore 0.4.0

- thirdparty/harfbuzz/CMakeLists.txt
- thirdparty/harfbuzz/android.patch
- thirdparty/harfbuzz/no-subset.patch
https://github.com/harfbuzz/harfbuzz/releases/tag/10.2.0
Additionally, don't compile support for unused APIs. Example code size reduction for release builds (vs master with 10.1.0):
- `android-arm64`: -70.3 KB
- `emu-x86_64`: -141.1 KB
- `kindlepw2`: -87.1 KB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2018)
> harfbuzz: update to 10.2.0

- thirdparty/cmake_modules/koenv.sh
Cleaning directories need to be done in reverse order.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2019)
> cmake: fix cleaning an external project source tree

- Makefile.defs
Not necessary anymore with the latest toolchains.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2021)
> make: drop kindle-legacy / pocketbook workaround

- thirdparty/kpvcrlib/crsetup.h.cmake
This get rid of one `LVRef` related compilation warning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2028)
> crengine: do not compile unused code

- thirdparty/sqlite/CMakeLists.txt
- thirdparty/sqlite/overlay/CMakeLists.txt
- https://sqlite.org/releaselog/3_48_0.html
- https://sqlite.org/releaselog/3_49_0.html
Additionally, switch to cmake for building: version (3.49.0) switches to autosetup, which depends on tclsh. There's a fallback on an automatically compiled jimsh binary, but at this point we might as well switch to the smallest amalgam source distribution plus a custom CMake build (as we only need the library).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2030)
> sqlite: update to 3.49.0

- thirdparty/kobo-usbms/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2042)
> kobo-usbms: ensure `KoboUSBMS.tar.gz` binaries are stripped

- thirdparty/luarocks/CMakeLists.txt
- need to set `LD` to our compiler (or luasystem will try to use gcc when building with clang)
- set `RT_LIBDIR` (directory where librt is) or luasystem will fail to build with clang
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2041)
> luarocks / luasystem: fix build under koreader/kobase-clang:0.3.6-20.04

- thirdparty/libzmq/cmake_tweaks.patch
- thirdparty/lua-rapidjson/cmake_tweaks.patch
- thirdparty/lunasvg/CMakeLists.txt
- thirdparty/lunasvg/cmake_tweaks.patch
Newer CMake versions dropped compatibility with CMake < 3.5:
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2048)
> fix build with newer CMake versions

- thirdparty/harfbuzz/CMakeLists.txt
- https://github.com/harfbuzz/harfbuzz/releases/tag/10.4.0
- https://github.com/harfbuzz/harfbuzz/releases/tag/11.0.0
- https://github.com/harfbuzz/harfbuzz/releases/tag/11.0.1
A small code size increase: +30.4 KB for `x86_64-pc-linux-gnu`, +25.6 KB for `arm-kindlepw2-linux-gnueabi`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2049)
> harfbuzz: update to 11.0.1

- thirdparty/sdl2/CMakeLists.txt
- thirdparty/sdl2/cmake_tweaks.patch
- https://github.com/libsdl-org/SDL/releases/tag/release-2.32.0
- https://github.com/libsdl-org/SDL/releases/tag/release-2.32.2
- https://github.com/libsdl-org/SDL/releases/tag/release-2.32.4
A small code size reduction: -30.8 K for `x86_64-pc-linux-gnu`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2052)
> sdl2: update to 2.32.4

- thirdparty/zsync2/CMakeLists.txt
- thirdparty/zsync2/cmake_tweaks.patch
Newer CMake versions dropped compatibility with CMake < 3.5.
Missed this in #2048.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2055)
> zsync2: fix build

- thirdparty/libwebp/CMakeLists.txt
- https://github.com/webmproject/libwebp/releases/tag/v1.4.0
- https://github.com/webmproject/libwebp/releases/tag/v1.5.0
A small code size increase: +11.1 KB for `x86_64-pc-linux-gnu`, +8.3 KB for `arm-kindlepw2-linux-gnueabi`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2050)
> libwebp: update to 1.5.0

- ffi/blitbuffer.lua
Add RGB32 variants for paintBorder and paintRoundedRect functions, currently the paintborder variant doesn't have support to rounded corners.
Allows for framecontainers with coloured backgrounds to be used io statistics plugin calendar view.
See: https://github.com/koreader/koreader/pull/13453#issue-2944166320
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2047)
> BlitBuffer: add partial support for paintRoundedRect using RGB colours

- thirdparty/libressl/CMakeLists.txt
More reliable than the OpenBSD CDN.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2057)
> libressl: add GitHub URL as main download source

- thirdparty/tar/CMakeLists.txt
We don't need it, and the added dependency on `libselinux.so.1` breaks the AppImage's tar binary on distribution that don't have that library (e.g. Arch Linux).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2061)
> tar: disable selinux support

- thirdparty/libiconv/CMakeLists.txt
To ensure we don't risk pulling a dependency on a (possibly external) libintl library.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2067)
> libiconv: disable NLS support

- .github/workflows/build.yml
```
cmake 3.31.6 is already installed
To upgrade to 4.0.1, run:
brew upgrade cmake
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2069)
> ci/macos: fix error annotations

- thirdparty/libressl/CMakeLists.txt
- https://github.com/libressl/portable/releases/tag/v4.1.0
A small code size reduction on Android:
- `x86_64-pc-linux-gnu`: -588 B
- `arm-kindlepw2-linux-gnueabi`: -792 B
- `armv7a-unknown-linux-android18`: -8.1 KB
- `aarch64-unknown-linux-android21`: -13.7 KB
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2073)
> libressl: update to 4.1.0

- Makefile.defs
- thirdparty/cmake_modules/koreader_targets.cmake
We already used `-ffunction-sections` for Android ARM, and `-Wl,--gc-sections` for the monolibtic library. Extend it to all binaries (`-ffunction-sections` without `--gc-sections` does not make sense), and add `-fdata-sections`.
Code size reduction:
| platform: component     |   reduction        |
| :-                      | -:                 |
| appimage: koreader      |   -2.1 MB ( -7.0%) |
| appimage: sdcv          | -490.8 KB (-49.7%) |
| appimage: tar           |  -10.3 KB ( -2.1%) |
| android-arm: koreader   | -118.5 KB ( -1.0%) |
| android-arm: sdcv       | -354.0 KB (-22.1%) |
| android-arm64: koreader | -196.8 KB ( -1.0%) |
| android-arm64: sdcv     | -485.0 KB (-26.0%) |
| kindlepw2: koreader     |   -1.3 MB ( -6.7%) |
| kindlepw2: dbclient     |   -8.3 KB ( -3.9%) |
| …
> use `-fdata-sections -ffunction-sections -Wl,--gc-sections` on all supported targets

- CMakeLists.txt
- Makefile.defs
- cmake/CMakeLists.txt
- thirdparty/czmq/cmake_tweaks.patch
- thirdparty/giflib/overlay/CMakeLists.txt
- thirdparty/kpvcrlib/CMakeLists.txt
- thirdparty/leptonica/cmake_tweaks.patch
- thirdparty/libressl/cmake_tweaks.patch
- thirdparty/libzmq/cmake_tweaks.patch
- thirdparty/lodepng/overlay/CMakeLists.txt
- thirdparty/lpeg/overlay/CMakeLists.txt
- thirdparty/lua-rapidjson/cmake_tweaks.patch
- thirdparty/luasec/overlay/CMakeLists.txt
- thirdparty/luasocket/overlay/CMakeLists.txt
- thirdparty/lunasvg/cmake_tweaks.patch
- thirdparty/md4c/cmake_tweaks.patch
- thirdparty/minizip/overlay/CMakeLists.txt
- thirdparty/popen-noshell/overlay/CMakeLists.txt
- thirdparty/sdl2/appimage.patch
- thirdparty/sdl2/cmake_tweaks.patch
- thirdparty/sqlite/overlay/CMakeLists.txt
- thirdparty/tesseract/cmake_tweaks.patch
- thirdparty/turbo/overlay/CMakeLists.txt
- thirdparty/zsync2/cmake_tweaks.patch
We need at least 3.17 for libarchive, and Ubuntu 22.04 provides 3.22.1. Additionally, CMake support for versions <3.17 is deprecated since Meson 0.62.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2085)
> cmake: bump minimum required version to 3.17.5

- cmake/CMakeLists.txt
- ffi-cdecl/libarchive_cdecl.c
- ffi/libarchive_h.lua
- ffi/zipwriter.lua
- thirdparty/cmake_modules/koreader_targets.cmake
- thirdparty/cmake_modules/koreader_thirdparty_libs.cmake
- thirdparty/libarchive/CMakeLists.txt
- thirdparty/libarchive/android.patch
- thirdparty/mupdf/CMakeLists.txt
- add libarchive 3.7.9:
- compiled with zlib+zstd support
- only the library for now (we could look at replacing `tar` with `bsdtar`)
- re-implement ZipWriter using libarchive
- enable MuPDF libarchive support
Code size increase:
|               |                   |
|:-             |:-                 |
| emulator      | +735.9 KB (+2.7%) |
| kindlepw2     | +458.0 KB (+2.5%) |
| android-arm   | +262.4 KB (+1.8%) |
| android-arm64 | +349.8 KB (+1.8%) |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2083)
> libarchive support

- cmake/CMakeLists.txt
- thirdparty/cmake_modules/koenv.sh
The intent was always to use the same git clone.
Je devais pas avoir les yeux en face des trous quand j'ai codé cette portion… :P
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2093)
> fbink / fbdepth / libfbink_input: fix duplicate downloads

- cmake/CMakeLists.txt
No need for it now that libarchive is used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2095)
> tar: don't build it for the emulator target

- Makefile.defs
Since we're not using CMake's NDK support, setting `ANDROID_STL` is not necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2099)
> android: small cleanup

- cmake/CMakeLists.txt
So executables end-up in the right staging tree sub-directory.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2110)
> cmake: fix meson projects `bindir` install directory

- Makefile.defs
- cmake/CMakeLists.txt
- thirdparty/cmake_modules/koreader_thirdparty_libs.cmake
Since in monolibtic mode we only have the one C++ library, we can statically link the STL. Ditto for our only executable (sdcv).
This fix another potential dynamic linker issue on some devices (cf. koreader/koreader#13821).
This also net us a small code size reduction:
| Target: component       | Difference          |
|:------------------------|--------------------:|
| android-arm: koreader   |  -455.2 KB ( -3.0%) |
| android-arm: sdcv       |  -463.1 KB (-24.9%) |
| android-arm64: koreader |  -652.3 KB ( -3.1%) |
| android-arm64: sdcv     |  -689.3 KB (-28.7%) |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2100)
> android: statically link the STL when using monolibtic mode

- .github/workflows/build.yml
Update ninjatracing to account for latest ninja log format.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2114)
> ci/macos: fix "Dump build timings" step

- cmake/CMakeLists.txt
That's one less variable when trying to troubleshoot issues with the emulator/GA artifacts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2116)
> sdl2: always compile on macOS

- .circleci/config.yml
- .github/workflows/build.yml
- Makefile.defs
Default to 1 when building an emulator for the current machine, so `make …` commands build for the same configuration as kodev's default.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2118)
> make: align `KODEBUG` default with kodev

- thirdparty/czmq/CMakeLists.txt
- thirdparty/czmq/fix_prefix_handling.patch
Cf. https://github.com/koreader/koreader/issues/14070.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2135)
> czmq: backport 2 upstream bugfixes

- thirdparty/sdcv/CMakeLists.txt
- thirdparty/sdcv/ignore_hidden.patch
Including the dreaded `.DS_Store` and other macOS crap.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2138)
> sdcv: ignore hidden filesystem entries

- Makefile.defs
When compiling the emulator or for the `macos` target: while gcc is already an alias for clang, this might prevent the build system from picking another GCC install (e.g. from homebrew).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2140)
> make: use clang on macOS

- thirdparty/dropbear/CMakeLists.txt
- thirdparty/dropbear/fix__GNU_SOURCE_warnings.patch
Some platforms (e.g. kindle-legacy & pocketbook) pass `-D_GNU_SOURCE` as compilation flag, resulting a in build log littered with such warnings:
```
In file included from …/build/arm-pocketbook-linux-gnueabi/thirdparty/dropbear/source/src/options.h:11,
from …/build/arm-pocketbook-linux-gnueabi/thirdparty/dropbear/source/src/dbmalloc.h:4,
from …/build/arm-pocketbook-linux-gnueabi/thirdparty/dropbear/source/libtommath/tommath_class.h:1322,
from …/build/arm-pocketbook-linux-gnueabi/thirdparty/dropbear/source/libtommath/tommath_class.h:1305,
from …/build/arm-pocketbook-linux-gnueabi/thirdparty/dropbear/source/libtommath/tommath_class.h:1305,
from …/build/arm-pocketbook-linux-gnueabi/thirdparty/dropbear/source/libtommath/tommath_class.h:1305,
from …
```
> dropbear: fix `_GNU_SOURCE` compilation warnings

- .github/workflows/build.yml
Save it **after** checking the binaries, to ensure a directory with broken shared dependencies is not saved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2168)
> ci/macos: improve build directory cache

- thirdparty/sdl2/CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2170)
> sdl2: enable libdecor support when building an AppImage

- Makefile.defs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2172)
> appimage: fix `-march` tuning for non-x86_64 builds

- ffi/mupdf.lua
- thirdparty/mupdf/CMakeLists.txt
https://mupdf.com/releases/history#:~:text=1.26.10
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2178)
> mupdf: update to 1.26.10

- utils/gen_linker_exports.sh
Allow a semi-colon after a call to `cdecl_func` or `cdecl_var` (to appease vim automatic-indent when editing).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2181)
> utils: improve `gen_linker_exports.sh` script
