koreader/koreader-base

Makefile

so that patch won't fail if we update the patch.
This is a hot-fix.

reset local change before patching

---

.gitignore
.gitmodules
Makefile
Makefile.defs

by static linking of libz, libglib-2.0, libiconv and libintl

Build sdcv for Android

---

.gitignore
Makefile
Makefile.defs
ffi-cdecl/SDL1_2_decl.c
ffi-cdecl/SDL2_0_decl.c
ffi-cdecl/einkfb_decl.c
ffi-cdecl/freetype2_decl.c
ffi-cdecl/giflib_decl.c
ffi-cdecl/inotify_decl.c
ffi-cdecl/linux_fb_decl.c
ffi-cdecl/linux_input_decl.c
ffi-cdecl/lodepng_decl.c
ffi-cdecl/mupdf_decl.c
ffi-cdecl/mxcfb_kindle_decl.c
ffi-cdecl/mxcfb_kobo_decl.c
ffi-cdecl/posix_decl.c
ffi-cdecl/pthread_cdecl.c
ffi-cdecl/turbojpeg_decl.c
ffi/framebuffer_mxcfb.lua
ffi/mupdf.lua
ffi/mupdf_h.lua
ffi/mxcfb_kindle_h.lua
mupdf.patch
wrap-mupdf.h

... Including MUPDF, DVJU & LuaJIT, so, err, here be dragons? ^^.
(-> Travis will be my friend on this one ^^)
* Also a minor tweak to yesterday's update mode tweaks, including a fix for untracked update_marker (0 is invalid, which is potentially harmless, but not that great, and at the very least had rendered WAIT_FOR_SUBMISSION useless on Kindles).

Massive bump of 3rd-party libs

---

mupdf.patch

and fix font filenames in urw.

Revert pulling droid fonts from mupdf resources

---

cre.cpp
mupdf.patch

need to run "make fetchthirdparty" to apply mupdf.patch

Update for font change

---

Makefile.defs
ffi/framebuffer_mxcfb.lua

Fixes potential USBMS issues on Kobos.
Thanks to tshering for pointing this out (cf. http://www.mobileread.com/forums/showpost.php?p=3163948&postcount=2358 and the next few messages for the gory details).

Some rather critical FT fixes

---

.travis.yml
Makefile
tar-0001-fix-build-failure.patch

This should fix the vagrant build error in #1009

build: fix tar build

---

cre.cpp

Add method to retrieve information about book e.q. title, author, series, language.

Add Statistic plugin (#1581 Amount of hours spent on a book)

---

.gitignore
.gitmodules
Makefile
Makefile.defs
ffi/mupdf.lua
ffi/util.lua
mupdf.patch

now mupdf supports the traditional PLZIP encryption and a much stronger AES encryption for ZIP documents.

patch mupdf to add support of password protected zip file

---

.travis.yml

See https://github.com/Olivine-Labs/busted/issues/459.

update to busted-2.0.rc11-0

---

ffi-cdecl/mupdf_decl.c
ffi/mupdf.lua
ffi/mupdf_h.lua

Add getMetadata feature to provide info about pdf

#1710 FR: Add support of statistics plugin for pdf. Base part

---

.gitmodules
Makefile
Makefile.defs
thirdparty/lua-Spore/CMakeLists.txt
thirdparty/mupdf/CMakeLists.txt

also convert lua-Spore buld to cmake

build: remove cmake stamp files to force update target files

---

.gitmodules
Makefile
Makefile.defs
thirdparty/leptonica/CMakeLists.txt
thirdparty/libk2pdfopt/CMakeLists.txt
thirdparty/tesseract/CMakeLists.txt

This PR depends on https://github.com/koreader/libk2pdfopt/pull/25

migrate libk2pdfopt to CMake 

---

Makefile.defs

this fixes https://github.com/koreader/koreader/issues/1779

build: error out on invalid target

---

ffi-cdecl/posix_decl.c
ffi/posix_h.lua
ffi/util.lua

This change is part of a new feature proposal, discussed @ koreader/koreader#1838

Add basename and dirname functions in util.lua

---

ffi/util.lua

Sorry for the trouble, I should learn more about lua before making any changes.

Revert last change to add util.getsec()

---

Makefile.defs
Makefile.third
ffi/framebuffer_mxcfb.lua
thirdparty/leptonica/CMakeLists.txt
thirdparty/leptonica/leptonica-1.72-fmemopen-compat-symbol.patch
thirdparty/leptonica/leptonica-1.74-fmemopen-compat-symbol.patch
thirdparty/sqlite/CMakeLists.txt

Related to base#421 & koreader#2005

Some assorted tweaks

---

thirdparty/libk2pdfopt/CMakeLists.txt

This should fix strange behaviors like non-optimal reflowing (quality degeneration) and wrong auto cropping for PDF files.

update crengine & 	fix libk2pdfopt

---

input.c

fix https://github.com/koreader/koreader/issues/2036

pocketbook(fix): ignore SIGINT on auto shutdown

---

ffi/framebuffer_mxcfb.lua
thirdparty/freetype2/CMakeLists.txt
thirdparty/libjpeg-turbo/CMakeLists.txt
thirdparty/libpng/CMakeLists.txt
thirdparty/lodepng/CMakeLists.txt
thirdparty/openssl/CMakeLists.txt
thirdparty/sqlite/CMakeLists.txt

Should be trivial enough.
Also set things up for Oasis & KT3 support.

Bump a bunch of third-party libs

---

thirdparty/freetype2/CMakeLists.txt

Fixes OS X build (regression).

Bump FT to a few commits after 2.6.4

---

Makefile
Makefile.defs
Makefile.third
input.c
thirdparty/lj-wpaclient/CMakeLists.txt

* get ready for the new network manager
* fixed a bug that can cause touch screen to lock up after a reader crash

pull in lj-wpaclient library

---

thirdparty/turbo/CMakeLists.txt
thirdparty/turbo/turbo.patch

As we have discussed in issue #2194, I would like to give turbo another shot.
Since we do not enable turbo by default, this change would be pretty safe.

Use latest turbo @ 5234825fd09bb0401aab6e2603f9f6d1aa83350b

---

Makefile.defs
djvu.c

Fix https://github.com/koreader/koreader/issues/2242

Fix djvu TOC page number parsing

---

ffi/pic.lua

linked with https://github.com/koreader/koreader/pull/2346

Add function openJPGDocumentFromMem

---

cre.cpp

Needed for 2 things i'll submit PR for to the koreader repository in a few days:
`CreDocument:hasXPointer(xp)` : will be used by `ReaderLink:onGotoLink(link)` to check that the link is actually an internal link. Currently, when clicking on an invalid or external link, we jump to page 1 of document.
(Mostly copied & pasted from `getPosFromXPointer()` , which I could have used as it returns 0 if the link is not internal, but it also returns 0 if the link is on the top line of the document.)
`CreDocument:getImageFromPosition(pos)` : will be used by `ReaderHighlight:onHold(arg,ges) `to check if we are holding on an image before calling `getWordFromPosition()`. (Currently, if holding on an image, you get a text with the last word before the image + the first word after the image.) That will …

Added hasXPointer() and getImageDataFromPosition()

---

cre.cpp

See koreader issue #2412
crengine bumped, including fix for segfault when hold on list items.

Fix for links clickable out of bounds

---

ffi/zipwriter.lua

Needed for wikipedia epub generation

New zipwriter module (wrapping zlib via ffi)

---

Makefile.defs

Fixes https://github.com/koreader/koreader/issues/2647

Fix Android build

---

cre.cpp

Also added on-the-fly SVG to PNG conversion (with zoom) to getImageFromPosition for high-quality display in ImageViewer widget.
See https://github.com/koreader/koreader/issues/2668

Bump crengine for SVG image support

---

Makefile.third
thirdparty/sdcv/CMakeLists.txt

update sdcv to support non-fuzzy-fallback option

---

.ci/build_script.sh
cre.cpp

See https://github.com/koreader/crengine/pull/74
crengine bumped, which also includes "css related improvement" commit

crengine: return description and keywords metadata

---

Makefile.defs
Makefile.third
thirdparty/sdcv/CMakeLists.txt

See discussion in https://github.com/koreader/koreader/issues/2951#issuecomment-313316115

thirdparty: change sdcv source to upstream

---

Makefile.defs
Makefile.third
thirdparty/sdcv/CMakeLists.txt

Reverts koreader/koreader-base#496

Revert "thirdparty: change sdcv source to upstream"

---

ffi/MD5.lua
ffi/SDL2_0.lua
ffi/framebuffer.lua
ffi/png.lua
ffi/util.lua
ffi/zipwriter.lua

Also fix doc generation.
Part two will be these simple lines in doc/config.ld a front PR:
```
file = {
'../frontend',
'../base/ffi',
}
```
And presto, some base docs. :-)

Add EMULATE_READER_DPI

---

.travis.yml

#510 passed even though it should've failed.

[fix] Travis build for NDK 15

---

ffi/koptcontext.lua
spec/unit/koptcontext_spec.lua
spec/unit/png_spec.lua

Luacheck fixes

---

.travis.yml
Makefile.defs
thirdparty/luajit/CMakeLists.txt

@poire-z Any thoughts on the name?

Add KODEBUG environment variable to trigger debug build

---

.travis.yml
ffi/koptcontext.lua

* No more allowed failure for shellchecks
* Fix up final `koptcontext.lua`

[CI] Enable LuaCheck

---

Makefile
Makefile.defs

I slightly missed the ball. The method is sound, but we don't need anything special in base.
Reverts koreader/koreader-base#540

Revert "Reintroduce base git-rev"

---

djvu.c

See https://github.com/koreader/koreader-base/pull/546#issuecomment-336674759 and around.

djvu: allow for color rendering

---

ffi/pic.lua

This should fix incorrect rendering color in goodreads plugin picture (thumbnail)
https://github.com/koreader/koreader/blob/master/plugins/goodreads.koplugin/goodreadsbook.lua#L198

Change JPG rendering to RGB in openJPGDocumentFromMem

---

thirdparty/lpeg/CMakeLists.txt

Minor bug fix release. See:
* http://lua-users.org/lists/lua-l/2017-01/msg00135.html
* http://lua-users.org/lists/lua-l/2017-01/msg00163.html

Bump lpeg to 1.0.1

---

ffi/framebuffer.lua

References https://github.com/koreader/koreader/pull/3392

[chore] framebuffer:setViewport ability to set multiple times

---

thirdparty/libk2pdfopt/CMakeLists.txt

Includes:
* implement pixmap_to_bmp https://github.com/koreader/libk2pdfopt/pull/28
* Leptonica 1.73+ support https://github.com/koreader/libk2pdfopt/pull/29

Bump libk2pdfopt

---

.travis.yml

[CI] SHELLCHECKS first

---

thirdparty/lj-wpaclient/CMakeLists.txt

* [fix] filter out more bad lines in wpa scan result (https://github.com/koreader/lj-wpaclient/pull/3)

[build] Bump lj-wpjaclient

---

.ci/build_script.sh

The chmod command started mysteriously failing a few days ago.
This should fix it.

[CI, fix] Kobo, Kindle & Pocketbook

---

ffi-cdecl/mupdf_decl.c
ffi/mupdf.lua
ffi/mupdf_h.lua
thirdparty/mupdf/external_fonts.patch

Fixes https://github.com/koreader/koreader/issues/3564

MuPDF HTML CJK font fix

---

ffi/zipwriter.lua

We won't need to compress images (already compressed ones like GIF, JPG, PNG) in wikipedia epub (just a small optimisation to space some cpu cycles, when saving as epub, and when reading with crengine).

ZipWriter: allow for storing files uncompressed

---

thirdparty/luasocket/CMakeLists.txt

Fixes a redirect-related issue[1] and other assorted issues.
[1] https://github.com/diegonehab/luasocket/commit/5b4b9158799293eeaf8439d40a7845b5b0a5e125

Bump luasocket

---

cre.cpp

See details in https://github.com/koreader/koreader/pull/3656 and https://github.com/koreader/crengine/pull/94.
Don't use `rc.height()` for the height to search in, as it may be small for some pages when there is a page-break (it would then be the height of the rendered text only) - and we would only search in this area of the other page, missing occurences in the visible but not searched other area.
Better to use the view height.
Don't use `+1` or `-1` with `rc.bottom` or `rc.top`, as there may be no node at this +/-1 location, and search would abort. So, use them directly.
Still, even when using them directly, we may miss some words at edges of page, and even some words not at edge of pages, but included in a node/tag that is itself at edge of page or spanning previous or
next page.
The …

cre.findText(): fix inconsistencies in results

---

cre.cpp

Bumps crengine for the new `getHRef(a_xpointer)` methods, see https://github.com/koreader/crengine/pull/96
Follow up to #597.
Should still have no impact on current code that does not use it.
I just want it in a nightly so I can test on my kobo for some time a followup to https://github.com/koreader/koreader/pull/3202 (_I would also have liked to have that when back from link, to again see where we were before jumping to link, but that's more complicated_)
I shall use that like this:
```lua
-        local link = self.ui.document:getLinkFromPosition(ges.pos)
-        if link ~= "" then
-            return link
+        local link_xpointer, a_xpointer = self.ui.document:getLinkFromPosition(ges.pos)
+
+        if a_xpointer and not self:isXpointerCoherent(a_xpointer) then
+            -- On …
```

getLinkFromPosition(), getPageLinks(): better xpointer for link origin

---

cre.cpp

See details in https://github.com/koreader/crengine/pull/97

cre.initCache(): allow toggling crengine cache compression

---

cre.cpp

Depends on a crengine change I have yet to turn into a PR.
References https://github.com/koreader/koreader/issues/2686

[fix] more font sizes for crengine

---

cre.cpp

Bump crengine for cache re-use fix and warnings when cache sizes reached.
Full details in https://github.com/koreader/crengine/pull/100

cre: Allow for increasing some crengine cache sizes

---

ffi/mupdf.lua

See https://github.com/koreader/koreader/issues/3705#issuecomment-369932761

[fix] ffi/mupdf: throw error if no pages in file

---

ffi/framebuffer.lua
ffi/framebuffer_SDL2_0.lua

References https://github.com/koreader/koreader/issues/3713

[feat] SDL2: framebuffer:setWindowTitle()

---

Makefile.defs

Reverts koreader/koreader-base#608

Revert "[build] Add -fsanitize=undefined to debug flags"

---

thirdparty/libffi/CMakeLists.txt

prevent error behind firewall

---

ffi/filechooser.lua
ffi/filechooser_gtk-3.lua
ffi/gtk-3_h.lua
ffi/input_SDL2_0.lua

Not much to say here. It opens a Gtk3 filechooser when available.

[feat] FFI: add FileChooser Gtk3 backend

---

.travis.yml

See https://github.com/koreader/koreader-base/pull/640#issuecomment-379771447

[CI] .travis.yml: update Docker images

---

ffi/SDL2_0.lua
ffi/SDL2_0_h.lua
ffi/framebuffer_SDL2_0.lua

References https://github.com/koreader/koreader/issues/3858
Edit: a couple of screenshots of this in action using one of the available icons (probably the worst one for this purpose since it doesn't scale down very recognizably).

[feat] SDL2: support SDL_SetWindowIcon

---

cre.cpp

Includes:
- table captions: fix link, highlighting and possible segfault https://github.com/koreader/crengine/pull/156
- update French.pattern https://github.com/koreader/crengine/pull/157
- `ldomXPointer::toPoint()`: add optional `use_getRectEx` param https://github.com/koreader/crengine/pull/158
`base/cre.cpp`: make `getPosFromXPointer()` uses `use_getRectEx=true` for better coordinates accuracy: see details in https://github.com/koreader/crengine/pull/158

bump crengine: various fixes

---

thirdparty/libjpeg-turbo/CMakeLists.txt

https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/1.5.3

[build] bump libjpeg-turbo to 1.5.3

---

Makefile
Makefile.defs
Makefile.third
thirdparty/dropbear/CMakeLists.txt
thirdparty/dropbear/dropbear-2018.76-kindle-nopasswd-hack.patch
thirdparty/dropbear/dropbear-2018.76-kindle-pubkey-gen-hack.patch
thirdparty/dropbear/dropbear-2018.76-kindle-pubkey-hack.patch
thirdparty/dropbear/dropbear-2018.76-kindle-pubkey2-gen-hack.patch

Add dropbear as an ssh server

---

cre.cpp
thirdparty/mupdf/external_fonts.patch

Depends on [KO#3942](https://github.com/koreader/koreader/pull/3942)

Update reference to NotoSansCJK filename

---

.ci/test_script.sh
ffi-cdecl/mupdf_decl.c
ffi/SDL1_2.lua
ffi/SDL2_0.lua
ffi/blitbuffer.lua
ffi/framebuffer.lua
ffi/framebuffer_SDL1_2.lua
ffi/framebuffer_android.lua
ffi/framebuffer_einkfb.lua
ffi/framebuffer_linux.lua
ffi/framebuffer_mxcfb.lua
ffi/input_android.lua
ffi/kobolight.lua
ffi/koptcontext.lua
ffi/mupdf.lua
ffi/mupdf_h.lua
ffi/util.lua

Needs testing, I don't have the device ;).
Based on @cramoisi's logs from [KO#3130](https://github.com/koreader/koreader/issues/3130).

Proper REAGL handling on Kobo Aura

---

thirdparty/lua-Spore/CMakeLists.txt

Includes:
- text formatting: fix leading spaces issues https://github.com/koreader/crengine/pull/204
- new English US & GB hyph patterns https://github.com/koreader/crengine/pull/206
(small bump to have nightly builds with individual changes in case we need to bissect some side effects with the recent and coming rendering fixes)

bump crengine: text formatting: fix leading spaces issues

---

cre.cpp

Update reference to default english hyph dict

---

thirdparty/openssl/CMakeLists.txt
thirdparty/openssl/openssl-android-makedepend.patch

I'm starting to seriously hate OpenSSL's build system. :D.

Fix nightwatcher Android builds

---

ffi/framebuffer_mxcfb.lua

Totally not fixing the dumbest thinko ever.

---

Makefile
Makefile.defs
Makefile.third
thirdparty/fbink/CMakeLists.txt

Letting the CI do the work to check if I did this right ;p.

Bundle FBInk for visual feedback in Kobo startup scripts

---

thirdparty/fbink/CMakeLists.txt
thirdparty/libpng/CMakeLists.txt

Bump a few thirdparty libs

---

cre.cpp

Details in https://github.com/koreader/crengine/pull/222
cre.cpp: process hyphenated words char by char to get the word box (instead of using wrong word width)

bump crengine: fix two highlight issues

---

thirdparty/glib/CMakeLists.txt

Fixed Ubuntu Touch, broke App Image ;D
Ubuntu hates me. (and the feeling is mutual, so, hey ;D).

Unbreak AppImage nighlties

---

thirdparty/fbink/CMakeLists.txt

Fix a graphical glitch with progress bars on legacy Kindles

Bump FBInk to 1.6.1

---

ffi/framebuffer_mxcfb.lua

Just to make it match how we handle that on other devices

Minor cosmetic tweak

---

ffi/framebuffer_mxcfb.lua

Because seeing those nonsensical negative regions in logs was starting to annoy me ;).

Minor mxcfb debug logging tweak

---

cre.cpp

Bump crengine with changes from https://github.com/koreader/crengine/pull/236
Adds a few function to cre.cpp to make use of that. See individual commit messages.
(I let the links & footnote stuff for some other base + frontend PRs after these ones are merged to keep things clearer).
(Needs the crengine merge and bump, making this PR early for easier review)

cre: adds HTML and CSS extraction functions, alternate highlight method, bump crengine

---

thirdparty/harfbuzz/CMakeLists.txt

[fix] HarfBuzz Android build with newer libtool

---

cre.cpp

bump crengine, which includes:
- Avoid uneeded re-rendering on load when with full status bar https://github.com/koreader/crengine/pull/238
- Update french hyphenation pattern https://github.com/koreader/crengine/pull/239
- https://github.com/koreader/crengine/pull/240 :
- Fix border-collapse on table cells in some cases
- Fix line-height inheritance when no unit
- Fix: don't ignore space following an image
- Fix: ignore occasional space at start of line
- Fix possible segfault when viewing HTML
- Fix and extend support of vertical-align
Also update footnote detection algorithm related to vertical-align to the crengine changes (which makes it less radical: to catch footnotes with `vertical-align: 30%`, we need to trigger it when there is a non-zero vertical, as we don't have access to …

bump crengine: fix vertical-align and others

---

Makefile.defs
Makefile.third
thirdparty/libjpeg-turbo/CMakeLists.txt
thirdparty/openssl/CMakeLists.txt

Hopefully unfucks the situation on Android...

Properly disable ASM on targets where we can't use SIMD instructions

---

ffi-cdecl/include/mxcfb-kindle.h
ffi-cdecl/mxcfb_kindle_decl.c
ffi/framebuffer_mxcfb.lua
ffi/mxcfb_kindle_h.lua

At least as far as the epdc driver is concerned ;).

PW4 support

---

ffi/framebuffer_linux.lua

We'll probably need it on the Kobo Forma

Export HW fb rotation

---

.ci/build_script.sh
.travis.yml
Makefile.defs

[build, fix] Support PocketBook TC in path

---

thirdparty/harfbuzz/CMakeLists.txt
thirdparty/openssl/CMakeLists.txt

* OpenSSL 1.0.2q
* HarfBuzz 2.1.3

Bump a few thurd-party libs

---

Makefile.third

Fixes https://github.com/koreader/koreader/issues/4375. (the build error w/ luarocks-5.1 not available).
Needs review because I'm dumb 👍

add support for luarocks3 from brew

---

ffi/framebuffer_mxcfb.lua

I'll be in the corner, laughing hysterically.
*facepalm*

Fix Kobo Mk7 detection

---

ffi/framebuffer_linux.lua

Fix https://github.com/koreader/koreader/issues/4416

Add support for PocketBook Touch HD Plus

---

thirdparty/fbink/CMakeLists.txt
thirdparty/glib/CMakeLists.txt
thirdparty/glib/glib-2.58.2-android-linux-syscalls.patch
thirdparty/harfbuzz/CMakeLists.txt
thirdparty/libk2pdfopt/CMakeLists.txt
thirdparty/sqlite/CMakeLists.txt

With a bit of luck HB will be a go... Otherwise, next version ;).

Bump third-party libraries

---

ffi/framebuffer_linux.lua

Mandatory status dump for everyone, so we get useful crash.logs straight away ;).
Plus a tentative fix for https://github.com/koreader/koreader/issues/4447
But I'd *really* like to get logs, because depending on those, I might be able to simply do away with the whole ugly side of the branch ;).

More PB fb shenanigans!

---

ffi/framebuffer_linux.lua

Hopefully for good, this time...

Even more PB fb setup fun!

---

.ci/android_install.sh
.travis.yml
Makefile
Makefile.defs

See <https://github.com/koreader/koreader/issues/4471>.

[Android, build] Deprecate NDK<15

---

thirdparty/fbink/CMakeLists.txt
thirdparty/glib/CMakeLists.txt
thirdparty/harfbuzz/CMakeLists.txt
thirdparty/luajit/CMakeLists.txt

* FBInk 1.10.1
* glib 2.58.3
* HarfBuzz 2.3.1
* LuaJIT (2019/01/10)

Bump a few third-party libraries

---

ffi/framebuffer_mxcfb.lua

Turns out, at least on the Touch, A2 is *really*, *really* bad ;D.
re https://github.com/koreader/koreader/issues/4518#issuecomment-461129739

Fix eggregious ghosting on older Kindles

---

cre.cpp

Adds missing getTextFromXPointers method. This is pretty much direct copy of getTextFromPositions.

Add getTextFromXPointers method

---

ffi/framebuffer_mxcfb.lua

It apparently doesn't behave like on Kobo...

Disable HW dithering on Kindle

---

ffi/framebuffer_mxcfb.lua

Actually kill HW dithering on Kindle for real ;).

---

Makefile
libxss-dummy.c

References <https://github.com/koreader/koreader/issues/4627>.

[fix, AppImage] Add libXss.so.1 dummy

---

ffi/util.lua

Make any future problems similar to https://github.com/koreader/koreader/issues/4627 show up in the log.

[chore] Log SDL loading error

---

Makefile
Makefile.third
thirdparty/fbink/CMakeLists.txt

Relevant to our interests: a progressbar rounding fix.
Also build & ship fbdepth on Kobo, for the upcoming great 8bpp switcheroo!

Bump FBInk to v1.11.0

---

cre.cpp

- consider links with only roman numerals (eg: `xiv`) as link to a footnote (1 to **10** roman numerals digix as I don't know how big these roman numbers can reasonably get for numbers with 500 footnotes)
- when extending footnote, also stop when meeting `<a name="someId">` as `name=` works as well as `id=` when following links.

cre: tweak footnote popup detection

---

ffi/framebuffer.lua

was: koreader/koreader-base#807

decouple reader setting from framebuffer

---

thirdparty/fbink/CMakeLists.txt
thirdparty/tar/CMakeLists.txt

* FBInk 1.12.0 (fbdepth tweaks, plus, it'll actually clone properly).
* GNU Tar 1.32

A couple third-party bumps

---

thirdparty/dropbear/CMakeLists.txt
thirdparty/zlib/CMakeLists.txt

IIRC, not the first time there's been a temporary failure there...

Switch zlib to a mirror

---

thirdparty/fbink/CMakeLists.txt

Fix rotation issues w/ KSM @ 8bpp (re: https://github.com/koreader/koreader/issues/4752)

Bump FBInk to v1.12.1

---

ffi/blitbuffer.lua

That paints a border on the inside, instead of the outside.
Doesn't support radius, because maths (and, also, I didn't need it to :D).

Add a paintInnerBorder method

---

.ci/before_install.sh
.ci/emulator_install.sh
.ci/lint_install.sh
.travis.yml
utils/pdfattach

This PR is a minor WIP to see about side effects, but should mostly be uneventful.

[CI] Switch Travis to Ubuntu Xenial (16.04)

---

cre.cpp

Includes https://github.com/koreader/crengine/pull/270:
- docToWindowPoint(): adds fitToPage parameter
- 2-pages mode: add and fix some functions
- 2-pages mode: tweak middle margin sizing
- Text rendering: fix words stuck when hyphenating on italic
cre.cpp:
- add a few functions useful with 2-pages mode
- fix docToWindowRect() to get truncated segments for lines split onto 2 pages, for highlights and links

bump crengine: 2-pages view tweaks, fix hyphenating on italic

---

Makefile.defs
Makefile.third
thirdparty/zlib/CMakeLists.txt

[build] Move Android ZLIB_LDFLAGS to thirdparty/zlib

---

thirdparty/kpvcrlib/CMakeLists.txt

[chore] CMake kpvcrlib convert remaining tabs to four spaces

---

thirdparty/fbink/CMakeLists.txt
thirdparty/harfbuzz/CMakeLists.txt
thirdparty/libk2pdfopt/CMakeLists.txt
thirdparty/libpng/CMakeLists.txt

• HarfBuzz 2.4.0
• k2pfopt to pickup https://github.com/koreader/libk2pdfopt/pull/35
• libpng 1.6.37
• FBInk 1.15.0

Bump a few third party libraries

---

ffi/framebuffer.lua
spec/unit/framebuffer_spec.lua

fix incorrect merge with master from #843

---

.ci/emulator_install.sh
.circleci/config.yml

Closes https://github.com/koreader/koreader-base/issues/905

[CI] Bump busted to v2.0.rc13-0

---

Makefile
spec/unit/blitbuffer_spec.lua
spec/unit/common_spec.lua
spec/unit/ffi_wrapper.lua
spec/unit/freetype_spec.lua
spec/unit/md5_spec.lua
spec/unit/png_spec.lua

Cf. https://github.com/koreader/koreader/pull/4972

[spec] Better insulation

---

Makefile
blitbuffer.c

Now that it's feature-complete for BB8 targets, and generally faster and
less finicky.

Build the C BB on Kindle, Kobo & PB

---

Makefile.defs

See https://github.com/koreader/koreader/issues/4830

Remove -march=native from Debian HOST_ARCH

---

ffi-cdecl/include/mxcfb-kindle.h
ffi/framebuffer_mxcfb.lua
ffi/mxcfb_kindle_h.lua
thirdparty/fbink/CMakeLists.txt

Same HW platform as the PW4, except with a crappier screen.

Pave the way for KT4 support

---

ffi/framebuffer_android.lua

requires https://github.com/koreader/android-luajit-launcher/pull/146

add full support for eink refreshes on compatible devices(ntx)

---

thirdparty/lpeg/CMakeLists.txt

Closes https://github.com/koreader/koreader-base/issues/908

lpeg 1.0.2

---

ffi/framebuffer_android.lua

- use AUTO waveform instead of REAGL (auto will choose regal on compatible devices)
- diff between freescale devices that require all eink updates and those that don't

enhancements for android eink devices

---

toolchain/Makefile

to build with latest api and build-tools.
May need changes on the build machine.

update android sdk tools

---

ffi/framebuffer_mxcfb.lua

Because it's apparently blatantly lying about supporting the fancy
nightmode waveforms...
Fix https://github.com/koreader/koreader/issues/5076

Fix nightmode on the KT4

---

.circleci/config.yml
.travis.yml

See https://github.com/koreader/virdevenv/pull/40

[CI] Switch to koreader/koandroid:0.3 image

---

ffi/framebuffer_android.lua

Based on https://github.com/koreader/koreader/issues/5056#issuecomment-502340079, https://github.com/koreader/koreader/issues/5056#issuecomment-502370215 and https://github.com/koreader/koreader/issues/5056#issuecomment-508811865

some tolino/nook waveform fixes

---

thirdparty/fbink/CMakeLists.txt

Some potentially minor performance improvements, as well as rendering fixes on legacy Kindles, but nothing critical ;).

Update FBInk to 1.17.0

---

blitbuffer.c

Potentially very slightly faster on decent CPUs (branch prediciton?).

Switch back to if ladders for inner loops

---

ffi/input_android.lua

Requires https://github.com/koreader/android-luajit-launcher/pull/162

do not consume media keys, consume volume keys based on user settings

---

ffi/SDL2_0.lua
ffi/util.lua

As proposed but forgotten to add in <https://github.com/koreader/koreader-base/pull/873#issuecomment-486156245>.
Fixes <https://github.com/koreader/koreader/issues/5122>.

[fix] Add libSDL2-2.0.so.0 to SDL2 ffiLoadCandidates

---

thirdparty/luasec/CMakeLists.txt

https://github.com/brunoos/luasec/releases/tag/luasec-0.8.1
Fixes a memory leak: https://github.com/brunoos/luasec/commit/dcd385e615854093edaabe6d6953923c7ff1fb9b

luasec 0.8.1

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/2.6.1

thirdparty/harfbuzz 2.6.1

---

thirdparty/harfbuzz/CMakeLists.txt

Fixes https://github.com/koreader/koreader-base/issues/958.

thirdparty/harfbuzz 2.6.1 for PocketBook

---

ffi/lodepng_h.lua
thirdparty/fbink/CMakeLists.txt
thirdparty/lodepng/CMakeLists.txt

* LodePNG 20190901
* FBInk 1.19.0

Minor third-party bumps

---

thirdparty/fbink/CMakeLists.txt

Might be using it for fun later ;p.

Build FBInk with OpenType support

---

ffi-cdecl/rtc_cdecl.c
ffi/rtc_h.lua

(re: https://github.com/koreader/koreader/pull/5335)

Add some more rtc stuff

---

thirdparty/djvulibre/CMakeLists.txt

One minuscule bug fix in the string class.

Bump thirdparty/djvulibre to current master

---

ffi/rtc.lua

Fixes <https://github.com/koreader/koreader/issues/5376>.

[fix] RTC: Compare time values in the right timezone

---

thirdparty/fbink/CMakeLists.txt

Update to FBInk v1.20.0

---

cre.cpp

Includes https://github.com/koreader/crengine/pull/310
- Adds tinyNodeCollection::getStatistics()
- epubfmt.cpp: cleanup indentation and small optimisation
- Add more progress callback events
- Optimisation: avoid re-init for EPUBs with embedded fonts
- Fix: don't draw border when border-color: transparent
- CSS: ignore 'inherit' inside font-family
cre.cpp:
- Adds setCallback(), and some infrastructure to handle callback events.
- Adds getStatistics()

bump crengine: get progress events via frontend callback

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/2.6.2

thirdparty/harfbuzz 2.6.2

---

thirdparty/fribidi/CMakeLists.txt

https://github.com/fribidi/fribidi/releases/tag/v1.0.7

thirdparty/fribidi 1.0.7

---

thirdparty/fribidi/CMakeLists.txt
thirdparty/fribidi/fribidi-pr115.patch
thirdparty/leptonica/CMakeLists.txt

Possibly not enough for a full build, untested ;).

macOS build fixes

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/2.6.3

thirdparty/harfbuzz 2.6.3

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/2.6.4

thirdparty/harfbuzz 2.6.4

---

Makefile.defs

Cf. <https://github.com/koreader/koreader-base/pull/1003#issuecomment-548260873>.

[fix] LuaRocks 2 and 3 compat

---

xtext.cpp

Includes https://github.com/koreader/crengine/pull/318
- Fonts: round FT metrics instead of floor'ing them
- Fonts: switch to no hinting when native hinting fails
- Fonts: fix issue with Harfbuzz fallback font drawing
- Text: split measuring and word drawing by unicode script
- Page splitting: fix small memory leak
- Fix "background-color: black" ignored on inline elements
- Fix decoding of recent MOBI files
- Hardcoded elements list: add <font>
xtext.cpp: small cleanup (no longer "no more" :), no logic change, adapted to use the same macro used in 1st crengine commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1014)

bump crengine: round FT metrics, split text drawing by script

---

ffi/util.lua

Figured I'd do base after frontend ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1015)

Minor ffi.util cleanups

---

thirdparty/libffi/CMakeLists.txt

https://github.com/libffi/libffi/releases/tag/v3.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1017)

thirdparty/libffi v3.3

---

xtext.cpp

Includes https://github.com/koreader/crengine/pull/321:
- CSS: remove invalid and unused item in selector enum
- Fix possible crash with backward search
Also adds `XText.getParaDirection()` to help with cursor positionning in empty lines in RTL/bidi text (and have `XText.shapeLine()` return the `bidi_level` of each glyph, which _might_ additionally help with cursor positionning).
(edit: renamed `isParaDirectionRTL()` to `getParaDirection()` to stay coherent with existing `setDefaultParaDirection()`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1019)

bump crengine: fix possible crash with backward search

---

.circleci/config.yml

See <https://github.com/koreader/virdevenv/pull/45>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1024)

[CI] Switch to Clang 9.0.1

---

xtext.cpp

Cut & pasted from https://github.com/koreader/koreader/issues/5359#issuecomment-570490169:
> It looks like it's also the reason for my ellipsis when text is truncated to be on the wrong side:
A correlated reason for that is that, in xtext.cpp, when substituting the text char with an ellipsis, I keep the original chat bidi type and level. So, if the ellipsis is replacing a letter it would stay near the previous letter - but if it is replacing a space, it may be sent away to start or end of string by the Unicode bidi rules L1 (or I1, I2, L1 to L4...).
And when adding an ellipsis to a TextBoxWidget, we always add it on a breakable character (so, a space), so the issue is always there - unlike for TextWidget where we drop the libunibreak rules and can add the ellipsis at any place.
For this …

xtext: fix truncation ellipsis position in bidi text

---

.circleci/config.yml
.travis.yml

See https://github.com/koreader/virdevenv/pull/46 and https://github.com/koreader/koreader-base/pull/1025#issuecomment-570556188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1026)

[chore, CI] Update to latest Docker images for ragel

---

ffi/framebuffer_android.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1029)

Fix partial updates in landscape orientation

---

xtext.cpp

To get (as a single UTF-8 string) the segment of text.
Needed for https://github.com/koreader/koreader/pull/5775.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1031)

xtext: adds getText(start, end)

---

thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1035)

Update SQLite to 3.31.1

---

.circleci/config.yml
.travis.yml

Cf. https://gitlab.com/koreader/nightly-builds/commit/24806cf9ae06ddbefcbb43041050f81852e82b52 and https://github.com/koreader/virdevenv/issues/25#issuecomment-570903643
Also remove most of the stuff from Travis to make it potentially actually useful rather than just duplicate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1040)

[chore] Switch Sony PRSTUX to kobase Docker image

---

thirdparty/mupdf/CMakeLists.txt
thirdparty/mupdf/tar-fixes.patch

Thanks to @q3cpma.
Long name records and a few more fixes.
Closes <https://github.com/koreader/koreader-base/issues/1041>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1042)

thirdparty: Add MuPDF tar patch

---

cre.cpp

Includes https://github.com/koreader/crengine/pull/328 :
- Fix shifted native selection/internal bookmarks in legacy mode
- Fix drawing of inline-block taller than page height
- (Upstream) createXPointer/toString: normalized xpointers
- toStringUsingNames(): rename to toStringV2()
- DOM_VERSION_WITH_NORMALIZED_XPOINTERS 20200223
- CSS/List items: skip boxing elements when walking
- CSS: parse pseudoclass nth_child(3n+2)
- toStringV2(): output [1] when first but not single
- Tables: complete incomplete tables
- Store gDOMVersionRequested in cache file header
- Cache: increase Rects cache size
cre.cpp: adds `getDomVersionWithNormalizedXPointers()` and `getNormalizedXPointer(xpv1)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

bump crengine: normalized xpointers, complete incomplete tables

---

.github/workflows/build.yml

That way it should show. See <https://github.com/koreader/koreader-base/pull/1052> and <https://github.com/koreader/koreader-base/pull/1054#issuecomment-590272286>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1058)

[CI] Run action on PR

---

thirdparty/curl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1059)

Update cURL to 7.69.0

---

Makefile.defs

Apparently >= is hard?
(re #1053).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1060)

Get rid of GNUism in the awk call

---

thirdparty/turbo/CMakeLists.txt

And stop shipping a useless CA bundle copy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1064)

Update turbo to v2.1.3

---

thirdparty/curl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1066)

Update cURL to 7.69.1

---

thirdparty/openssh/CMakeLists.txt
thirdparty/openssl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1068)

Update OpenSSL to 1.1.1e

---

cre.cpp

Includes https://github.com/koreader/crengine/pull/336 :
- Fix lvRect:isRectInside(rc) with 0-width or 0-height rect
- TOC: parse EPUB3 nav toc, fallback to spine when no toc
- Parse and cache various hardcopy page list maps
- epub.css: hide EPUB3 <span epub:type="pagebreak"> content
cre.cpp: add a few PageMap helper functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1070)

bump crengine: support for EPUB3 nav toc and page maps

---

Makefile.third
thirdparty/djvulibre/CMakeLists.txt

See <https://github.com/koreader/koreader/issues/4512#issuecomment-605517909>.
Follow-up to <https://github.com/koreader/koreader-base/pull/1071>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1072)

Minor win32 fix for libjpeg-turbo

---

thirdparty/openssl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1073)

Update to OpenSSL 1.1.1f

---

thirdparty/utf8proc/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1079)

Bump utf8proc to 2.5.0

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/2.6.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1084)

thirdparty/harfbuzz 2.6.5

---

thirdparty/openssl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1085)

Update to OpenSSL 1.1.1g

---

thirdparty/dropbear/CMakeLists.txt

Fixes <https://github.com/koreader/koreader-base/issues/1086>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1087)

thirdparty/dropbear: Change URL to Debian mirror

---

.gitignore
thirdparty/curl/CMakeLists.txt
thirdparty/fbink/CMakeLists.txt

* FBInk 1.22.1
* cURL 7.70.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1092)

Minor third-party updates

---

thirdparty/freetype2/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1098)

Update to FreeType 2.10.2

---

thirdparty/harfbuzz/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1100)

Update to HarfBuzz 2.6.6

---

thirdparty/evernote-sdk-lua/CMakeLists.txt

https://github.com/koreader/evernote-sdk-lua/pull/2#issuecomment-629818092
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1101)

Bump evernote-sdk-lua

---

cre.cpp

Includes https://github.com/koreader/crengine/pull/344 :
- Don't reset invisible BR to display: inline
- ldomTextCollector: handle inline-block/table as inline
- Avoid re-rendering on font hinting mode change
- List markers: fix positionning when floats involved
- GIF decoding: avoid uneeded abort on LZW table overflow
- Adds getUnknownEntities(), can help with debugging
- Don't check stylesheet hashes when loading from cache
- Hardcoded elements and attributes list: cleanup
- Full rendering: 2 small optimisations
- Strut confinning: deal with images earlier
- lvtextfm: some cleanup and reordering
cre.cpp:
- fix getPageFromXPointer() and getPosFromXPointer() to not fail on invisible nodes and work on the next visible node (so links whose target is display:none can work, …

bump crengine: various fixes, tweaks and cleanups

---

Makefile.defs
thirdparty/cmake_modules/CMakeCross.cmake

Re #1102
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1103)

Neuter pkg-config when cross-compiling

---

.luacheckrc
ffi/sha2.lua

pure lua SHA from https://github.com/Egor-Skriptunoff/pure_lua_SHA
See https://github.com/koreader/koreader/pull/6177#discussion_r430745355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1105)

add SHA functions

---

thirdparty/openssh/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1107)

Update to OpenSSH 8.3p1

---

thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1111)

Update to SQLite 3.32.2

---

thirdparty/lodepng/CMakeLists.txt
thirdparty/luajit/CMakeLists.txt

* LuaJIT (should be fairly tame)
* LuaFileSystem (ditto)
* LodePNG (ditto)
* CRe (for the ePub3 metadata stuff)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1115)

A few third party updates

---

thirdparty/libunibreak/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1116)

Update to libunibreak 4.3

---

ffi/input_android.lua

Requires https://github.com/koreader/android-luajit-launcher/pull/233
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1117)

android: ignore back button events

---

thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1118)

Update to SQLite 3.32.3

---

thirdparty/luasocket/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1124)

thirdparty/luasocket Bump to latest master

---

thirdparty/evernote-sdk-lua/CMakeLists.txt

https://github.com/koreader/evernote-sdk-lua/pull/4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1125)

Bump evernote-sdk-lua - add logging

---

thirdparty/libjpeg-turbo/CMakeLists.txt

<https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.0.5>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1126)

thirdparty/libjpeg-turbo 2.0.5

---

ffi/framebuffer.lua

depends on koreader/koreader#6309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1127)

framebuffer: simplify orientation

---

thirdparty/curl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1129)

Update cURL to 7.71.0

---

.circleci/config.yml

See <https://github.com/koreader/virdevenv/pull/52>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1131)

[CI] Use Clang 10

---

thirdparty/fribidi/CMakeLists.txt

No relevant changes. Just keeping up to date.
https://github.com/fribidi/fribidi/releases/tag/v1.0.10
https://github.com/fribidi/fribidi/compare/v1.0.9...v1.0.10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1136)

thirdparty/fribidi 1.0.10

---

ffi/framebuffer.lua

Take two, because I forgot to merge #1132 before an unrelated force-push :D.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1137)

Minor clarification on rotation constants and buffer rotation

---

cre.cpp

Includes:
- New German hyphenation patterns https://github.com/koreader/crengine/pull/356
- CSS: adds `text-align-last: -cr-right-if-not-first` private keywords https://github.com/koreader/crengine/pull/357
- CSS: adds `-cr-only-if: fb2-document`
- fb2.css: fix verses, minor cleanup
- FB2 footnotes: fix spacing between number and text
- ldomTextCollector: guess block boundaries better
- Text: fix read/write outside array bounds
- Text: fix read outside array bounds https://github.com/koreader/crengine/pull/358
- Fix crash when more than 64 nested elements
- Fix possible crash on book with embedded fonts load
- (Upstream) lvstsheet: avoid compilation warnings https://github.com/koreader/crengine/pull/359
- Strut confining: don't when there is no strut
- CSS: switch `-cr-hint` from enum to …

bump crengine: various fixes and FB2 tweaks

---

ffi/framebuffer.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1150)

Make dithering toggles more flexible

---

thirdparty/harfbuzz/CMakeLists.txt

<https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.0>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1152)

thirdparty/harfbuzz 2.7.0

---

ffi/SDL2_0.lua
ffi/framebuffer_SDL2_0.lua

Moves environment overrides to the frontend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1157)

sdl window position and size

---

ffi-cdecl/SDL2_0_decl.c
ffi/SDL2_0.lua
ffi/SDL2_0_h.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1158)

SDL: don't bypass X11 WM compositor

---

thirdparty/kobo-usbms/CMakeLists.txt

i18n \o/
Getting gettext to behave on Kobo has been... interesting >_<".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1170)

Update to KoboUSBMS v0.9.2

---

thirdparty/kobo-usbms/CMakeLists.txt

Implements time & battery tracking during a session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1172)

Update to KoboUSBMS v0.9.4

---

thirdparty/kobo-usbms/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1173)

Update to KoboUSBMS 0.9.5

---

thirdparty/harfbuzz/CMakeLists.txt

* Update to HarfBuzz 2.7.2 (https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.2)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1175)

Minor third-party bump

---

thirdparty/kobo-usbms/CMakeLists.txt

(Better handling of early failures)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1176)

Update to KoboUSBMS v0.9.6

---

thirdparty/kobo-usbms/CMakeLists.txt

New l10n, CJK support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1180)

Update to KoboUSBMS 0.9.7

---

ffi/framebuffer_mxcfb.lua

See #1171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1181)

PocketBook: use DU for fast updates

---

blitbuffer.c
ffi-cdecl/linux_fb_decl.c
ffi/blitbuffer.lua
ffi/framebuffer.lua
ffi/framebuffer_linux.lua
ffi/framebuffer_mxcfb.lua
ffi/linux_fb_h.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1194)

linuxfb: Refactor and remove kludges, add support for HW rotation.

---

ffi/blitbuffer.lua

This is necessary even with CBB on, for Lua fallbacks.
(maybe) fixes https://github.com/koreader/koreader/issues/6736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1205)

blitbuffer: Always enable JIT workaround

---

ffi/koptcontext.lua

One variable was never freed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1207)

Fix memory leak in panel zoom

---

thirdparty/luajit/CMakeLists.txt

Fixes a nasty issue, possibly related to the recent CI weirdness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1216)

Bump LuaJIT

---

Makefile

Missed in 32af1b8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1219)

Fix missing LUA_LJ_SQLITE dep

---

thirdparty/freetype2/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1222)

Update to FreeType 2.10.4

---

ffi/harfbuzz.lua

Fixes https://github.com/koreader/koreader/issues/6806
(to be verified)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1223)

harfbuzz: Don't crash on invalid language tags.

---

ffi/framebuffer_android.lua

Not a night mode fan, I guess.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1220)

android: don't blink to white while doing a HW rota on night mode

---

toolchain/Makefile

Required by https://github.com/koreader/android-luajit-launcher/pull/253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1230)

bump android build-tools and platform

---

thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1249)

Update to SQLite 3.34.0

---

Makefile
nnsvg.c
nnsvg.cpp
nnsvg.h

Will allow rendering SVG images in frontend. See https://github.com/koreader/koreader/pull/6937 https://github.com/koreader/koreader/pull/6937#issuecomment-738347035
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1250)

Adds libkoreader-nnsvg.so, Lua/C module wrapping NanoSVG

---

thirdparty/djvulibre/CMakeLists.txt

Once again very minor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1251)

thirdparty/djvulibre 3.5.28

---

Makefile
spec/unit/nnsvg_spec.lua

May fix https://github.com/koreader/koreader-base/pull/1250#issuecomment-739471075 and https://github.com/koreader/koreader-base/pull/1252#issuecomment-739388745
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1254)

libkoreader-nnsvg.so: fix build on Android and MacOS

---

Makefile.defs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1253)

osx: fix brew's luarocks

---

Makefile

Cf. <https://github.com/koreader/koreader/pull/6959#discussion_r537784223>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1255)

Stop building tar on Android

---

thirdparty/curl/CMakeLists.txt
thirdparty/luajit/CMakeLists.txt
thirdparty/luajit/koreader-luajit-makefile-tweaks.patch
thirdparty/luajit/koreader-luajit-verbose-build.patch
thirdparty/openssh/CMakeLists.txt
thirdparty/openssl/CMakeLists.txt

* LuaJIT (minor)
* cURL 7.74.0 (I'd somehow forgotten about 7.73.0 ^^).
* OpenSSL 1.1.1i
* OpenSSH 8.4p1 (again, forgot about it when it came out).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1256)

2020.12 bumps

---

Makefile.defs
thirdparty/leptonica/CMakeLists.txt
thirdparty/luajit/CMakeLists.txt
thirdparty/openssl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1239)

Debian: new arm64 target (aarch64)

---

thirdparty/zstd/CMakeLists.txt

(Hotfix for unaligned memory accesses)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1261)

Update to ZSTD 1.4.8

---

thirdparty/harfbuzz/CMakeLists.txt

* Update USE shaper to 2020-08-13 specification, and other improvements.
* And more… see <https://github.com/harfbuzz/harfbuzz/releases/tag/2.7.3>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1267)

thirdparty/harfbuzz 2.7.3

---

Makefile.defs
thirdparty/czmq/CMakeLists.txt
thirdparty/filemq/CMakeLists.txt
thirdparty/freetype2/CMakeLists.txt
thirdparty/giflib/CMakeLists.txt
thirdparty/libpng/CMakeLists.txt
thirdparty/libzmq/CMakeLists.txt
thirdparty/zyre/CMakeLists.txt

Closes #1237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1266)

android: unversioning shared libraries

---

Makefile.defs
thirdparty/czmq/CMakeLists.txt
thirdparty/filemq/CMakeLists.txt
thirdparty/freetype2/CMakeLists.txt
thirdparty/giflib/CMakeLists.txt
thirdparty/libpng/CMakeLists.txt
thirdparty/libzmq/CMakeLists.txt
thirdparty/zyre/CMakeLists.txt

Reverts koreader/koreader-base#1266
Because https://github.com/koreader/koreader/pull/7040#issuecomment-751459350, an unversioned libs in filesDir may clash with system libs.
I will apply it again on the future, once underlying issues were ironed out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1272)

Revert "android: unversioning shared libraries"

---

thirdparty/sdcv/sdcv.patch

Apparently Mac patch has some issues with my lazy manual update otherwise.
Fixes #1274.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1275)

Fully update sdcv patch

---

osx_loader.c

depends on koreader/koreader#7053
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1273)

Mac launcher: do not pass directory as argument

---

ffi/SDL2_0.lua

regression from koreader/koreader#7037
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1278)

Fix sdl Function & joystick input

---

Makefile.defs
ffi/input_android.lua
thirdparty/luajit/CMakeLists.txt
thirdparty/luajit/koreader-luajit-vanilla-mcode-debug.patch

Requires https://github.com/koreader/android-luajit-launcher/pull/283
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1279)

LuaJIT on Android fixes

---

thirdparty/tar/CMakeLists.txt

(Android patch still applies cleanly. Not that we build that on Android anymore :D).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1284)

Update GNU tar to 1.33

---

ffi/bitser.lua

From https://github.com/gvx/bitser
Removed love specific functions to pass Luacheck
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1281)

Add bitser

---

cre.cpp

Includes:
- EPUB: fix truncated HEAD>STYLE stylesheet https://github.com/koreader/crengine/pull/405
- XML parsing: slightly better parsing of `<script>`
- Update German hyphenation patterns https://github.com/koreader/crengine/pull/406
- (chore) Silence some clang warnings https://github.com/koreader/crengine/pull/407
- (Upstream) CSS content: fix regression with open-quote/close-quote
- (Upstream) HTML lists: support the 'reversed' attribute
- (Upstream) Tweak list items disc/circle/square symbols
- 2-pages mode: option to skip geometry checks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1286)

bump crengine: parsing, lists, 2-pages mode fixes & tweaks

---

Makefile.defs

Re https://github.com/koreader/koreader/issues/7175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1289)

Bundle lj_wpaclient on rM

---

thirdparty/kobo-usbms/CMakeLists.txt

https://github.com/koreader/KoboUSBMS/releases/tag/v1.1.1
Mainly I18N updates ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1294)

Update to KoboUSBMS 1.1.1

---

ffi/framebuffer_mxcfb.lua

This is a companion PR to https://github.com/koreader/koreader/pull/7166 ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1290)

Move HW dithering alignment fixup to base

---

ffi/SDL2_0.lua

This allows the client to handle things like dragged URLs and other
text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1291)

SDL: Handle and forward SDL_DROPTEXT events

---

thirdparty/tar/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1302)

Update GNU tar to 1.34

---

thirdparty/gettext/CMakeLists.txt

And make it less verbose, re: Android/GitLab being the worst.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1304)

Update to gettext 0.21

---

thirdparty/gettext/CMakeLists.txt
thirdparty/gettext/gettext-0.21-android-pre21-build.patch

maybe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1305)

Fix gettext 0.21 build on Android

---

thirdparty/gettext/CMakeLists.txt
thirdparty/gettext/gettext-0.21-android-pre21-build.patch

Wheee!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1306)

Really fix gettext on Android

---

thirdparty/openssl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1308)

Update to OpenSSL 1.1.1j

---

thirdparty/kobo-usbms/CMakeLists.txt

I18N ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1311)

Update to KoboUSBMS v1.1.1.1

---

thirdparty/utf8proc/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1316)

Update utf8proc to v2.6.1

---

wrap-mupdf.c
wrap-mupdf.h

Missed those :/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1317)

Fix visibility of custom non-wrapped MuPDF symbols.

---

thirdparty/luasec/CMakeLists.txt

https://github.com/brunoos/luasec/releases/tag/v1.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1297)

thirdparty/luasec v1.0

---

thirdparty/openssh/CMakeLists.txt
thirdparty/zstd/CMakeLists.txt
thirdparty/zstd/zstd-rpath.patch

* zstd 1.4.9
* OpenSSH 8.5p1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1319)

Third-party bumps

---

ffi/zstd_h.lua

[skip-ci]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1320)

Forgot to refresh zstd's FFI stuff

---

thirdparty/kobo-usbms/CMakeLists.txt

* User-friendly check if the SD card is busy, instead of a hard failure during umount, like we already did for onboard.
* Fancier clock updates ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1321)

Update to KoboUSBMS 1.2.0

---

ffi-cdecl/rtc_cdecl.c
ffi/rtc.lua
ffi/rtc_h.lua

Needed for Kobo shenanigans on devices whose system clock goes wonky during suspend.
(Re #https://github.com/koreader/koreader/issues/7092)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1322)

RTC: Implement HCToSys

---

thirdparty/fbink/CMakeLists.txt

Fix default behavior on PB devices w/ a B288 SoC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1324)

Bump FBInk

---

ffi/framebuffer_mxcfb.lua

*nobody noticed*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1325)

Kobo: Flag the Nia as Mk.7 (Oops.)

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/2.8.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1333)

thirdparty/harfbuzz 2.8.0

---

thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1336)

Update to SQLite 3.35.2

---

thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1340)

Update to SQLite 3.35.3

---

thirdparty/curl/CMakeLists.txt
thirdparty/luajit/CMakeLists.txt
thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1348)

Update SQLite, cURL & LuaJIT

---

thirdparty/nanosvg/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1351)

CRe & nanosvg bump

---

ffi/bitser.lua
ffi/sha2.lua

Also, jot down the exact commit it was taken from to ease maintenance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1353)

Minor bitser update

---

ffi-cdecl/linux_input_decl.c
ffi/linux_input_h.lua

[skip ci]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1354)

Input: add ABS_DISTANCE constant

---

thirdparty/curl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1357)

Update to cURL 7.76.1

---

thirdparty/luasec/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1362)

thirdparty/luasec v1.0.1

---

cre.cpp

Includes:
- MathML: a few minor fixes https://github.com/koreader/crengine/pull/435
- (Upstream) lvtext: fix possible index out of range
- Fonts: RegisterExternalFont() should take a documentId
- Fonts: fix: letter-spacing should not be applied on diacritic
- (Upstream) Fonts: more granular synthetic weights
- Fonts: synthesized weights: tweak some comments
- Fonts: keep hinting with synthetic weight
- Fonts: fix synthesized weight inconsitencies
- Fonts: fix getFontFileNameAndFaceIndex()
- Fonts: adds LVFontMan::RegularizeRegisteredFontsWeights()
- Fonts: handle synth_weight tweaks in glyph/glyphinfo slots
- (Upstream) Fonts: fix some compiler warnings
- Fix hyphenation on Armenian and Georgian text https://github.com/koreader/crengine/pull/436
cre.cpp: remove `toggleFontBolder()`, the …

bump crengine: more granular font weights

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/2.8.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1366)

thirdparty/harfbuzz 2.8.1

---

ffi/lru.lua

A minor fix to :clear, and templated functions to avoid branches in hot paths.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1368)

Some more LRU tweaks :)

---

thirdparty/zstd/CMakeLists.txt
thirdparty/zstd/zstd-rpath.patch

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1371)

Bump zstandard to v1.5.0

---

Makefile.defs
ffi-cdecl/mupdf_decl.c
ffi/util.lua
spec/unit/ffi_wrapper.lua
thirdparty/mupdf/CMakeLists.txt
thirdparty/mupdf/mupdf-1.13.0-backports.patch

Mainly the store overcommit issues, but also a few other potentially memory-management related stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1372)

Backport a semi-random assortment of MµPDF fixes

---

thirdparty/curl/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1376)

Update to cURL 7.77.0

---

thirdparty/luajit/CMakeLists.txt
thirdparty/luajit/koreader-luajit-makefile-tweaks.patch
thirdparty/sqlite/CMakeLists.txt

* SQLite
* LuaJIT
* CRe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1379)

Bump a few things

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/2.8.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1381)

Update to HB 2.8.2

---

ffi/utf8proc.lua

See comment https://github.com/koreader/koreader/pull/7956#issuecomment-880626432 by @poire-z
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1385)

Fix doc for ffi/utf8proc

---

thirdparty/freetype2/CMakeLists.txt

https://sourceforge.net/projects/freetype/files/freetype2/2.11.0/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1389)

Update to FreeType 2.11.0

---

ffi-cdecl/include/ion-kobo.h
ffi-cdecl/include/mxcfb-kobo.h
ffi-cdecl/include/sunxi-kobo.h
ffi-cdecl/ion_kobo_decl.c
ffi-cdecl/linux_fb_decl.c
ffi-cdecl/linux_input_decl.c
ffi-cdecl/mxcfb_kobo_decl.c
ffi-cdecl/sunxi_kobo_decl.c
ffi-cdecl/utf8proc_decl.c
ffi/framebuffer_ion.lua
ffi/framebuffer_linux.lua
ffi/framebuffer_mxcfb.lua
ffi/framebuffer_sunxi.lua
ffi/ion_kobo_h.lua
ffi/linux_fb_h.lua
ffi/linux_input_h.lua
ffi/mxcfb_kobo_h.lua
ffi/sunxi_kobo_h.lua
ffi/utf8proc_h.lua
thirdparty/fbink/CMakeLists.txt
thirdparty/kobo-usbms/CMakeLists.txt

It shouldn't sell your firstborn to the devil, but I haven't done much testing yet, and it's arguably unfinished.
But, it boots, and it mostly works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1386)

Kobo sunxi support (ion buffers/disp2 display driver)

---

thirdparty/curl/CMakeLists.txt
thirdparty/curl/curl-7.78.0-pb-rename.patch

https://curl.se/changes.html#7_78_0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1390)

Update to cURL 7.78.0

---

ffi/framebuffer_mxcfb.lua
ffi/utf8proc.lua

https://github.com/koreader/koreader/issues/8018
https://github.com/koreader/koreader/issues/8014
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1392)

A couple of fixes

---

thirdparty/libjpeg-turbo/CMakeLists.txt

https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/2.1.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1397)

Update to libjpeg-turbo 2.1.1

---

cre.cpp

See https://github.com/koreader/koreader/issues/8033#issuecomment-894274092
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1398)

cre: footnote popup detection: support type=endnote

---

thirdparty/openssl/CMakeLists.txt

Cf. https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9318#note_652827133 and https://github.com/koreader/koreader/issues/7924#issuecomment-900213635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1399)

Fix F-Droid build

---

thirdparty/luasec/CMakeLists.txt

https://github.com/brunoos/luasec/releases/tag/v1.0.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1401)

thirdparty/luasec v1.0.2

---

thirdparty/openssl/CMakeLists.txt

Will check after dinner if the patches need to be refreshed ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1403)

Update to OpenSSL 1.1.1l

---

thirdparty/fbink/CMakeLists.txt
thirdparty/kobo-usbms/CMakeLists.txt

Not much changes, besides properly tagged releases ;).
(And, well, `fbdepth` having been rewritten ;p).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1405)

Update FBInk & co

---

thirdparty/djvulibre/CMakeLists.txt

NB That just means it doesn't produce any errors *during build*.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1404)

win32: fix djvulibre build

---

thirdparty/curl/CMakeLists.txt
thirdparty/harfbuzz/CMakeLists.txt

* HarfBuzz [3.0.0](https://github.com/harfbuzz/harfbuzz/releases/tag/3.0.0)
* cURL [7.79.0](https://curl.se/changes.html#7_79_0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1411)

Third party updates

---

thirdparty/fribidi/CMakeLists.txt

In before @NiLuJe :angel: 
https://github.com/fribidi/fribidi/releases/tag/v1.0.11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1413)

thirdparty/fribidi 1.0.11

---

.circleci/config.yml

You could probably already merge this to get some of the builds going again but I won't have time to build the cross chains tonight.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1417)

[CI] New Docker images for updated root certificates

---

Makefile.defs

Forgot to ship the new files :x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1425)

Unbreak lj-wpaclient

---

button-listen.c

Suggestion to fix #1426 without breaking pre-firmware update compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1428)

Update button-listen for firmware update

---

thirdparty/freetype2/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1436)

thirdparty/freetype 2.11.1

---

cre.cpp

Fix bookmark dogear not shown when revisiting some page when hanging punctuation is enabled and the first char of the page is hanging in the left margin. See https://github.com/koreader/koreader/pull/6456#issuecomment-993461335
Also add `cre.smoothScaleBlitBuffer()` to allow benchmarking BB scaling methods on devices.
See https://github.com/koreader/koreader/pull/3905#issuecomment-989789750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1441)

cre.cpp: fix isXPointerInCurrentPage()

---

cre.cpp
ffi/util.lua

See https://github.com/koreader/koreader/issues/8619#issuecomment-1012506110.
Should allow closing https://github.com/koreader/koreader/issues/8619.
Also:
`FFIutil.runInSubProcess(): return error string on failure`
Couldn't get any failure, but might be useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1444)

cre.getTextFromPositions(): fix selection of single CJK char

---

thirdparty/luajit/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1448)

Bump LuaJIT (20220124)

---

ffi/SDL2_0.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1446)

SDL: add function to get linked version from frontend

---

thirdparty/fbink/CMakeLists.txt
thirdparty/kobo-usbms/CMakeLists.txt
thirdparty/luajit/CMakeLists.txt

Mainly for the sake of KoboUSBMS ;p.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1452)

Third-party updates

---

thirdparty/luajit/CMakeLists.txt

20220313
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1461)

Update LuaJIT (20220313)

---

ffi/mupdf.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1460)

Expose position for internal PDF links

---

ffi/utf8proc.lua

Do the lower casing of a string like crengine does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1458)

Utf8Proc: add a dumb lowercase method

---

thirdparty/kobo-usbms/CMakeLists.txt

Should fix more FW 4.31 weirdness on some devices...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1467)

Update KoboUSBMS to 1.2.7

---

thirdparty/kobo-usbms/CMakeLists.txt

Better deal with even more corner-cases ;).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1469)

Update to KoboUSBMS 1.3.0

---

cre.cpp

Includes https://github.com/koreader/crengine/pull/472 :
- LVString: fix char props, add lStr_isCJK() and lStr_isRTL()
- Rework is/prev/next-VisibleWord-Start/End()
- getCursorRect(): fix bottom point check
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1471)

bump crengine: rework char categorization and word selection

---

ffi-cdecl/linux_input_decl.c
ffi/linux_input_h.lua
input/input.c

Needed by https://github.com/koreader/koreader/pull/8987
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1478)

Input: Support getting/setting key repeat rates

---

thirdparty/cmake_modules/koreader_thirdparty_git.cmake

*sigh*
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1479)

CMake 3.23 vs. 3.5: battle of the stoopid

---

thirdparty/luasec/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1481)

thirdparty/luasec v1.1.0

---

cre.cpp

Includes https://github.com/koreader/crengine/pull/484 : 
- lvtext: fix `m_kerning_mode` type
- XML: let '`gb2312`' (Chinese) encoding be known
- Add `ldomXPointer::getChar()`
- `LVDocView::getNodeByPoint()`: tweak for text selection
- Fonts: allow fetching the list of embedded fonts
cre.cpp:
- `getTextFromPositions()`: use `getNodeByPoint(forTextSelection=true)` to allow panning in margins and get the nearest text instead of nothing. See https://github.com/koreader/koreader/issues/9169#issuecomment-1146625083.
- add `extendXPointersToSentenceSegment()` to allow extending some xpointer range to include punctuations at start or end (with for now a quite rudimentary implementation). See https://github.com/koreader/koreader/issues/8857#issuecomment-1151198923.
- add `getEmbeddedFontList()` …

bump crengine: text selection tweaks and helpers

---

ffi/SDL2_0.lua

See <https://github.com/libsdl-org/SDL/issues/5652> and <https://github.com/koreader/koreader/issues/9091>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1491)

ffi/SDL2: work around touch issue in SDL 2.0.22

---

input/input-kindle.h
input/input.c

koreader/koreader#9269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1499)

Kindle input: wakeupFromSuspend & readyToSuspend

---

thirdparty/turbo/turbo.patch

Cf. <https://github.com/koreader/koreader/issues/9306>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1501)

[fix] thirdparty/turbo: update patch

---

thirdparty/sdcv/CMakeLists.txt

Reverts koreader/koreader-base#1495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1502)

Revert "thirdparty/sdcv v0.5.4"

---

thirdparty/luasec/CMakeLists.txt

https://github.com/brunoos/luasec/releases/tag/v1.2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1509)

thirdparty/luasec 1.2.0

---

ffi/input_android.lua

This should hopefully better deal with the quirks of the Android API, especially as far as MT is concerned.
Requires https://github.com/koreader/koreader/pull/9463 to not horribly break.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1512)

Android: Refactor Android -> evdev input translation layer

---

thirdparty/harfbuzz/CMakeLists.txt

<https://github.com/harfbuzz/harfbuzz/releases/tag/5.2.0>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1519)

thirdparty/harfbuzz 5.2.0

---

thirdparty/fbink/CMakeLists.txt
thirdparty/kobo-usbms/CMakeLists.txt

For the Clara 2E
(At least as far as detection goes, I imagine the rotation stuff is wrong, proper support will require a guinea pig^W^Wfriendly tester ;)).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1521)

Update FBInk & KoboUSBMS

---

.luacheckrc
ffi/util.lua
thirdparty/lua-ljsqlite3/init.lua

Lest I forget about it ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1522)

Companion PR to https://github.com/koreader/koreader/pull/9546

---

ffi/pic.lua

Minor code style changes in ffi/pic ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1525)

Companion PR to https://github.com/koreader/koreader/pull/9586

---

ffi/serpent.lua

For slightly fancier pretty-printing ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1527)

Import serpent

---

ffi/utf8proc.lua

Use `libutf8proc.utf8proc_toupper` to convert string to uppercase.
Needed in Vietnamese keyboard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1528)

ffi add uppercase convert

---

thirdparty/sdcv/CMakeLists.txt
thirdparty/sdcv/sdcv-no-unknown-dict-warning.patch

We handle dictionary whitelisting and sorting ourselves, so this isn't helpful information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1532)

sdcv: Don't warn on unknown dictionaries

---

ffi/framebuffer_mxcfb.lua
ffi/framebuffer_sunxi.lua

Logger now handles nils, so get rid of the branching in there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1537)

Simplify fb debug messages

---

thirdparty/kobo-usbms/CMakeLists.txt

(i18n updates)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1538)

Bump KoboUSBMS

---

thirdparty/kobo-usbms/CMakeLists.txt

Small update to a tagged release (only meaningful change being dealing with devices w/ broken wait_for_complete ioctls).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1546)

Update to KoboUSBMS v1.3.3

---

Makefile.defs

No idea why it was trying to be a special snowflake: we build our own LuaJIT, use it!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1547)

Unbreak Luarocks on macOS (maybe)

---

ffi/blitbuffer.lua

And rename a couple of confusing/dumb ones.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1548)

BB: Add color constants for the full eInk palette

---

thirdparty/libunibreak/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1563)

Update to libunibreak 5.1

---

thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1569)

Bump SQLite to 3.40.1

---

ffi/framebuffer_mxcfb.lua

There's no per-update flag on mxcfb (instead there are global no-merge UPDATE_SCHEME modes). Since we don't want to mess with the global mode, we fake the fencing via explicit wait_for ioctl usage. To account for devices with broken wait_for ioctl (since those happen to be the target for testing this implementation), we force a much larger sleep than usual for the pre- fence (250 instead of 2.5ms).
Re: https://github.com/koreader/koreader/issues/9806#issuecomment-1416827447
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1576)

mxcfb: Implement fenced updates modes ([partial] & [ui])

---

ffi-cdecl/SDL2_0_decl.c
ffi/SDL2_0.lua
ffi/SDL2_0_h.lua

* fix a heap buffer overflow
* fix some (minor) memory leaks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1585)

SDL: miscellaneous fixes

---

Makefile.third
thirdparty/sqlite/CMakeLists.txt
thirdparty/sqlite/sqlite-72e2aa50968f0846f8738208b8770088bf280f25.patch

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1588)

Bump SQLite to 3.41.0

---

cre.cpp

Includes:
- https://github.com/koreader/crengine/pull/509
- LVStyleSheet: "const" some accessors
- LVStyleSheet: optimize `LVStyleSheet::merge`
- LVStyleSheet: simplify `insert_into_selectors` implementation
- https://github.com/koreader/crengine/pull/510
- Update German hyphenation patterns
- https://github.com/koreader/crengine/pull/511
- Header: render title/authors with book language glyphs
- Text: fix issues when hyphenation happened on a ligature
- getDocumentFileStream() support percent-encoded path
- getHtml(): add flag to get CSS selectors for met elements
- Add gatherStylesheetsMatchingRulesets(node)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1589)

bump crengine: optimizations, fixes, View HTML helpers

---

thirdparty/luasec/CMakeLists.txt

https://github.com/brunoos/luasec/compare/v1.2.0...v1.3.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1591)

thirdparty/luasec 1.3.1

---

ffi/util.lua

Regression from #1570.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1593)

Fix brew not found on non-Mac platforms

---

.circleci/config.yml

~~Maybe it will magically compile.~~
Cf. https://github.com/koreader/virdevenv/pull/84
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1597)

[CI] Switch Android Docker image from 18.04 to 22.04

---

.luarc.json

Because doing this globally is a PITA.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1621)

Add a config file for the Lua LSP

---

thirdparty/luajit/CMakeLists.txt
thirdparty/luajit/luajit-revert-b7a8c7c.patch

One of the few commits in the last bump appears to be causing us trouble...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1633)

Unbreak LuaJIT

---

ffi-cdecl/harfbuzz_cdecl.c
thirdparty/harfbuzz/CMakeLists.txt

Good thing I forgot about 8.1.0 yesterday ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1646)

Update to HarfBuzz 8.1.1

---

ffi/input_android.lua

See https://www.mobileread.com/forums/showpost.php?p=4351935&postcount=459
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1650)

android: forward play and pause to the system

---

thirdparty/harfbuzz/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1652)

Update to HarfBuzz 8.2.0

---

thirdparty/sqlite/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1653)

Update to SQLite 3.43.1

---

thirdparty/zlib/CMakeLists.txt

Fix #1654
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1655)

zlib: download it from GH

---

thirdparty/harfbuzz/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1657)

Update to HarfBuzz 8.2.1

---

spec/unit/common_spec.lua

So they can easily be filtered-out when offline.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1660)

tests: tag tests relying on a working internet access

---

blitbuffer.c
blitbuffer.h
ffi/blitbuffer.lua

Also fix BB_GET_PIXEL with proper parens around parameters that could be complex.
Will allow for fancy stuff in Page Browse. See https://github.com/koreader/koreader/issues/10193#issuecomment-1712537745 and follow ups.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1661)

BlitBuffer: add :hatchRect()

---

cre.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1668)

cre: free callback forwarder on quit

---

thirdparty/harfbuzz/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1670)

Bump harfbuzz to 8.2.2

---

thirdparty/libjpeg-turbo/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1671)

Bump libjpeg-turbo to 3.0.1

---

Makefile.defs
ffi-cdecl/zeromq_cdecl.c

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1688)

remove filemq / zyre leftovers

---

cre.cpp

Will be used by frontend to display a list of all matches. Also fix some cre.findText() arguments to be expected as booleans.
Required by, and needing (because of argument type changes) https://github.com/koreader/koreader/pull/11313
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1720)

cre.cpp: add cre.findAllText()

---

ffi/framebuffer_android.lua

Missed the _updateFull call site in #1718
Fix https://github.com/koreader/koreader/issues/11348
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1722)

FB/Android: Make sure we always pass a rect to _updatePartial

---

thirdparty/libjpeg-turbo/CMakeLists.txt

https://github.com/libjpeg-turbo/libjpeg-turbo/compare/3.0.1...3.0.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1733)

thirdparty/libjpeg-turbo 3.0.2

---

thirdparty/libpng/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1735)

Update to libpng 1.6.41

---

thirdparty/turbo/turbo.patch

Comes with a sense of déjà vu from #1501. In reply to https://github.com/koreader/koreader/issues/11535.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1741)

thirdparty/turbo: remove some cdefs to prevent duplicates

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/8.3.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1744)

thirdparty/harfbuzz: update to 8.3.1

---

.github/actions/brew_cache/action.yml
.github/workflows/build.yml

- install ccache from the upstream binary distribution
- build bottles for the brew packages we need and cache them
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1745)

CI: speedup macOS workflow

---

Makefile.defs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1749)

make: drop unused variables

---

Makefile.third
thirdparty/sdcv/CMakeLists.txt

Not needed on other platforms, fix regression introduced in #1690.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1754)

only compile gettext & libiconv on Android & macOS

---

cre.cpp

Depends on https://github.com/koreader/crengine/pull/560
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1758)

cre: add identifiers to doc props

---

thirdparty/luajit/CMakeLists.txt

Update LuaJIT to 20240310
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1765)

Update LuaJIT to 20240310

---

ffi/input_android.lua

used in some wired headphones
https://github.com/koreader/koreader/issues/11655
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1769)

forward headset hook

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1774)

ci: bump docker images

---

ffi/koptcontext.lua

Work in progress, the idea is to document what I learned so far, so that others interested in this stuff don't have to rediscover America again ;-). For now I'm adding a cheatsheet, with Leptonica's most common functions we use and short explanation how it's used/what it's used for. Later I'll try to add documentation to a few functions.
@poire-z Is something like this acceptable? I'm open to suggestions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1189)

KOPTContext - add comments explaining Leptonica's usage

---

ffi/input_SDL2_0.lua
ffi/input_android.lua
ffi/input_pocketbook.lua
input/input.c

* Allows front to explicitly request closing an open'ed fd
(Used in https://github.com/koreader/koreader/pull/11807)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1785)

Input: Add a close API

---

ffi/SDL2_0.lua

Also see https://github.com/koreader/koreader/pull/11871
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1793)

SDL: send ContextMenu when pressing gamecontroller Y button

---

Makefile.defs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1803)

make: set LTO jobs from `PARALLEL_JOBS`

---

.github/workflows/build.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1807)

ci/macos: add arm64 job

---

Makefile.defs

To support Alpine Linux.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1810)

make: tweak luarocks detection

---

.ci/common.sh
.ci/helper_shellchecks.sh
.ci/lint_script.sh
.ci/test_script.sh
utils/bindeps.sh
utils/libcheck.sh
utils/pdfattach
utils/shellcheck.sh

The plan is to use the new `./utils/shellcheck.sh` helper in koreader too, to avoid duplication and ensure the same standard is used.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1820)

improve linting

---

thirdparty/lua-rapidjson/CMakeLists.txt

Stupid typo made the calibre parser drop the uuid field ^^.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1833)

Bump lua-rapidjson

---

.github/workflows/build.yml

No wonder the macOS builds take so long…
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1843)

ci/macos: fix fallback cache key

---

thirdparty/openlipclua/CMakeLists.txt

Fix build w/ legacy TCs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1845)

Bump openlipclua

---

thirdparty/luasocket/CMakeLists.txt

fixes https://github.com/koreader/koreader/issues/12131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1844)

luasocket: don't patch on android

---

djvu.c
ffi/mupdf.lua

For https://github.com/koreader/koreader/pull/12085.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1848)

improve color handling

---

djvu.c
thirdparty/cmake_modules/koreader_targets.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1850)

djvu: improve debugging traces

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1851)

ci/circle: bump docker images

---

.ci/lint_script.sh
.cmakelintrc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1852)

ci: add cmakelint check

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1853)

ci/circle: add build timings

---

Makefile.defs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1854)

make: fix error message

---

thirdparty/fbink/CMakeLists.txt
thirdparty/kobo-usbms/CMakeLists.txt
thirdparty/luajit/CMakeLists.txt

FBInk & USBMS, and a few LuaJIT fixes while we're at it ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1855)

A round of small bumps

---

cre.cpp

Includes:
- xml parser: simplifications and optimizations https://github.com/koreader/crengine/pull/567
- lvstring: optimize Utf8ToUnicode https://github.com/koreader/crengine/pull/571 
- https://github.com/koreader/crengine/pull/572 : 
- lvstream: add helper to read the whole stream
- lvfntman: use new `LVStream::GetData` helper
- EPUB: minor simplification
- EPUB: fix possible buffer overflows
- EPUB: improve support for obfuscated fonts
- lvfntman: add error traces for some freetype calls https://github.com/koreader/crengine/pull/573
- LVDocView header: allow displaying author and book title separately https://github.com/koreader/crengine/pull/575
- https://github.com/koreader/crengine/pull/578 :
- LVFontDef::CalcMatch(): bump weight of typeface match
- Font: fix measureText() when …

bump crengine: various fixes and optimizations

---

thirdparty/kpvcrlib/crsetup.h.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1860)

crengine: minor cleanup

---

thirdparty/kpvcrlib/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1869)

crengine: sort source list

---

Makefile.defs
utils/gen_linker_exports.sh

Cf. #1873.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1875)

2 build system tweaks to support more environments

---

thirdparty/gettext/CMakeLists.txt
thirdparty/libiconv/CMakeLists.txt
thirdparty/tar/CMakeLists.txt

To another mirror, in case gnu.org is down.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1878)

gettext & libiconv & tar: add fallback URLs

---

thirdparty/kpvcrlib/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1871)

bump crengine: fix some warnings!

---

thirdparty/lj-wpaclient/CMakeLists.txt

For https://github.com/koreader/lj-wpaclient/pull/11
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1879)

Bump lj-wpaclient

---

Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1882)

make: drop unused leftover rule

---

.github/workflows/build.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1884)

ci/macos: don't install sdl2 (not needed)

---

utils/bininfo.py

Handle the SDL2 library (cf. macOS build issues in https://github.com/koreader/koreader/pull/12265).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1883)

utils: improve `bincheck` macOS support

---

cre.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1885)

bump crengine

---

thirdparty/libpng/CMakeLists.txt

Changelogs (nothing major):
- [1.6.42](http://www.libpng.org/pub/png/src/libpng-1.6.42-README.txt)
- [1.6.43](http://www.libpng.org/pub/png/src/libpng-1.6.43-README.txt)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1887)

libpng: update to 1.6.43

---

thirdparty/zlib/CMakeLists.txt

Changelog (nothing major): https://www.zlib.net/.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1888)

zlib: update to 1.3.1

---

thirdparty/sqlite/CMakeLists.txt

Changelogs (nothing major):
- [3.45.3](https://sqlite.org/releaselog/3_45_3.html)
- [3.46.0](https://sqlite.org/releaselog/3_46_0.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1889)

sqlite: update to 3.46.0

---

thirdparty/fbink/CMakeLists.txt
thirdparty/kobo-usbms/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1896)

Minor fbink/usbms bumps

---

thirdparty/luajit/CMakeLists.txt
thirdparty/luajit/koreader-luajit-mcode-debug.patch
thirdparty/luajit/koreader-luajit-mcode-reserve-hack.patch

Cf. https://github.com/koreader/koreader/pull/12285.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1899)

luajit: add android luajit-launcher patch

---

.github/workflows/build.yml

Started to fail on the `x86_64` job: https://github.com/benoit-pierre/koreader-base/actions/runs/10454946648/job/28950252358.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1909)

ci/macos: fix homebrew packages install

---

ffi/util.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1911)

ffi/util: remove dead code

---

thirdparty/luajit/CMakeLists.txt

*Should* be mostly tame ;).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1913)

Update to LuaJIT 20240824

---

.busted
Makefile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1915)

tests: allow overriding the list of tests to run

---

thirdparty/fribidi/CMakeLists.txt

https://github.com/fribidi/fribidi/releases/tag/v1.0.15
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1914)

fribidi: update to 1.0.15

---

cre.cpp

Fix https://github.com/koreader/koreader/issues/12435#issuecomment-2322752801
(Tried first to fix the wrap around in crengine, but it was not obvious... So, local fix it is.)
Also bump crengine:
fix xml parser regression (infinite loop) https://github.com/koreader/crengine/pull/602
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1919)

cre.cpp: fix findAllText() context at end of book, bump crengine

---

thirdparty/tesseract/CMakeLists.txt
thirdparty/tesseract/cmake_tweaks.patch

- https://github.com/tesseract-ocr/tesseract/releases/tag/5.4.0
- https://github.com/tesseract-ocr/tesseract/releases/tag/5.4.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1931)

tesseract: update to 5.4.1

---

thirdparty/lpeg/CMakeLists.txt
thirdparty/lpeg/overlay/CMakeLists.txt

For #1920.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1934)

lpeg: switch to cmake for building

---

thirdparty/openlipclua/CMakeLists.txt

Prerequisite for #1920.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1936)

openlipclua: switch to cmake for building

---

thirdparty/turbo/CMakeLists.txt
thirdparty/turbo/overlay/CMakeLists.txt

For #1920.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1942)

turbo: switch to cmake for building

---

ffi/loadlib.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1939)

ffi/loadlib: add some documentation

---

thirdparty/harfbuzz/CMakeLists.txt

- https://github.com/harfbuzz/harfbuzz/releases/tag/10.0.0
- https://github.com/harfbuzz/harfbuzz/releases/tag/10.0.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1945)

harfbuzz: update to 10.0.1

---

thirdparty/fribidi/CMakeLists.txt

https://github.com/fribidi/fribidi/releases/tag/v1.0.16
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1944)

fribidi: update to 1.0.16

---

thirdparty/cmake_modules/koreader_targets.cmake

Cf. https://github.com/koreader/koreader/issues/12546#issuecomment-2391710914.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1948)

macos: fix wrap-mupdf library extension

---

ffi/loadlib.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1949)

macos: fix monolibtic library extension

---

Makefile
Makefile.defs
thirdparty/cmake_modules/koenv.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1952)

minor build system improvements

---

utils/bininfo.py

Correctly handle binaries with a `runpath` entry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1950)

utils: fix bininfo helper

---

ffi/posix_h.lua
ffi/util.lua

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1955)

ffi/posix: fix `FIONREAD` value on macOS

---

thirdparty/luajit/CMakeLists.txt

https://github.com/LuaJIT/LuaJIT/compare/87ae18af97fd4de790bb6c476b212e047689cc93...97813fb924edf822455f91a5fbbdfdb349e5984f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1957)

luajit: bump to 2.0.1727618617

---

ffi/mupdf.lua
thirdparty/mupdf/CMakeLists.txt

https://www.mupdf.com/releases/history
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1963)

mupdf: update to 1.24.10

---

thirdparty/dropbear/CMakeLists.txt
thirdparty/dropbear/localoptions.h.cmake

https://github.com/mkj/dropbear/releases/tag/DROPBEAR_2024.86
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1966)

dropbear: update to 2024.86

---

djvu.c
djvu.h
ffi/mupdf.lua
thirdparty/cmake_modules/koreader_targets.cmake
thirdparty/cmake_modules/koreader_thirdparty_libs.cmake

Factorized to the upper layers (`koptinterface`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1974)

djvu & mupdf: drop reflow support

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/10.1.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1979)

harfbuzz: update to 10.1.0

---

.circleci/config.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1988)

ci/circle: add kindlehf to build matrix

---

.busted
.ci/test_script.sh
.circleci/config.yml
.github/workflows/build.yml
Makefile
Makefile.defs
cache-key.base
test-runner/busted_config.lua
test-runner/meson.build
test-runner/runtests

Cf. https://github.com/koreader/koreader/pull/12789.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1989)

tests: add new runner

---

Makefile.defs
cmake/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1996)

cmake: enable some warnings

---

test-runner/runtests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1998)

minor testsuite fixes

---

thirdparty/sqlite/CMakeLists.txt

https://sqlite.org/releaselog/3_47_2.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/1999)

sqlite: update to 3.47.2

---

thirdparty/lua-Spore/CMakeLists.txt

https://framagit.org/fperrad/lua-Spore/-/compare/0.3.3..0.3.4
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2003)

thirdparty/lua-Spore 0.3.4

---

Makefile.defs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2007)

fix linux target architecture flags

---

ffi/mupdf.lua
ffi/mupdf_h.lua
thirdparty/mupdf/CMakeLists.txt
thirdparty/mupdf/css_color_names.patch
thirdparty/mupdf/encrypted_zip.patch
thirdparty/mupdf/external_fonts.patch
thirdparty/mupdf/free-html-doc-fonts-on-close.patch
thirdparty/mupdf/honor_cflags.patch
thirdparty/mupdf/mupdf_cbz_chapter_support.patch
thirdparty/mupdf/no_arm_asm.patch
thirdparty/mupdf/relink_on_xlibs_change.patch
thirdparty/mupdf/visibility.patch
thirdparty/mupdf/webp-upstream-697749.patch

https://www.mupdf.com/releases/history
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2017)

mupdf: update to 1.25.2

---

thirdparty/libpng/CMakeLists.txt
thirdparty/libpng/math_library.patch

https://github.com/pnggroup/libpng/blob/v1.6.46/CHANGES#L6199
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2025)

libpng: update to 1.6.46

---

thirdparty/sdl2/CMakeLists.txt
thirdparty/sdl2/cmake_tweaks.patch
thirdparty/sdl2/cocoa.patch

- https://github.com/libsdl-org/SDL/releases/tag/release-2.30.7
- https://github.com/libsdl-org/SDL/releases/tag/release-2.30.8
- https://github.com/libsdl-org/SDL/releases/tag/release-2.30.9
- https://github.com/libsdl-org/SDL/releases/tag/release-2.30.10
- https://github.com/libsdl-org/SDL/releases/tag/release-2.30.11
- https://github.com/libsdl-org/SDL/releases/tag/release-2.30.12
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2031)

sdl2: update to 2.30.12

---

thirdparty/sqlite/CMakeLists.txt

https://sqlite.org/releaselog/3_49_1.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2035)

sqlite: update to 3.49.1

---

thirdparty/utf8proc/CMakeLists.txt

https://github.com/JuliaStrings/utf8proc/releases/tag/v2.10.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2036)

utf8proc: update to 2.10.0

---

spec/unit/mupdf_spec.lua
test-runner/busted_helper.lua
test-runner/runtests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2032)

minor testsuite improvements

---

ffi/utf8proc_h.lua

Forgot to update those as part of #2036.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2037)

ffi/utf8proc: fix cdecls after 2.10.0 update

---

Makefile.defs
thirdparty/zstd/CMakeLists.txt
thirdparty/zstd/no_qsort_r.patch

https://github.com/facebook/zstd/releases/tag/v1.5.7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2038)

zstd: update to 1.5.7

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/10.3.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2040)

harfbuzz: update to 10.3.0

---

thirdparty/dropbear/CMakeLists.txt
thirdparty/dropbear/dbscp-path.patch
thirdparty/dropbear/fix-static_asserts.patch
thirdparty/dropbear/localoptions.h.cmake
thirdparty/dropbear/nopasswd-hack.patch
thirdparty/dropbear/pubkey-hack.patch
thirdparty/dropbear/reduce_build_verbosity.patch

https://github.com/mkj/dropbear/releases/tag/DROPBEAR_2025.87
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2056)

dropbear: update to 2025.87

---

thirdparty/luajit/CMakeLists.txt
thirdparty/luajit/koreader-luajit-enable-table_pack.patch
thirdparty/luajit/koreader-luajit-makefile-tweaks.patch
thirdparty/luajit/koreader-luajit-mcode-debug.patch
thirdparty/luajit/koreader-luajit-mcode-reserve-hack.patch
thirdparty/spec/luasystem/CMakeLists.txt

https://github.com/LuaJIT/LuaJIT/compare/97813fb9...eec7a801
Note: luasystem had to be updated to >= 0.4.5 first: https://github.com/lunarmodules/luasystem/compare/v0.4.4...v0.6.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2054)

luajit: update to 2.1.1744318430

---

Makefile.defs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2059)

reMarkable Paper Pro support

---

thirdparty/openssh/CMakeLists.txt

- https://www.openssh.com/txt/release-9.7
- https://www.openssh.com/txt/release-9.8
- https://www.openssh.com/txt/release-9.9
- https://www.openssh.com/txt/release-9.9p2
- https://www.openssh.com/txt/release-10.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2065)

openssh: update to 10.0p1

---

thirdparty/libpng/CMakeLists.txt

https://github.com/pnggroup/libpng/blob/v1.6.48/CHANGES#L6254
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2072)

libpng: update to 1.6.48

---

thirdparty/fbink/CMakeLists.txt

https://github.com/NiLuJe/FBInk/compare/ab450182...8ce07a0c
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2077)

fbink: update to 1.25.0-490-g8ce07a0c

---

thirdparty/harfbuzz/CMakeLists.txt
thirdparty/harfbuzz/no-paint.patch

- https://github.com/harfbuzz/harfbuzz/releases/tag/11.1.0
- https://github.com/harfbuzz/harfbuzz/releases/tag/11.2.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2082)

harfbuzz: update to 11.2.0

---

thirdparty/libressl/CMakeLists.txt
thirdparty/libressl/android.patch

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2081)

libressl: fix android build in non-monolibtic mode

---

thirdparty/lua-Spore/CMakeLists.txt
thirdparty/lua-Spore/content-type-detection.patch

Accept multi-valued content-types once again.
Regression in 0.4.0
Re: https://github.com/koreader/koreader/issues/13629
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2062)

Patch lua-Spore to unbreak content-type detection

---

ffi/crypto.lua

Cf. https://github.com/koreader/koreader/issues/13781#issuecomment-2880887699 & #2073.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2087)

ffi/crypto: fix loading of crypto library

---

thirdparty/libarchive/CMakeLists.txt

Cf. https://github.com/koreader/koreader-base/pull/2083#issuecomment-2886049283.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2089)

libarchive: avoid depending on libmd

---

thirdparty/cpu_features/CMakeLists.txt

- https://github.com/google/cpu_features/releases/tag/v0.10.0
- https://github.com/google/cpu_features/releases/tag/v0.10.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2104)

cpu_features: update to 0.10.1

---

thirdparty/sdl2/CMakeLists.txt

- https://github.com/libsdl-org/SDL/releases/tag/release-2.32.6
- https://github.com/libsdl-org/SDL/releases/tag/release-2.32.8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2103)

sdl2: update to 2.32.8

---

thirdparty/sqlite/CMakeLists.txt

https://sqlite.org/releaselog/3_50_1.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2102)

sqlite: update to 3.50.1

---

thirdparty/sqlite/CMakeLists.txt

https://sqlite.org/releaselog/3_50_2.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2119)

sqlite: update to 3.50.2

---

cmake/CMakeLists.txt
ffi/mupdf.lua
thirdparty/mupdf/CMakeLists.txt

https://mupdf.com/releases/history
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2120)

mupdf: update to 1.26.3

---

thirdparty/xz/CMakeLists.txt

There's only one user: libarchive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2121)

xz: always build a static library

---

thirdparty/cmake_modules/koreader_thirdparty_libs.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2131)

xz: fix android non-monolibtic build

---

thirdparty/sqlite/CMakeLists.txt

https://sqlite.org/releaselog/3_50_3.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2137)

sqlite: update to 3.50.3

---

thirdparty/luajit/CMakeLists.txt

https://github.com/LuaJIT/LuaJIT/compare/f9140a62...871db2c8
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2141)

luajit: update to 2.1.1753364724

---

thirdparty/harfbuzz/CMakeLists.txt

https://github.com/harfbuzz/harfbuzz/releases/tag/11.3.3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2144)

harfbuzz: update to 11.3.3

---

test-runner/runtests

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2147)

tests: fix test runner shellcheck 0.11.0 false positives

---

thirdparty/harfbuzz/CMakeLists.txt
thirdparty/harfbuzz/android.patch
thirdparty/harfbuzz/no-subset.patch

- https://github.com/harfbuzz/harfbuzz/releases/tag/11.4.0
- https://github.com/harfbuzz/harfbuzz/releases/tag/11.4.1
- https://github.com/harfbuzz/harfbuzz/releases/tag/11.4.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2150)

harfbuzz: update to 11.4.2

---

ffi/mupdf.lua
thirdparty/mupdf/CMakeLists.txt

https://mupdf.com/releases/history
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2152)

mupdf: update to 1.26.7

---

thirdparty/harfbuzz/CMakeLists.txt

- https://github.com/harfbuzz/harfbuzz/releases/tag/11.4.4
- https://github.com/harfbuzz/harfbuzz/releases/tag/11.4.5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2153)

harbuzz: update to 11.4.5

---

thirdparty/cmake_modules/koreader_targets.cmake
thirdparty/cmake_modules/koreader_thirdparty_libs.cmake

Fix regression from #2158.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2161)

koreader-lfs: fix monolibtic build

---

.github/workflows/build.yml

Reduce differences with koreader.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2169)

ci/macos: tweaks

---

Makefile.defs
thirdparty/sdl2/appimage.patch

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2171)

appimage: support aarch64

---

Makefile.defs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2176)

appimage: fix architecture specific compilation flags

---

thirdparty/harfbuzz/CMakeLists.txt
thirdparty/harfbuzz/android.patch
thirdparty/harfbuzz/no-subset.patch

- https://github.com/harfbuzz/harfbuzz/releases/tag/11.5.0
- https://github.com/harfbuzz/harfbuzz/releases/tag/11.5.1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2180)

harfbuzz: update to 11.5.1

---

Makefile.defs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2182)

fix optimization flags (particularly LTO) when using clang

---

cre.cpp

Includes:
- lvtinydom: buildSyntheticPageMap(): clean page info https://github.com/koreader/crengine/pull/635
Will be useful to https://github.com/koreader/koreader/pull/14405
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/koreader/koreader-base/2183)

bump crengine, cre.cpp: add a few more PageMap / synthetic pages methods
